<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notifies/notify.proto

namespace Fatehan\Notify;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.notifies.EventList</code>
 */
class EventList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 total = 1 [json_name = "total"];</code>
     */
    protected $total = 0;
    /**
     * Generated from protobuf field <code>uint32 current_page = 2 [json_name = "current_page"];</code>
     */
    protected $current_page = 0;
    /**
     * Generated from protobuf field <code>uint32 last_page = 3 [json_name = "last_page"];</code>
     */
    protected $last_page = 0;
    /**
     * Generated from protobuf field <code>uint32 per_page = 4 [json_name = "per_page"];</code>
     */
    protected $per_page = 0;
    /**
     * Generated from protobuf field <code>repeated .com.fatehan.notifies.Event events = 5 [json_name = "events"];</code>
     */
    private $events;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $total
     *     @type int $current_page
     *     @type int $last_page
     *     @type int $per_page
     *     @type \Fatehan\Notify\Event[] $events
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Notify\MetaData\Notify::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 total = 1 [json_name = "total"];</code>
     * @return int
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>uint32 total = 1 [json_name = "total"];</code>
     * @param int $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkUint32($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 current_page = 2 [json_name = "current_page"];</code>
     * @return int
     */
    public function getCurrentPage()
    {
        return $this->current_page;
    }

    /**
     * Generated from protobuf field <code>uint32 current_page = 2 [json_name = "current_page"];</code>
     * @param int $var
     * @return $this
     */
    public function setCurrentPage($var)
    {
        GPBUtil::checkUint32($var);
        $this->current_page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 last_page = 3 [json_name = "last_page"];</code>
     * @return int
     */
    public function getLastPage()
    {
        return $this->last_page;
    }

    /**
     * Generated from protobuf field <code>uint32 last_page = 3 [json_name = "last_page"];</code>
     * @param int $var
     * @return $this
     */
    public function setLastPage($var)
    {
        GPBUtil::checkUint32($var);
        $this->last_page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 per_page = 4 [json_name = "per_page"];</code>
     * @return int
     */
    public function getPerPage()
    {
        return $this->per_page;
    }

    /**
     * Generated from protobuf field <code>uint32 per_page = 4 [json_name = "per_page"];</code>
     * @param int $var
     * @return $this
     */
    public function setPerPage($var)
    {
        GPBUtil::checkUint32($var);
        $this->per_page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.notifies.Event events = 5 [json_name = "events"];</code>
     * @return RepeatedField<\Fatehan\Notify\Event>
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.notifies.Event events = 5 [json_name = "events"];</code>
     * @param \Fatehan\Notify\Event[] $var
     * @return $this
     */
    public function setEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fatehan\Notify\Event::class);
        $this->events = $arr;

        return $this;
    }

}

