<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notifies/notify.proto

namespace Fatehan\Notify;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.notifies.GsmEvent</code>
 */
class GsmEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 signal_below = 1;</code>
     */
    protected $signal_below = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $signal_below
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Notify\MetaData\Notify::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 signal_below = 1;</code>
     * @return int
     */
    public function getSignalBelow()
    {
        return $this->signal_below;
    }

    /**
     * Generated from protobuf field <code>uint32 signal_below = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSignalBelow($var)
    {
        GPBUtil::checkUint32($var);
        $this->signal_below = $var;

        return $this;
    }

}

