<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notifies/notify.proto

namespace Fatehan\Notify;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.notifies.Notification</code>
 */
class Notification extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string uuid = 1 [json_name = "uuid"];</code>
     */
    protected $uuid = '';
    /**
     * Generated from protobuf field <code>uint64 user_id = 2 [json_name = "user_id"];</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>optional uint64 object_id = 3 [json_name = "object_id"];</code>
     */
    protected $object_id = null;
    /**
     * Generated from protobuf field <code>optional .com.fatehan.notifies.ObjectType object_type = 4 [json_name = "object_type"];</code>
     */
    protected $object_type = null;
    /**
     * Generated from protobuf field <code>string title = 5 [json_name = "title"];</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>optional string body = 6 [json_name = "body"];</code>
     */
    protected $body = null;
    /**
     * Generated from protobuf field <code>optional uint64 alert_id = 7 [json_name = "alert_id"];</code>
     */
    protected $alert_id = null;
    /**
     * Generated from protobuf field <code>.com.fatehan.packets.Alert alert = 8 [json_name = "alert"];</code>
     */
    protected $alert = 0;
    /**
     * Generated from protobuf field <code>repeated .com.fatehan.notifies.Via via = 9 [json_name = "via"];</code>
     */
    private $via;
    /**
     * Generated from protobuf field <code>map<string, string> data = 10 [json_name = "data"];</code>
     */
    private $data;
    /**
     * Generated from protobuf field <code>optional string image = 11 [json_name = "image"];</code>
     */
    protected $image = null;
    /**
     * Generated from protobuf field <code>optional uint64 sound = 12 [json_name = "sound"];</code>
     */
    protected $sound = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 13 [json_name = "created_at"];</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp read_at = 14 [json_name = "read_at"];</code>
     */
    protected $read_at = null;
    /**
     * Generated from protobuf field <code>optional uint64 user_alert_id = 15 [json_name = "user_alert_id"];</code>
     */
    protected $user_alert_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uuid
     *     @type int|string $user_id
     *     @type int|string $object_id
     *     @type int $object_type
     *     @type string $title
     *     @type string $body
     *     @type int|string $alert_id
     *     @type int $alert
     *     @type int[] $via
     *     @type array|\Google\Protobuf\Internal\MapField $data
     *     @type string $image
     *     @type int|string $sound
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type \Google\Protobuf\Timestamp $read_at
     *     @type int|string $user_alert_id
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Notify\MetaData\Notify::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string uuid = 1 [json_name = "uuid"];</code>
     * @return string
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * Generated from protobuf field <code>string uuid = 1 [json_name = "uuid"];</code>
     * @param string $var
     * @return $this
     */
    public function setUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 user_id = 2 [json_name = "user_id"];</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>uint64 user_id = 2 [json_name = "user_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkUint64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint64 object_id = 3 [json_name = "object_id"];</code>
     * @return int|string
     */
    public function getObjectId()
    {
        return isset($this->object_id) ? $this->object_id : 0;
    }

    public function hasObjectId()
    {
        return isset($this->object_id);
    }

    public function clearObjectId()
    {
        unset($this->object_id);
    }

    /**
     * Generated from protobuf field <code>optional uint64 object_id = 3 [json_name = "object_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setObjectId($var)
    {
        GPBUtil::checkUint64($var);
        $this->object_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .com.fatehan.notifies.ObjectType object_type = 4 [json_name = "object_type"];</code>
     * @return int
     */
    public function getObjectType()
    {
        return isset($this->object_type) ? $this->object_type : 0;
    }

    public function hasObjectType()
    {
        return isset($this->object_type);
    }

    public function clearObjectType()
    {
        unset($this->object_type);
    }

    /**
     * Generated from protobuf field <code>optional .com.fatehan.notifies.ObjectType object_type = 4 [json_name = "object_type"];</code>
     * @param int $var
     * @return $this
     */
    public function setObjectType($var)
    {
        GPBUtil::checkEnum($var, \Fatehan\Notify\ObjectType::class);
        $this->object_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 5 [json_name = "title"];</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 5 [json_name = "title"];</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string body = 6 [json_name = "body"];</code>
     * @return string
     */
    public function getBody()
    {
        return isset($this->body) ? $this->body : '';
    }

    public function hasBody()
    {
        return isset($this->body);
    }

    public function clearBody()
    {
        unset($this->body);
    }

    /**
     * Generated from protobuf field <code>optional string body = 6 [json_name = "body"];</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint64 alert_id = 7 [json_name = "alert_id"];</code>
     * @return int|string
     */
    public function getAlertId()
    {
        return isset($this->alert_id) ? $this->alert_id : 0;
    }

    public function hasAlertId()
    {
        return isset($this->alert_id);
    }

    public function clearAlertId()
    {
        unset($this->alert_id);
    }

    /**
     * Generated from protobuf field <code>optional uint64 alert_id = 7 [json_name = "alert_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setAlertId($var)
    {
        GPBUtil::checkUint64($var);
        $this->alert_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.packets.Alert alert = 8 [json_name = "alert"];</code>
     * @return int
     */
    public function getAlert()
    {
        return $this->alert;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.packets.Alert alert = 8 [json_name = "alert"];</code>
     * @param int $var
     * @return $this
     */
    public function setAlert($var)
    {
        GPBUtil::checkEnum($var, \Fatehan\Packet\DataModel\Alert::class);
        $this->alert = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.notifies.Via via = 9 [json_name = "via"];</code>
     * @return RepeatedField<int>
     */
    public function getVia()
    {
        return $this->via;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.notifies.Via via = 9 [json_name = "via"];</code>
     * @param int[] $var
     * @return $this
     */
    public function setVia($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Fatehan\Notify\Via::class);
        $this->via = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> data = 10 [json_name = "data"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>map<string, string> data = 10 [json_name = "data"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->data = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string image = 11 [json_name = "image"];</code>
     * @return string
     */
    public function getImage()
    {
        return isset($this->image) ? $this->image : '';
    }

    public function hasImage()
    {
        return isset($this->image);
    }

    public function clearImage()
    {
        unset($this->image);
    }

    /**
     * Generated from protobuf field <code>optional string image = 11 [json_name = "image"];</code>
     * @param string $var
     * @return $this
     */
    public function setImage($var)
    {
        GPBUtil::checkString($var, True);
        $this->image = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint64 sound = 12 [json_name = "sound"];</code>
     * @return int|string
     */
    public function getSound()
    {
        return isset($this->sound) ? $this->sound : 0;
    }

    public function hasSound()
    {
        return isset($this->sound);
    }

    public function clearSound()
    {
        unset($this->sound);
    }

    /**
     * Generated from protobuf field <code>optional uint64 sound = 12 [json_name = "sound"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setSound($var)
    {
        GPBUtil::checkUint64($var);
        $this->sound = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 13 [json_name = "created_at"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 13 [json_name = "created_at"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp read_at = 14 [json_name = "read_at"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getReadAt()
    {
        return $this->read_at;
    }

    public function hasReadAt()
    {
        return isset($this->read_at);
    }

    public function clearReadAt()
    {
        unset($this->read_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp read_at = 14 [json_name = "read_at"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setReadAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->read_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint64 user_alert_id = 15 [json_name = "user_alert_id"];</code>
     * @return int|string
     */
    public function getUserAlertId()
    {
        return isset($this->user_alert_id) ? $this->user_alert_id : 0;
    }

    public function hasUserAlertId()
    {
        return isset($this->user_alert_id);
    }

    public function clearUserAlertId()
    {
        unset($this->user_alert_id);
    }

    /**
     * Generated from protobuf field <code>optional uint64 user_alert_id = 15 [json_name = "user_alert_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserAlertId($var)
    {
        GPBUtil::checkUint64($var);
        $this->user_alert_id = $var;

        return $this;
    }

}

