<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notifies/notify.proto

namespace Fatehan\Notify;

use UnexpectedValueException;

/**
 * Protobuf type <code>com.fatehan.notifies.ObjectType</code>
 */
class ObjectType
{
    /**
     * Generated from protobuf enum <code>UNSPECIFIED = 0;</code>
     */
    const UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>DEVICE = 1;</code>
     */
    const DEVICE = 1;
    /**
     * Generated from protobuf enum <code>USER = 2;</code>
     */
    const USER = 2;
    /**
     * Generated from protobuf enum <code>OPERATION = 3;</code>
     */
    const OPERATION = 3;
    /**
     * Generated from protobuf enum <code>WORKFLOW_TASK = 4;</code>
     */
    const WORKFLOW_TASK = 4;
    /**
     * Generated from protobuf enum <code>MAINTENANCE = 5;</code>
     */
    const MAINTENANCE = 5;
    /**
     * Generated from protobuf enum <code>EVENT = 6;</code>
     */
    const EVENT = 6;

    private static $valueToName = [
        self::UNSPECIFIED => 'UNSPECIFIED',
        self::DEVICE => 'DEVICE',
        self::USER => 'USER',
        self::OPERATION => 'OPERATION',
        self::WORKFLOW_TASK => 'WORKFLOW_TASK',
        self::MAINTENANCE => 'MAINTENANCE',
        self::EVENT => 'EVENT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

