<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notifies/direct.proto

namespace Fatehan\Notify;

use UnexpectedValueException;

/**
 * Protobuf type <code>com.fatehan.notifies.Platform</code>
 */
class Platform
{
    /**
     * Generated from protobuf enum <code>UNSPECIFICED = 0;</code>
     */
    const UNSPECIFICED = 0;
    /**
     * Generated from protobuf enum <code>ANDROID = 1;</code>
     */
    const ANDROID = 1;
    /**
     * Generated from protobuf enum <code>WEB = 2;</code>
     */
    const WEB = 2;
    /**
     * Generated from protobuf enum <code>IOS = 3;</code>
     */
    const IOS = 3;
    /**
     * Generated from protobuf enum <code>DESKTOP = 4;</code>
     */
    const DESKTOP = 4;

    private static $valueToName = [
        self::UNSPECIFICED => 'UNSPECIFICED',
        self::ANDROID => 'ANDROID',
        self::WEB => 'WEB',
        self::IOS => 'IOS',
        self::DESKTOP => 'DESKTOP',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

