<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifies/notify.proto

namespace Fatehan\Notify;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.fatehan.notifies.SpeedEvent</code>
 */
class SpeedEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 speed_limit = 1 [json_name = "speed_limit"];</code>
     */
    protected $speed_limit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $speed_limit
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Notify\MetaData\Notify::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 speed_limit = 1 [json_name = "speed_limit"];</code>
     * @return int
     */
    public function getSpeedLimit()
    {
        return $this->speed_limit;
    }

    /**
     * Generated from protobuf field <code>uint32 speed_limit = 1 [json_name = "speed_limit"];</code>
     * @param int $var
     * @return $this
     */
    public function setSpeedLimit($var)
    {
        GPBUtil::checkUint32($var);
        $this->speed_limit = $var;

        return $this;
    }

}

