<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notifies/notify.proto

namespace Fatehan\Notify;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Deprecated: Use UserAlert instead
 *
 * Generated from protobuf message <code>com.fatehan.notifies.UserDeviceAlert</code>
 */
class UserDeviceAlert extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1 [json_name = "id"];</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>uint64 user_id = 2 [json_name = "user_id"];</code>
     */
    protected $user_id = 0;
    /**
     * Generated from protobuf field <code>uint64 device_id = 4 [json_name = "device_id"];</code>
     */
    protected $device_id = 0;
    /**
     * Generated from protobuf field <code>uint64 organization_id = 11 [json_name = "organization_id"];</code>
     */
    protected $organization_id = 0;
    /**
     * Generated from protobuf field <code>uint64 alert_id = 5 [json_name = "alert_id"];</code>
     */
    protected $alert_id = 0;
    /**
     * Generated from protobuf field <code>map<uint32, .com.fatehan.notifies.UserDeviceAlert.ConditionList> condition = 6 [json_name = "condition"];</code>
     */
    private $condition;
    /**
     * Generated from protobuf field <code>map<uint32, .com.fatehan.notifies.UserDeviceAlert.ConditionList> timing = 14 [json_name = "timing"];</code>
     */
    private $timing;
    /**
     * Generated from protobuf field <code>bool status = 7 [json_name = "status"];</code>
     */
    protected $status = false;
    /**
     * Generated from protobuf field <code>string format = 8 [json_name = "format"];</code>
     */
    protected $format = '';
    /**
     * Generated from protobuf field <code>.com.fatehan.packets.Alert alert = 9 [json_name = "alert"];</code>
     */
    protected $alert = 0;
    /**
     * Generated from protobuf field <code>optional string unit = 10 [json_name = "unit"];</code>
     */
    protected $unit = null;
    /**
     * Generated from protobuf field <code>optional string object_type = 12 [json_name = "object_type"];</code>
     */
    protected $object_type = null;
    /**
     * Generated from protobuf field <code>optional uint64 object_id = 13 [json_name = "object_id"];</code>
     */
    protected $object_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int|string $user_id
     *     @type int|string $device_id
     *     @type int|string $organization_id
     *     @type int|string $alert_id
     *     @type array|\Google\Protobuf\Internal\MapField $condition
     *     @type array|\Google\Protobuf\Internal\MapField $timing
     *     @type bool $status
     *     @type string $format
     *     @type int $alert
     *     @type string $unit
     *     @type string $object_type
     *     @type int|string $object_id
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Notify\MetaData\Notify::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1 [json_name = "id"];</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1 [json_name = "id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 user_id = 2 [json_name = "user_id"];</code>
     * @return int|string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>uint64 user_id = 2 [json_name = "user_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkUint64($var);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 device_id = 4 [json_name = "device_id"];</code>
     * @return int|string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Generated from protobuf field <code>uint64 device_id = 4 [json_name = "device_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkUint64($var);
        $this->device_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 organization_id = 11 [json_name = "organization_id"];</code>
     * @return int|string
     */
    public function getOrganizationId()
    {
        return $this->organization_id;
    }

    /**
     * Generated from protobuf field <code>uint64 organization_id = 11 [json_name = "organization_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrganizationId($var)
    {
        GPBUtil::checkUint64($var);
        $this->organization_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 alert_id = 5 [json_name = "alert_id"];</code>
     * @return int|string
     */
    public function getAlertId()
    {
        return $this->alert_id;
    }

    /**
     * Generated from protobuf field <code>uint64 alert_id = 5 [json_name = "alert_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setAlertId($var)
    {
        GPBUtil::checkUint64($var);
        $this->alert_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<uint32, .com.fatehan.notifies.UserDeviceAlert.ConditionList> condition = 6 [json_name = "condition"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCondition()
    {
        return $this->condition;
    }

    /**
     * Generated from protobuf field <code>map<uint32, .com.fatehan.notifies.UserDeviceAlert.ConditionList> condition = 6 [json_name = "condition"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCondition($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::UINT32, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fatehan\Notify\UserDeviceAlert\ConditionList::class);
        $this->condition = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<uint32, .com.fatehan.notifies.UserDeviceAlert.ConditionList> timing = 14 [json_name = "timing"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getTiming()
    {
        return $this->timing;
    }

    /**
     * Generated from protobuf field <code>map<uint32, .com.fatehan.notifies.UserDeviceAlert.ConditionList> timing = 14 [json_name = "timing"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setTiming($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::UINT32, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fatehan\Notify\UserDeviceAlert\ConditionList::class);
        $this->timing = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool status = 7 [json_name = "status"];</code>
     * @return bool
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>bool status = 7 [json_name = "status"];</code>
     * @param bool $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string format = 8 [json_name = "format"];</code>
     * @return string
     */
    public function getFormat()
    {
        return $this->format;
    }

    /**
     * Generated from protobuf field <code>string format = 8 [json_name = "format"];</code>
     * @param string $var
     * @return $this
     */
    public function setFormat($var)
    {
        GPBUtil::checkString($var, True);
        $this->format = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.packets.Alert alert = 9 [json_name = "alert"];</code>
     * @return int
     */
    public function getAlert()
    {
        return $this->alert;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.packets.Alert alert = 9 [json_name = "alert"];</code>
     * @param int $var
     * @return $this
     */
    public function setAlert($var)
    {
        GPBUtil::checkEnum($var, \Fatehan\Packet\DataModel\Alert::class);
        $this->alert = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string unit = 10 [json_name = "unit"];</code>
     * @return string
     */
    public function getUnit()
    {
        return isset($this->unit) ? $this->unit : '';
    }

    public function hasUnit()
    {
        return isset($this->unit);
    }

    public function clearUnit()
    {
        unset($this->unit);
    }

    /**
     * Generated from protobuf field <code>optional string unit = 10 [json_name = "unit"];</code>
     * @param string $var
     * @return $this
     */
    public function setUnit($var)
    {
        GPBUtil::checkString($var, True);
        $this->unit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string object_type = 12 [json_name = "object_type"];</code>
     * @return string
     */
    public function getObjectType()
    {
        return isset($this->object_type) ? $this->object_type : '';
    }

    public function hasObjectType()
    {
        return isset($this->object_type);
    }

    public function clearObjectType()
    {
        unset($this->object_type);
    }

    /**
     * Generated from protobuf field <code>optional string object_type = 12 [json_name = "object_type"];</code>
     * @param string $var
     * @return $this
     */
    public function setObjectType($var)
    {
        GPBUtil::checkString($var, True);
        $this->object_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint64 object_id = 13 [json_name = "object_id"];</code>
     * @return int|string
     */
    public function getObjectId()
    {
        return isset($this->object_id) ? $this->object_id : 0;
    }

    public function hasObjectId()
    {
        return isset($this->object_id);
    }

    public function clearObjectId()
    {
        unset($this->object_id);
    }

    /**
     * Generated from protobuf field <code>optional uint64 object_id = 13 [json_name = "object_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setObjectId($var)
    {
        GPBUtil::checkUint64($var);
        $this->object_id = $var;

        return $this;
    }

}

