<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packets/dataModel.proto

namespace Fatehan\Packet\DataModel\OdysseyDevice;

use UnexpectedValueException;

/**
 * Protobuf type <code>com.fatehan.packets.OdysseyDevice.ObjectType</code>
 */
class ObjectType
{
    /**
     * Generated from protobuf enum <code>CAR = 0;</code>
     */
    const CAR = 0;
    /**
     * Generated from protobuf enum <code>PERSON = 1;</code>
     */
    const PERSON = 1;

    private static $valueToName = [
        self::CAR => 'CAR',
        self::PERSON => 'PERSON',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ObjectType::class, \Fatehan\Packet\DataModel\OdysseyDevice_ObjectType::class);

