<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: devices/devices.proto

namespace Fatehan\Device;

if (false) {
    /**
     * This class is deprecated. Use Fatehan\Device\DeviceIcon\Image instead.
     * @deprecated
     */
    class DeviceIcon_Image {}
}
class_exists(DeviceIcon\Image::class);
@trigger_error('Fatehan\Device\DeviceIcon_Image is deprecated and will be removed in the next major release. Use Fatehan\Device\DeviceIcon\Image instead', E_USER_DEPRECATED);

