<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reports/report.proto

namespace Fatehan\Report\AreaSummaryReviewRequest;

use UnexpectedValueException;

/**
 * Protobuf type <code>com.fatehan.reports.AreaSummaryReviewRequest.ScopeEnum</code>
 */
class ScopeEnum
{
    /**
     * Generated from protobuf enum <code>INSIDE_ONLY = 0;</code>
     */
    const INSIDE_ONLY = 0;
    /**
     * Generated from protobuf enum <code>OUTSIDE_ONLY = 1;</code>
     */
    const OUTSIDE_ONLY = 1;
    /**
     * Generated from protobuf enum <code>BOTH_SIDE = 2;</code>
     */
    const BOTH_SIDE = 2;

    private static $valueToName = [
        self::INSIDE_ONLY => 'INSIDE_ONLY',
        self::OUTSIDE_ONLY => 'OUTSIDE_ONLY',
        self::BOTH_SIDE => 'BOTH_SIDE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

