<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: activities/camera.proto

namespace Fatehan\Activities\Camera;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.activities.CameraEvent</code>
 */
class CameraEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 device_id = 1 [json_name = "device_id"];</code>
     */
    protected $device_id = 0;
    /**
     * Generated from protobuf field <code>uint32 serial_number = 2 [json_name = "serial_number"];</code>
     */
    protected $serial_number = 0;
    protected $event;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $device_id
     *     @type int $serial_number
     *     @type \Fatehan\Activities\Camera\CameraEvent\Started $started
     *     @type \Fatehan\Activities\Camera\CameraEvent\Publish $publish
     *     @type \Fatehan\Activities\Camera\CameraEvent\PublishDone $publish_done
     *     @type \Fatehan\Activities\Camera\CameraEvent\Record $record
     *     @type \Fatehan\Activities\Camera\CameraEvent\IdleTimeout $idle_timeout
     *     @type \Fatehan\Activities\Camera\CameraEvent\ReceiveTimeout $receive_timeout
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Activities\Camera\MetaData\Camera::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 device_id = 1 [json_name = "device_id"];</code>
     * @return int|string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Generated from protobuf field <code>uint64 device_id = 1 [json_name = "device_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkUint64($var);
        $this->device_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 serial_number = 2 [json_name = "serial_number"];</code>
     * @return int
     */
    public function getSerialNumber()
    {
        return $this->serial_number;
    }

    /**
     * Generated from protobuf field <code>uint32 serial_number = 2 [json_name = "serial_number"];</code>
     * @param int $var
     * @return $this
     */
    public function setSerialNumber($var)
    {
        GPBUtil::checkUint32($var);
        $this->serial_number = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.activities.CameraEvent.Started started = 21 [json_name = "started"];</code>
     * @return \Fatehan\Activities\Camera\CameraEvent\Started|null
     */
    public function getStarted()
    {
        return $this->readOneof(21);
    }

    public function hasStarted()
    {
        return $this->hasOneof(21);
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.activities.CameraEvent.Started started = 21 [json_name = "started"];</code>
     * @param \Fatehan\Activities\Camera\CameraEvent\Started $var
     * @return $this
     */
    public function setStarted($var)
    {
        GPBUtil::checkMessage($var, \Fatehan\Activities\Camera\CameraEvent\Started::class);
        $this->writeOneof(21, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.activities.CameraEvent.Publish publish = 22 [json_name = "publish"];</code>
     * @return \Fatehan\Activities\Camera\CameraEvent\Publish|null
     */
    public function getPublish()
    {
        return $this->readOneof(22);
    }

    public function hasPublish()
    {
        return $this->hasOneof(22);
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.activities.CameraEvent.Publish publish = 22 [json_name = "publish"];</code>
     * @param \Fatehan\Activities\Camera\CameraEvent\Publish $var
     * @return $this
     */
    public function setPublish($var)
    {
        GPBUtil::checkMessage($var, \Fatehan\Activities\Camera\CameraEvent\Publish::class);
        $this->writeOneof(22, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.activities.CameraEvent.PublishDone publish_done = 23 [json_name = "publish_done"];</code>
     * @return \Fatehan\Activities\Camera\CameraEvent\PublishDone|null
     */
    public function getPublishDone()
    {
        return $this->readOneof(23);
    }

    public function hasPublishDone()
    {
        return $this->hasOneof(23);
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.activities.CameraEvent.PublishDone publish_done = 23 [json_name = "publish_done"];</code>
     * @param \Fatehan\Activities\Camera\CameraEvent\PublishDone $var
     * @return $this
     */
    public function setPublishDone($var)
    {
        GPBUtil::checkMessage($var, \Fatehan\Activities\Camera\CameraEvent\PublishDone::class);
        $this->writeOneof(23, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.activities.CameraEvent.Record record = 24 [json_name = "record"];</code>
     * @return \Fatehan\Activities\Camera\CameraEvent\Record|null
     */
    public function getRecord()
    {
        return $this->readOneof(24);
    }

    public function hasRecord()
    {
        return $this->hasOneof(24);
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.activities.CameraEvent.Record record = 24 [json_name = "record"];</code>
     * @param \Fatehan\Activities\Camera\CameraEvent\Record $var
     * @return $this
     */
    public function setRecord($var)
    {
        GPBUtil::checkMessage($var, \Fatehan\Activities\Camera\CameraEvent\Record::class);
        $this->writeOneof(24, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.activities.CameraEvent.IdleTimeout idle_timeout = 25 [json_name = "idle_timeout"];</code>
     * @return \Fatehan\Activities\Camera\CameraEvent\IdleTimeout|null
     */
    public function getIdleTimeout()
    {
        return $this->readOneof(25);
    }

    public function hasIdleTimeout()
    {
        return $this->hasOneof(25);
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.activities.CameraEvent.IdleTimeout idle_timeout = 25 [json_name = "idle_timeout"];</code>
     * @param \Fatehan\Activities\Camera\CameraEvent\IdleTimeout $var
     * @return $this
     */
    public function setIdleTimeout($var)
    {
        GPBUtil::checkMessage($var, \Fatehan\Activities\Camera\CameraEvent\IdleTimeout::class);
        $this->writeOneof(25, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.activities.CameraEvent.ReceiveTimeout receive_timeout = 26 [json_name = "receive_timeout"];</code>
     * @return \Fatehan\Activities\Camera\CameraEvent\ReceiveTimeout|null
     */
    public function getReceiveTimeout()
    {
        return $this->readOneof(26);
    }

    public function hasReceiveTimeout()
    {
        return $this->hasOneof(26);
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.activities.CameraEvent.ReceiveTimeout receive_timeout = 26 [json_name = "receive_timeout"];</code>
     * @param \Fatehan\Activities\Camera\CameraEvent\ReceiveTimeout $var
     * @return $this
     */
    public function setReceiveTimeout($var)
    {
        GPBUtil::checkMessage($var, \Fatehan\Activities\Camera\CameraEvent\ReceiveTimeout::class);
        $this->writeOneof(26, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getEvent()
    {
        return $this->whichOneof("event");
    }

}

