<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: packets/dataModel.proto

namespace Fatehan\Packet\DataModel\Packet;

use UnexpectedValueException;

/**
 * Protobuf type <code>com.fatehan.packets.Packet.AnswerType</code>
 */
class AnswerType
{
    /**
     * Generated from protobuf enum <code>BYTE = 0;</code>
     */
    const BYTE = 0;
    /**
     * Generated from protobuf enum <code>STRING = 1;</code>
     */
    const STRING = 1;
    /**
     * Generated from protobuf enum <code>INT = 2;</code>
     */
    const INT = 2;
    /**
     * Generated from protobuf enum <code>TT10780X0001 = 3;</code>
     */
    const TT10780X0001 = 3;
    /**
     * Generated from protobuf enum <code>CONCOX_LIKE_R31 = 4;</code>
     */
    const CONCOX_LIKE_R31 = 4;

    private static $valueToName = [
        self::BYTE => 'BYTE',
        self::STRING => 'STRING',
        self::INT => 'INT',
        self::TT10780X0001 => 'TT10780X0001',
        self::CONCOX_LIKE_R31 => 'CONCOX_LIKE_R31',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

