<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: packets/dataModel.proto

namespace Fatehan\Packet\DataModel\Packet;

use UnexpectedValueException;

/**
 * Deprecated: Use custom oneof instead
 *
 * Protobuf type <code>com.fatehan.packets.Packet.CustomPacketType</code>
 */
class CustomPacketType
{
    /**
     * Deprecated: Use custom oneof instead
     *
     * Generated from protobuf enum <code>CUSTOM_PACKET_TYPE_UNSPECIFIED = 0;</code>
     */
    const CUSTOM_PACKET_TYPE_UNSPECIFIED = 0;
    /**
     * Deprecated: Use custom oneof instead
     *
     * Generated from protobuf enum <code>MULTIMEDIA_EVENT_INFORMATION_UPLOADING = 1;</code>
     */
    const MULTIMEDIA_EVENT_INFORMATION_UPLOADING = 1;
    /**
     * Deprecated: Use custom oneof instead
     *
     * Generated from protobuf enum <code>CONCOX_LBS_INFORMATION = 7;</code>
     */
    const CONCOX_LBS_INFORMATION = 7;
    /**
     * Deprecated: Use custom oneof instead
     *
     * Generated from protobuf enum <code>CONCOX_IMSI_NUMBER = 8;</code>
     */
    const CONCOX_IMSI_NUMBER = 8;
    /**
     * Deprecated: Use custom oneof instead
     *
     * Generated from protobuf enum <code>CONCOX_ICCID_NUMBER = 9;</code>
     */
    const CONCOX_ICCID_NUMBER = 9;
    /**
     * Deprecated: Use custom oneof instead
     *
     * Generated from protobuf enum <code>CONCOX_RECORDING_PROTOCOL_PACKAGE0X8D = 10;</code>
     */
    const CONCOX_RECORDING_PROTOCOL_PACKAGE0X8D = 10;
    /**
     * Deprecated: Use custom oneof instead
     *
     * Generated from protobuf enum <code>DOLPHIN_BUFFER_PAYLOAD = 12;</code>
     */
    const DOLPHIN_BUFFER_PAYLOAD = 12;
    /**
     * Deprecated: Use custom oneof instead
     *
     * Generated from protobuf enum <code>DOLPHIN_NEW_BUFFER = 13;</code>
     */
    const DOLPHIN_NEW_BUFFER = 13;

    private static $valueToName = [
        self::CUSTOM_PACKET_TYPE_UNSPECIFIED => 'CUSTOM_PACKET_TYPE_UNSPECIFIED',
        self::MULTIMEDIA_EVENT_INFORMATION_UPLOADING => 'MULTIMEDIA_EVENT_INFORMATION_UPLOADING',
        self::CONCOX_LBS_INFORMATION => 'CONCOX_LBS_INFORMATION',
        self::CONCOX_IMSI_NUMBER => 'CONCOX_IMSI_NUMBER',
        self::CONCOX_ICCID_NUMBER => 'CONCOX_ICCID_NUMBER',
        self::CONCOX_RECORDING_PROTOCOL_PACKAGE0X8D => 'CONCOX_RECORDING_PROTOCOL_PACKAGE0X8D',
        self::DOLPHIN_BUFFER_PAYLOAD => 'DOLPHIN_BUFFER_PAYLOAD',
        self::DOLPHIN_NEW_BUFFER => 'DOLPHIN_NEW_BUFFER',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

