<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packets/forge.proto

namespace Fatehan\Packet\Forge;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.fatehan.packets.R31AudioRequest</code>
 */
class R31AudioRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Packet\Forge\MetaData\Forge::initOnce();
        parent::__construct($data);
    }

}

