<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packets/dataModel.proto

namespace Fatehan\Packet\DataModel;

if (false) {
    /**
     * This class is deprecated. Use Fatehan\Packet\DataModel\ADAS\RoadSignType instead.
     * @deprecated
     */
    class ADAS_RoadSignType {}
}
class_exists(ADAS\RoadSignType::class);
@trigger_error('Fatehan\Packet\DataModel\ADAS_RoadSignType is deprecated and will be removed in the next major release. Use Fatehan\Packet\DataModel\ADAS\RoadSignType instead', E_USER_DEPRECATED);

