<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packets/dataModel.proto

namespace Fatehan\Packet\DataModel;

if (false) {
    /**
     * This class is deprecated. Use Fatehan\Packet\DataModel\ADAS\DeviationType instead.
     * @deprecated
     */
    class ADAS_DeviationType {}
}
class_exists(ADAS\DeviationType::class);
@trigger_error('Fatehan\Packet\DataModel\ADAS_DeviationType is deprecated and will be removed in the next major release. Use Fatehan\Packet\DataModel\ADAS\DeviationType instead', E_USER_DEPRECATED);

