<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packets/dataModel.proto

namespace Fatehan\Packet\DataModel;

if (false) {
    /**
     * This class is deprecated. Use Fatehan\Packet\DataModel\CanAdaptersElements\Cisf instead.
     * @deprecated
     */
    class CanAdaptersElements_Cisf {}
}
class_exists(CanAdaptersElements\Cisf::class);
@trigger_error('Fatehan\Packet\DataModel\CanAdaptersElements_Cisf is deprecated and will be removed in the next major release. Use Fatehan\Packet\DataModel\CanAdaptersElements\Cisf instead', E_USER_DEPRECATED);

