<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: packets/dataModel.proto

namespace Fatehan\Packet\DataModel;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.packets.Data</code>
 */
class Data extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 device_id = 1 [json_name = "device_id"];</code>
     */
    protected $device_id = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp gps_time = 2 [json_name = "gps_time"];</code>
     */
    protected $gps_time = null;
    /**
     * Generated from protobuf field <code>float latitude = 3 [json_name = "latitude"];</code>
     */
    protected $latitude = 0.0;
    /**
     * Generated from protobuf field <code>float longitude = 4 [json_name = "longitude"];</code>
     */
    protected $longitude = 0.0;
    /**
     * Generated from protobuf field <code>uint32 altitude = 5 [json_name = "altitude"];</code>
     */
    protected $altitude = 0;
    /**
     * Generated from protobuf field <code>uint32 angle = 6 [json_name = "angle"];</code>
     */
    protected $angle = 0;
    /**
     * Generated from protobuf field <code>uint32 speed = 7 [json_name = "speed"];</code>
     */
    protected $speed = 0;
    /**
     * Generated from protobuf field <code>optional uint32 satellite = 8 [json_name = "satellite"];</code>
     */
    protected $satellite = null;
    /**
     * Generated from protobuf field <code>optional bool ignition = 9 [json_name = "ignition"];</code>
     */
    protected $ignition = null;
    /**
     * Generated from protobuf field <code>optional uint64 mileage = 10 [json_name = "mileage"];</code>
     */
    protected $mileage = null;
    /**
     * Generated from protobuf field <code>optional .com.fatehan.packets.Compact compact = 11 [json_name = "compact"];</code>
     */
    protected $compact = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $device_id
     *     @type \Google\Protobuf\Timestamp $gps_time
     *     @type float $latitude
     *     @type float $longitude
     *     @type int $altitude
     *     @type int $angle
     *     @type int $speed
     *     @type int $satellite
     *     @type bool $ignition
     *     @type int|string $mileage
     *     @type \Fatehan\Packet\DataModel\Compact $compact
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Packet\DataModel\MetaData\DataModel::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 device_id = 1 [json_name = "device_id"];</code>
     * @return int|string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Generated from protobuf field <code>uint64 device_id = 1 [json_name = "device_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkUint64($var);
        $this->device_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp gps_time = 2 [json_name = "gps_time"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getGpsTime()
    {
        return $this->gps_time;
    }

    public function hasGpsTime()
    {
        return isset($this->gps_time);
    }

    public function clearGpsTime()
    {
        unset($this->gps_time);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp gps_time = 2 [json_name = "gps_time"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setGpsTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->gps_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float latitude = 3 [json_name = "latitude"];</code>
     * @return float
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * Generated from protobuf field <code>float latitude = 3 [json_name = "latitude"];</code>
     * @param float $var
     * @return $this
     */
    public function setLatitude($var)
    {
        GPBUtil::checkFloat($var);
        $this->latitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float longitude = 4 [json_name = "longitude"];</code>
     * @return float
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * Generated from protobuf field <code>float longitude = 4 [json_name = "longitude"];</code>
     * @param float $var
     * @return $this
     */
    public function setLongitude($var)
    {
        GPBUtil::checkFloat($var);
        $this->longitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 altitude = 5 [json_name = "altitude"];</code>
     * @return int
     */
    public function getAltitude()
    {
        return $this->altitude;
    }

    /**
     * Generated from protobuf field <code>uint32 altitude = 5 [json_name = "altitude"];</code>
     * @param int $var
     * @return $this
     */
    public function setAltitude($var)
    {
        GPBUtil::checkUint32($var);
        $this->altitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 angle = 6 [json_name = "angle"];</code>
     * @return int
     */
    public function getAngle()
    {
        return $this->angle;
    }

    /**
     * Generated from protobuf field <code>uint32 angle = 6 [json_name = "angle"];</code>
     * @param int $var
     * @return $this
     */
    public function setAngle($var)
    {
        GPBUtil::checkUint32($var);
        $this->angle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 speed = 7 [json_name = "speed"];</code>
     * @return int
     */
    public function getSpeed()
    {
        return $this->speed;
    }

    /**
     * Generated from protobuf field <code>uint32 speed = 7 [json_name = "speed"];</code>
     * @param int $var
     * @return $this
     */
    public function setSpeed($var)
    {
        GPBUtil::checkUint32($var);
        $this->speed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 satellite = 8 [json_name = "satellite"];</code>
     * @return int
     */
    public function getSatellite()
    {
        return isset($this->satellite) ? $this->satellite : 0;
    }

    public function hasSatellite()
    {
        return isset($this->satellite);
    }

    public function clearSatellite()
    {
        unset($this->satellite);
    }

    /**
     * Generated from protobuf field <code>optional uint32 satellite = 8 [json_name = "satellite"];</code>
     * @param int $var
     * @return $this
     */
    public function setSatellite($var)
    {
        GPBUtil::checkUint32($var);
        $this->satellite = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool ignition = 9 [json_name = "ignition"];</code>
     * @return bool
     */
    public function getIgnition()
    {
        return isset($this->ignition) ? $this->ignition : false;
    }

    public function hasIgnition()
    {
        return isset($this->ignition);
    }

    public function clearIgnition()
    {
        unset($this->ignition);
    }

    /**
     * Generated from protobuf field <code>optional bool ignition = 9 [json_name = "ignition"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIgnition($var)
    {
        GPBUtil::checkBool($var);
        $this->ignition = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint64 mileage = 10 [json_name = "mileage"];</code>
     * @return int|string
     */
    public function getMileage()
    {
        return isset($this->mileage) ? $this->mileage : 0;
    }

    public function hasMileage()
    {
        return isset($this->mileage);
    }

    public function clearMileage()
    {
        unset($this->mileage);
    }

    /**
     * Generated from protobuf field <code>optional uint64 mileage = 10 [json_name = "mileage"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setMileage($var)
    {
        GPBUtil::checkUint64($var);
        $this->mileage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .com.fatehan.packets.Compact compact = 11 [json_name = "compact"];</code>
     * @return \Fatehan\Packet\DataModel\Compact|null
     */
    public function getCompact()
    {
        return $this->compact;
    }

    public function hasCompact()
    {
        return isset($this->compact);
    }

    public function clearCompact()
    {
        unset($this->compact);
    }

    /**
     * Generated from protobuf field <code>optional .com.fatehan.packets.Compact compact = 11 [json_name = "compact"];</code>
     * @param \Fatehan\Packet\DataModel\Compact $var
     * @return $this
     */
    public function setCompact($var)
    {
        GPBUtil::checkMessage($var, \Fatehan\Packet\DataModel\Compact::class);
        $this->compact = $var;

        return $this;
    }

}

