<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: packets/dataModel.proto

namespace Fatehan\Packet\DataModel;

use UnexpectedValueException;

/**
 * Protobuf type <code>com.fatehan.packets.FileFormat</code>
 */
class FileFormat
{
    /**
     * Generated from protobuf enum <code>FILE_FORMAT_UNSPECIFIED = 0;</code>
     */
    const FILE_FORMAT_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>JPEG = 1;</code>
     */
    const JPEG = 1;
    /**
     * Generated from protobuf enum <code>PNG = 2;</code>
     */
    const PNG = 2;
    /**
     * Generated from protobuf enum <code>GIF = 3;</code>
     */
    const GIF = 3;
    /**
     * Generated from protobuf enum <code>BMP = 4;</code>
     */
    const BMP = 4;
    /**
     * Generated from protobuf enum <code>TIFF = 5;</code>
     */
    const TIFF = 5;
    /**
     * Generated from protobuf enum <code>AVI = 6;</code>
     */
    const AVI = 6;
    /**
     * Generated from protobuf enum <code>P4 = 7;</code>
     */
    const P4 = 7;
    /**
     * Generated from protobuf enum <code>WAV = 8;</code>
     */
    const WAV = 8;
    /**
     * Generated from protobuf enum <code>P3 = 9;</code>
     */
    const P3 = 9;
    /**
     * Generated from protobuf enum <code>TXT = 10;</code>
     */
    const TXT = 10;
    /**
     * Generated from protobuf enum <code>JPG = 11;</code>
     */
    const JPG = 11;
    /**
     * Generated from protobuf enum <code>BIN = 12;</code>
     */
    const BIN = 12;
    /**
     * Generated from protobuf enum <code>OTHER_FORMAT = 13;</code>
     */
    const OTHER_FORMAT = 13;

    private static $valueToName = [
        self::FILE_FORMAT_UNSPECIFIED => 'FILE_FORMAT_UNSPECIFIED',
        self::JPEG => 'JPEG',
        self::PNG => 'PNG',
        self::GIF => 'GIF',
        self::BMP => 'BMP',
        self::TIFF => 'TIFF',
        self::AVI => 'AVI',
        self::P4 => 'P4',
        self::WAV => 'WAV',
        self::P3 => 'P3',
        self::TXT => 'TXT',
        self::JPG => 'JPG',
        self::BIN => 'BIN',
        self::OTHER_FORMAT => 'OTHER_FORMAT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

