<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: packets/dataModel.proto

namespace Fatehan\Packet\DataModel;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.packets.FmsElement</code>
 */
class FmsElement extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional bool brake_switch = 1 [json_name = "brake_switch"];</code>
     */
    protected $brake_switch = null;
    /**
     * Generated from protobuf field <code>optional uint32 wheel_based_speed = 2 [json_name = "wheel_based_speed"];</code>
     */
    protected $wheel_based_speed = null;
    /**
     * Generated from protobuf field <code>optional bool cruise_control_active = 3 [json_name = "cruise_control_active"];</code>
     */
    protected $cruise_control_active = null;
    /**
     * Generated from protobuf field <code>optional bool clutch_switch = 4 [json_name = "clutch_switch"];</code>
     */
    protected $clutch_switch = null;
    /**
     * Generated from protobuf field <code>optional bool pto_state = 5 [json_name = "pto_state"];</code>
     */
    protected $pto_state = null;
    /**
     * Generated from protobuf field <code>optional uint32 acceleration_pedal_position = 6 [json_name = "acceleration_pedal_position"];</code>
     */
    protected $acceleration_pedal_position = null;
    /**
     * Generated from protobuf field <code>optional uint32 engine_current_load = 7 [json_name = "engine_current_load"];</code>
     */
    protected $engine_current_load = null;
    /**
     * Generated from protobuf field <code>optional uint32 engine_total_fuel_used = 8 [json_name = "engine_total_fuel_used"];</code>
     */
    protected $engine_total_fuel_used = null;
    /**
     * Generated from protobuf field <code>optional uint32 fuel_level_percentage = 9 [json_name = "fuel_level_percentage"];</code>
     */
    protected $fuel_level_percentage = null;
    /**
     * Generated from protobuf field <code>optional uint32 engine_speed = 10 [json_name = "engine_speed"];</code>
     */
    protected $engine_speed = null;
    /**
     * Generated from protobuf field <code>optional uint32 axle_weight1 = 11 [json_name = "axle_weight_1"];</code>
     */
    protected $axle_weight1 = null;
    /**
     * Generated from protobuf field <code>optional uint32 axle_weight2 = 12 [json_name = "axle_weight_2"];</code>
     */
    protected $axle_weight2 = null;
    /**
     * Generated from protobuf field <code>optional uint32 axle_weight3 = 13 [json_name = "axle_weight_3"];</code>
     */
    protected $axle_weight3 = null;
    /**
     * Generated from protobuf field <code>optional uint32 axle_weight4 = 14 [json_name = "axle_weight_4"];</code>
     */
    protected $axle_weight4 = null;
    /**
     * Generated from protobuf field <code>optional uint32 axle_weight5 = 15 [json_name = "axle_weight_5"];</code>
     */
    protected $axle_weight5 = null;
    /**
     * Generated from protobuf field <code>optional uint32 axle_weight6 = 16 [json_name = "axle_weight_6"];</code>
     */
    protected $axle_weight6 = null;
    /**
     * Generated from protobuf field <code>optional uint32 axle_weight7 = 17 [json_name = "axle_weight_7"];</code>
     */
    protected $axle_weight7 = null;
    /**
     * Generated from protobuf field <code>optional uint32 axle_weight8 = 18 [json_name = "axle_weight_8"];</code>
     */
    protected $axle_weight8 = null;
    /**
     * Generated from protobuf field <code>optional uint32 axle_weight9 = 19 [json_name = "axle_weight_9"];</code>
     */
    protected $axle_weight9 = null;
    /**
     * Generated from protobuf field <code>optional uint32 axle_weight10 = 20 [json_name = "axle_weight_10"];</code>
     */
    protected $axle_weight10 = null;
    /**
     * Generated from protobuf field <code>optional uint32 axle_weight11 = 21 [json_name = "axle_weight_11"];</code>
     */
    protected $axle_weight11 = null;
    /**
     * Generated from protobuf field <code>optional uint32 axle_weight12 = 22 [json_name = "axle_weight_12"];</code>
     */
    protected $axle_weight12 = null;
    /**
     * Generated from protobuf field <code>optional uint32 axle_weight13 = 23 [json_name = "axle_weight_13"];</code>
     */
    protected $axle_weight13 = null;
    /**
     * Generated from protobuf field <code>optional uint32 axle_weight14 = 24 [json_name = "axle_weight_14"];</code>
     */
    protected $axle_weight14 = null;
    /**
     * Generated from protobuf field <code>optional uint32 axle_weight15 = 25 [json_name = "axle_weight_15"];</code>
     */
    protected $axle_weight15 = null;
    /**
     * Generated from protobuf field <code>optional uint32 engine_total_hours_of_operation = 26 [json_name = "engine_total_hours_of_operation"];</code>
     */
    protected $engine_total_hours_of_operation = null;
    /**
     * Generated from protobuf field <code>optional uint32 software_version_supported = 27 [json_name = "software_version_supported"];</code>
     */
    protected $software_version_supported = null;
    /**
     * Generated from protobuf field <code>optional uint32 diagnostic_supported = 28 [json_name = "diagnostic_supported"];</code>
     */
    protected $diagnostic_supported = null;
    /**
     * Generated from protobuf field <code>optional uint32 requests_supported = 29 [json_name = "requests_supported"];</code>
     */
    protected $requests_supported = null;
    /**
     * Generated from protobuf field <code>optional sint32 server_distance = 30 [json_name = "server_distance"];</code>
     */
    protected $server_distance = null;
    /**
     * Generated from protobuf field <code>optional uint32 direction_indication = 31 [json_name = "direction_indication"];</code>
     */
    protected $direction_indication = null;
    /**
     * Generated from protobuf field <code>optional uint32 tachograph_performance = 32 [json_name = "tachograph_performance"];</code>
     */
    protected $tachograph_performance = null;
    /**
     * Generated from protobuf field <code>optional uint32 handling_info = 33 [json_name = "handling_info"];</code>
     */
    protected $handling_info = null;
    /**
     * Generated from protobuf field <code>optional uint32 system_event = 34 [json_name = "system_event"];</code>
     */
    protected $system_event = null;
    /**
     * Generated from protobuf field <code>optional sint32 engine_coolant_temperature = 35 [json_name = "engine_coolant_temperature"];</code>
     */
    protected $engine_coolant_temperature = null;
    /**
     * Generated from protobuf field <code>optional sint32 ambient_air_temperature = 36 [json_name = "ambient_air_temperature"];</code>
     */
    protected $ambient_air_temperature = null;
    /**
     * Generated from protobuf field <code>optional uint32 fuel_rate = 37 [json_name = "fuel_rate"];</code>
     */
    protected $fuel_rate = null;
    /**
     * Generated from protobuf field <code>optional uint32 instantaneous_fuel_economy = 38 [json_name = "instantaneous_fuel_economy"];</code>
     */
    protected $instantaneous_fuel_economy = null;
    /**
     * Generated from protobuf field <code>optional uint32 pto_drive_engagement = 39 [json_name = "pto_drive_engagement"];</code>
     */
    protected $pto_drive_engagement = null;
    /**
     * Generated from protobuf field <code>optional uint32 high_resolution_engine_total_fuel_used = 40 [json_name = "high_resolution_engine_total_fuel_used"];</code>
     */
    protected $high_resolution_engine_total_fuel_used = null;
    /**
     * Generated from protobuf field <code>optional uint32 gross_combination_vehicle_weight = 41 [json_name = "gross_combination_vehicle_weight"];</code>
     */
    protected $gross_combination_vehicle_weight = null;
    /**
     * Generated from protobuf field <code>optional uint32 ad_blue_status = 42 [json_name = "ad_blue_status"];</code>
     */
    protected $ad_blue_status = null;
    /**
     * Generated from protobuf field <code>optional uint32 brake_pedal_position = 43 [json_name = "brake_pedal_position"];</code>
     */
    protected $brake_pedal_position = null;
    /**
     * Generated from protobuf field <code>optional uint32 fuel_level2 = 44 [json_name = "fuel_level_2"];</code>
     */
    protected $fuel_level2 = null;
    /**
     * Generated from protobuf field <code>optional uint32 mil_indicator = 45 [json_name = "mil_indicator"];</code>
     */
    protected $mil_indicator = null;
    /**
     * Generated from protobuf field <code>optional bytes tell_tale0 = 46 [json_name = "tell_tale_0"];</code>
     */
    protected $tell_tale0 = null;
    /**
     * Generated from protobuf field <code>optional bytes tell_tale1 = 47 [json_name = "tell_tale_1"];</code>
     */
    protected $tell_tale1 = null;
    /**
     * Generated from protobuf field <code>optional bytes tell_tale2 = 48 [json_name = "tell_tale_2"];</code>
     */
    protected $tell_tale2 = null;
    /**
     * Generated from protobuf field <code>optional bytes tell_tale3 = 49 [json_name = "tell_tale_3"];</code>
     */
    protected $tell_tale3 = null;
    /**
     * Generated from protobuf field <code>optional bytes tell_tale4 = 50 [json_name = "tell_tale_4"];</code>
     */
    protected $tell_tale4 = null;
    /**
     * Generated from protobuf field <code>optional uint32 ad_blue_level = 51 [json_name = "ad_blue_level"];</code>
     */
    protected $ad_blue_level = null;
    /**
     * Generated from protobuf field <code>optional uint32 dtc_dm1 = 52 [json_name = "dtc_dm_1"];</code>
     */
    protected $dtc_dm1 = null;
    /**
     * Generated from protobuf field <code>optional uint32 dtc_time_dm1 = 53 [json_name = "dtc_time_dm_1"];</code>
     */
    protected $dtc_time_dm1 = null;
    /**
     * Generated from protobuf field <code>optional uint32 dtc_dm2 = 54 [json_name = "dtc_dm_2"];</code>
     */
    protected $dtc_dm2 = null;
    /**
     * Generated from protobuf field <code>optional uint32 dtc_time_dm2 = 55 [json_name = "dtc_time_dm_2"];</code>
     */
    protected $dtc_time_dm2 = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $brake_switch
     *     @type int $wheel_based_speed
     *     @type bool $cruise_control_active
     *     @type bool $clutch_switch
     *     @type bool $pto_state
     *     @type int $acceleration_pedal_position
     *     @type int $engine_current_load
     *     @type int $engine_total_fuel_used
     *     @type int $fuel_level_percentage
     *     @type int $engine_speed
     *     @type int $axle_weight1
     *     @type int $axle_weight2
     *     @type int $axle_weight3
     *     @type int $axle_weight4
     *     @type int $axle_weight5
     *     @type int $axle_weight6
     *     @type int $axle_weight7
     *     @type int $axle_weight8
     *     @type int $axle_weight9
     *     @type int $axle_weight10
     *     @type int $axle_weight11
     *     @type int $axle_weight12
     *     @type int $axle_weight13
     *     @type int $axle_weight14
     *     @type int $axle_weight15
     *     @type int $engine_total_hours_of_operation
     *     @type int $software_version_supported
     *     @type int $diagnostic_supported
     *     @type int $requests_supported
     *     @type int $server_distance
     *     @type int $direction_indication
     *     @type int $tachograph_performance
     *     @type int $handling_info
     *     @type int $system_event
     *     @type int $engine_coolant_temperature
     *     @type int $ambient_air_temperature
     *     @type int $fuel_rate
     *     @type int $instantaneous_fuel_economy
     *     @type int $pto_drive_engagement
     *     @type int $high_resolution_engine_total_fuel_used
     *     @type int $gross_combination_vehicle_weight
     *     @type int $ad_blue_status
     *     @type int $brake_pedal_position
     *     @type int $fuel_level2
     *     @type int $mil_indicator
     *     @type string $tell_tale0
     *     @type string $tell_tale1
     *     @type string $tell_tale2
     *     @type string $tell_tale3
     *     @type string $tell_tale4
     *     @type int $ad_blue_level
     *     @type int $dtc_dm1
     *     @type int $dtc_time_dm1
     *     @type int $dtc_dm2
     *     @type int $dtc_time_dm2
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Packet\DataModel\MetaData\DataModel::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional bool brake_switch = 1 [json_name = "brake_switch"];</code>
     * @return bool
     */
    public function getBrakeSwitch()
    {
        return isset($this->brake_switch) ? $this->brake_switch : false;
    }

    public function hasBrakeSwitch()
    {
        return isset($this->brake_switch);
    }

    public function clearBrakeSwitch()
    {
        unset($this->brake_switch);
    }

    /**
     * Generated from protobuf field <code>optional bool brake_switch = 1 [json_name = "brake_switch"];</code>
     * @param bool $var
     * @return $this
     */
    public function setBrakeSwitch($var)
    {
        GPBUtil::checkBool($var);
        $this->brake_switch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 wheel_based_speed = 2 [json_name = "wheel_based_speed"];</code>
     * @return int
     */
    public function getWheelBasedSpeed()
    {
        return isset($this->wheel_based_speed) ? $this->wheel_based_speed : 0;
    }

    public function hasWheelBasedSpeed()
    {
        return isset($this->wheel_based_speed);
    }

    public function clearWheelBasedSpeed()
    {
        unset($this->wheel_based_speed);
    }

    /**
     * Generated from protobuf field <code>optional uint32 wheel_based_speed = 2 [json_name = "wheel_based_speed"];</code>
     * @param int $var
     * @return $this
     */
    public function setWheelBasedSpeed($var)
    {
        GPBUtil::checkUint32($var);
        $this->wheel_based_speed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool cruise_control_active = 3 [json_name = "cruise_control_active"];</code>
     * @return bool
     */
    public function getCruiseControlActive()
    {
        return isset($this->cruise_control_active) ? $this->cruise_control_active : false;
    }

    public function hasCruiseControlActive()
    {
        return isset($this->cruise_control_active);
    }

    public function clearCruiseControlActive()
    {
        unset($this->cruise_control_active);
    }

    /**
     * Generated from protobuf field <code>optional bool cruise_control_active = 3 [json_name = "cruise_control_active"];</code>
     * @param bool $var
     * @return $this
     */
    public function setCruiseControlActive($var)
    {
        GPBUtil::checkBool($var);
        $this->cruise_control_active = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool clutch_switch = 4 [json_name = "clutch_switch"];</code>
     * @return bool
     */
    public function getClutchSwitch()
    {
        return isset($this->clutch_switch) ? $this->clutch_switch : false;
    }

    public function hasClutchSwitch()
    {
        return isset($this->clutch_switch);
    }

    public function clearClutchSwitch()
    {
        unset($this->clutch_switch);
    }

    /**
     * Generated from protobuf field <code>optional bool clutch_switch = 4 [json_name = "clutch_switch"];</code>
     * @param bool $var
     * @return $this
     */
    public function setClutchSwitch($var)
    {
        GPBUtil::checkBool($var);
        $this->clutch_switch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool pto_state = 5 [json_name = "pto_state"];</code>
     * @return bool
     */
    public function getPtoState()
    {
        return isset($this->pto_state) ? $this->pto_state : false;
    }

    public function hasPtoState()
    {
        return isset($this->pto_state);
    }

    public function clearPtoState()
    {
        unset($this->pto_state);
    }

    /**
     * Generated from protobuf field <code>optional bool pto_state = 5 [json_name = "pto_state"];</code>
     * @param bool $var
     * @return $this
     */
    public function setPtoState($var)
    {
        GPBUtil::checkBool($var);
        $this->pto_state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 acceleration_pedal_position = 6 [json_name = "acceleration_pedal_position"];</code>
     * @return int
     */
    public function getAccelerationPedalPosition()
    {
        return isset($this->acceleration_pedal_position) ? $this->acceleration_pedal_position : 0;
    }

    public function hasAccelerationPedalPosition()
    {
        return isset($this->acceleration_pedal_position);
    }

    public function clearAccelerationPedalPosition()
    {
        unset($this->acceleration_pedal_position);
    }

    /**
     * Generated from protobuf field <code>optional uint32 acceleration_pedal_position = 6 [json_name = "acceleration_pedal_position"];</code>
     * @param int $var
     * @return $this
     */
    public function setAccelerationPedalPosition($var)
    {
        GPBUtil::checkUint32($var);
        $this->acceleration_pedal_position = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 engine_current_load = 7 [json_name = "engine_current_load"];</code>
     * @return int
     */
    public function getEngineCurrentLoad()
    {
        return isset($this->engine_current_load) ? $this->engine_current_load : 0;
    }

    public function hasEngineCurrentLoad()
    {
        return isset($this->engine_current_load);
    }

    public function clearEngineCurrentLoad()
    {
        unset($this->engine_current_load);
    }

    /**
     * Generated from protobuf field <code>optional uint32 engine_current_load = 7 [json_name = "engine_current_load"];</code>
     * @param int $var
     * @return $this
     */
    public function setEngineCurrentLoad($var)
    {
        GPBUtil::checkUint32($var);
        $this->engine_current_load = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 engine_total_fuel_used = 8 [json_name = "engine_total_fuel_used"];</code>
     * @return int
     */
    public function getEngineTotalFuelUsed()
    {
        return isset($this->engine_total_fuel_used) ? $this->engine_total_fuel_used : 0;
    }

    public function hasEngineTotalFuelUsed()
    {
        return isset($this->engine_total_fuel_used);
    }

    public function clearEngineTotalFuelUsed()
    {
        unset($this->engine_total_fuel_used);
    }

    /**
     * Generated from protobuf field <code>optional uint32 engine_total_fuel_used = 8 [json_name = "engine_total_fuel_used"];</code>
     * @param int $var
     * @return $this
     */
    public function setEngineTotalFuelUsed($var)
    {
        GPBUtil::checkUint32($var);
        $this->engine_total_fuel_used = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 fuel_level_percentage = 9 [json_name = "fuel_level_percentage"];</code>
     * @return int
     */
    public function getFuelLevelPercentage()
    {
        return isset($this->fuel_level_percentage) ? $this->fuel_level_percentage : 0;
    }

    public function hasFuelLevelPercentage()
    {
        return isset($this->fuel_level_percentage);
    }

    public function clearFuelLevelPercentage()
    {
        unset($this->fuel_level_percentage);
    }

    /**
     * Generated from protobuf field <code>optional uint32 fuel_level_percentage = 9 [json_name = "fuel_level_percentage"];</code>
     * @param int $var
     * @return $this
     */
    public function setFuelLevelPercentage($var)
    {
        GPBUtil::checkUint32($var);
        $this->fuel_level_percentage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 engine_speed = 10 [json_name = "engine_speed"];</code>
     * @return int
     */
    public function getEngineSpeed()
    {
        return isset($this->engine_speed) ? $this->engine_speed : 0;
    }

    public function hasEngineSpeed()
    {
        return isset($this->engine_speed);
    }

    public function clearEngineSpeed()
    {
        unset($this->engine_speed);
    }

    /**
     * Generated from protobuf field <code>optional uint32 engine_speed = 10 [json_name = "engine_speed"];</code>
     * @param int $var
     * @return $this
     */
    public function setEngineSpeed($var)
    {
        GPBUtil::checkUint32($var);
        $this->engine_speed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight1 = 11 [json_name = "axle_weight_1"];</code>
     * @return int
     */
    public function getAxleWeight1()
    {
        return isset($this->axle_weight1) ? $this->axle_weight1 : 0;
    }

    public function hasAxleWeight1()
    {
        return isset($this->axle_weight1);
    }

    public function clearAxleWeight1()
    {
        unset($this->axle_weight1);
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight1 = 11 [json_name = "axle_weight_1"];</code>
     * @param int $var
     * @return $this
     */
    public function setAxleWeight1($var)
    {
        GPBUtil::checkUint32($var);
        $this->axle_weight1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight2 = 12 [json_name = "axle_weight_2"];</code>
     * @return int
     */
    public function getAxleWeight2()
    {
        return isset($this->axle_weight2) ? $this->axle_weight2 : 0;
    }

    public function hasAxleWeight2()
    {
        return isset($this->axle_weight2);
    }

    public function clearAxleWeight2()
    {
        unset($this->axle_weight2);
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight2 = 12 [json_name = "axle_weight_2"];</code>
     * @param int $var
     * @return $this
     */
    public function setAxleWeight2($var)
    {
        GPBUtil::checkUint32($var);
        $this->axle_weight2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight3 = 13 [json_name = "axle_weight_3"];</code>
     * @return int
     */
    public function getAxleWeight3()
    {
        return isset($this->axle_weight3) ? $this->axle_weight3 : 0;
    }

    public function hasAxleWeight3()
    {
        return isset($this->axle_weight3);
    }

    public function clearAxleWeight3()
    {
        unset($this->axle_weight3);
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight3 = 13 [json_name = "axle_weight_3"];</code>
     * @param int $var
     * @return $this
     */
    public function setAxleWeight3($var)
    {
        GPBUtil::checkUint32($var);
        $this->axle_weight3 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight4 = 14 [json_name = "axle_weight_4"];</code>
     * @return int
     */
    public function getAxleWeight4()
    {
        return isset($this->axle_weight4) ? $this->axle_weight4 : 0;
    }

    public function hasAxleWeight4()
    {
        return isset($this->axle_weight4);
    }

    public function clearAxleWeight4()
    {
        unset($this->axle_weight4);
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight4 = 14 [json_name = "axle_weight_4"];</code>
     * @param int $var
     * @return $this
     */
    public function setAxleWeight4($var)
    {
        GPBUtil::checkUint32($var);
        $this->axle_weight4 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight5 = 15 [json_name = "axle_weight_5"];</code>
     * @return int
     */
    public function getAxleWeight5()
    {
        return isset($this->axle_weight5) ? $this->axle_weight5 : 0;
    }

    public function hasAxleWeight5()
    {
        return isset($this->axle_weight5);
    }

    public function clearAxleWeight5()
    {
        unset($this->axle_weight5);
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight5 = 15 [json_name = "axle_weight_5"];</code>
     * @param int $var
     * @return $this
     */
    public function setAxleWeight5($var)
    {
        GPBUtil::checkUint32($var);
        $this->axle_weight5 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight6 = 16 [json_name = "axle_weight_6"];</code>
     * @return int
     */
    public function getAxleWeight6()
    {
        return isset($this->axle_weight6) ? $this->axle_weight6 : 0;
    }

    public function hasAxleWeight6()
    {
        return isset($this->axle_weight6);
    }

    public function clearAxleWeight6()
    {
        unset($this->axle_weight6);
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight6 = 16 [json_name = "axle_weight_6"];</code>
     * @param int $var
     * @return $this
     */
    public function setAxleWeight6($var)
    {
        GPBUtil::checkUint32($var);
        $this->axle_weight6 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight7 = 17 [json_name = "axle_weight_7"];</code>
     * @return int
     */
    public function getAxleWeight7()
    {
        return isset($this->axle_weight7) ? $this->axle_weight7 : 0;
    }

    public function hasAxleWeight7()
    {
        return isset($this->axle_weight7);
    }

    public function clearAxleWeight7()
    {
        unset($this->axle_weight7);
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight7 = 17 [json_name = "axle_weight_7"];</code>
     * @param int $var
     * @return $this
     */
    public function setAxleWeight7($var)
    {
        GPBUtil::checkUint32($var);
        $this->axle_weight7 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight8 = 18 [json_name = "axle_weight_8"];</code>
     * @return int
     */
    public function getAxleWeight8()
    {
        return isset($this->axle_weight8) ? $this->axle_weight8 : 0;
    }

    public function hasAxleWeight8()
    {
        return isset($this->axle_weight8);
    }

    public function clearAxleWeight8()
    {
        unset($this->axle_weight8);
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight8 = 18 [json_name = "axle_weight_8"];</code>
     * @param int $var
     * @return $this
     */
    public function setAxleWeight8($var)
    {
        GPBUtil::checkUint32($var);
        $this->axle_weight8 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight9 = 19 [json_name = "axle_weight_9"];</code>
     * @return int
     */
    public function getAxleWeight9()
    {
        return isset($this->axle_weight9) ? $this->axle_weight9 : 0;
    }

    public function hasAxleWeight9()
    {
        return isset($this->axle_weight9);
    }

    public function clearAxleWeight9()
    {
        unset($this->axle_weight9);
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight9 = 19 [json_name = "axle_weight_9"];</code>
     * @param int $var
     * @return $this
     */
    public function setAxleWeight9($var)
    {
        GPBUtil::checkUint32($var);
        $this->axle_weight9 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight10 = 20 [json_name = "axle_weight_10"];</code>
     * @return int
     */
    public function getAxleWeight10()
    {
        return isset($this->axle_weight10) ? $this->axle_weight10 : 0;
    }

    public function hasAxleWeight10()
    {
        return isset($this->axle_weight10);
    }

    public function clearAxleWeight10()
    {
        unset($this->axle_weight10);
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight10 = 20 [json_name = "axle_weight_10"];</code>
     * @param int $var
     * @return $this
     */
    public function setAxleWeight10($var)
    {
        GPBUtil::checkUint32($var);
        $this->axle_weight10 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight11 = 21 [json_name = "axle_weight_11"];</code>
     * @return int
     */
    public function getAxleWeight11()
    {
        return isset($this->axle_weight11) ? $this->axle_weight11 : 0;
    }

    public function hasAxleWeight11()
    {
        return isset($this->axle_weight11);
    }

    public function clearAxleWeight11()
    {
        unset($this->axle_weight11);
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight11 = 21 [json_name = "axle_weight_11"];</code>
     * @param int $var
     * @return $this
     */
    public function setAxleWeight11($var)
    {
        GPBUtil::checkUint32($var);
        $this->axle_weight11 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight12 = 22 [json_name = "axle_weight_12"];</code>
     * @return int
     */
    public function getAxleWeight12()
    {
        return isset($this->axle_weight12) ? $this->axle_weight12 : 0;
    }

    public function hasAxleWeight12()
    {
        return isset($this->axle_weight12);
    }

    public function clearAxleWeight12()
    {
        unset($this->axle_weight12);
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight12 = 22 [json_name = "axle_weight_12"];</code>
     * @param int $var
     * @return $this
     */
    public function setAxleWeight12($var)
    {
        GPBUtil::checkUint32($var);
        $this->axle_weight12 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight13 = 23 [json_name = "axle_weight_13"];</code>
     * @return int
     */
    public function getAxleWeight13()
    {
        return isset($this->axle_weight13) ? $this->axle_weight13 : 0;
    }

    public function hasAxleWeight13()
    {
        return isset($this->axle_weight13);
    }

    public function clearAxleWeight13()
    {
        unset($this->axle_weight13);
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight13 = 23 [json_name = "axle_weight_13"];</code>
     * @param int $var
     * @return $this
     */
    public function setAxleWeight13($var)
    {
        GPBUtil::checkUint32($var);
        $this->axle_weight13 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight14 = 24 [json_name = "axle_weight_14"];</code>
     * @return int
     */
    public function getAxleWeight14()
    {
        return isset($this->axle_weight14) ? $this->axle_weight14 : 0;
    }

    public function hasAxleWeight14()
    {
        return isset($this->axle_weight14);
    }

    public function clearAxleWeight14()
    {
        unset($this->axle_weight14);
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight14 = 24 [json_name = "axle_weight_14"];</code>
     * @param int $var
     * @return $this
     */
    public function setAxleWeight14($var)
    {
        GPBUtil::checkUint32($var);
        $this->axle_weight14 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight15 = 25 [json_name = "axle_weight_15"];</code>
     * @return int
     */
    public function getAxleWeight15()
    {
        return isset($this->axle_weight15) ? $this->axle_weight15 : 0;
    }

    public function hasAxleWeight15()
    {
        return isset($this->axle_weight15);
    }

    public function clearAxleWeight15()
    {
        unset($this->axle_weight15);
    }

    /**
     * Generated from protobuf field <code>optional uint32 axle_weight15 = 25 [json_name = "axle_weight_15"];</code>
     * @param int $var
     * @return $this
     */
    public function setAxleWeight15($var)
    {
        GPBUtil::checkUint32($var);
        $this->axle_weight15 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 engine_total_hours_of_operation = 26 [json_name = "engine_total_hours_of_operation"];</code>
     * @return int
     */
    public function getEngineTotalHoursOfOperation()
    {
        return isset($this->engine_total_hours_of_operation) ? $this->engine_total_hours_of_operation : 0;
    }

    public function hasEngineTotalHoursOfOperation()
    {
        return isset($this->engine_total_hours_of_operation);
    }

    public function clearEngineTotalHoursOfOperation()
    {
        unset($this->engine_total_hours_of_operation);
    }

    /**
     * Generated from protobuf field <code>optional uint32 engine_total_hours_of_operation = 26 [json_name = "engine_total_hours_of_operation"];</code>
     * @param int $var
     * @return $this
     */
    public function setEngineTotalHoursOfOperation($var)
    {
        GPBUtil::checkUint32($var);
        $this->engine_total_hours_of_operation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 software_version_supported = 27 [json_name = "software_version_supported"];</code>
     * @return int
     */
    public function getSoftwareVersionSupported()
    {
        return isset($this->software_version_supported) ? $this->software_version_supported : 0;
    }

    public function hasSoftwareVersionSupported()
    {
        return isset($this->software_version_supported);
    }

    public function clearSoftwareVersionSupported()
    {
        unset($this->software_version_supported);
    }

    /**
     * Generated from protobuf field <code>optional uint32 software_version_supported = 27 [json_name = "software_version_supported"];</code>
     * @param int $var
     * @return $this
     */
    public function setSoftwareVersionSupported($var)
    {
        GPBUtil::checkUint32($var);
        $this->software_version_supported = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 diagnostic_supported = 28 [json_name = "diagnostic_supported"];</code>
     * @return int
     */
    public function getDiagnosticSupported()
    {
        return isset($this->diagnostic_supported) ? $this->diagnostic_supported : 0;
    }

    public function hasDiagnosticSupported()
    {
        return isset($this->diagnostic_supported);
    }

    public function clearDiagnosticSupported()
    {
        unset($this->diagnostic_supported);
    }

    /**
     * Generated from protobuf field <code>optional uint32 diagnostic_supported = 28 [json_name = "diagnostic_supported"];</code>
     * @param int $var
     * @return $this
     */
    public function setDiagnosticSupported($var)
    {
        GPBUtil::checkUint32($var);
        $this->diagnostic_supported = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 requests_supported = 29 [json_name = "requests_supported"];</code>
     * @return int
     */
    public function getRequestsSupported()
    {
        return isset($this->requests_supported) ? $this->requests_supported : 0;
    }

    public function hasRequestsSupported()
    {
        return isset($this->requests_supported);
    }

    public function clearRequestsSupported()
    {
        unset($this->requests_supported);
    }

    /**
     * Generated from protobuf field <code>optional uint32 requests_supported = 29 [json_name = "requests_supported"];</code>
     * @param int $var
     * @return $this
     */
    public function setRequestsSupported($var)
    {
        GPBUtil::checkUint32($var);
        $this->requests_supported = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional sint32 server_distance = 30 [json_name = "server_distance"];</code>
     * @return int
     */
    public function getServerDistance()
    {
        return isset($this->server_distance) ? $this->server_distance : 0;
    }

    public function hasServerDistance()
    {
        return isset($this->server_distance);
    }

    public function clearServerDistance()
    {
        unset($this->server_distance);
    }

    /**
     * Generated from protobuf field <code>optional sint32 server_distance = 30 [json_name = "server_distance"];</code>
     * @param int $var
     * @return $this
     */
    public function setServerDistance($var)
    {
        GPBUtil::checkInt32($var);
        $this->server_distance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 direction_indication = 31 [json_name = "direction_indication"];</code>
     * @return int
     */
    public function getDirectionIndication()
    {
        return isset($this->direction_indication) ? $this->direction_indication : 0;
    }

    public function hasDirectionIndication()
    {
        return isset($this->direction_indication);
    }

    public function clearDirectionIndication()
    {
        unset($this->direction_indication);
    }

    /**
     * Generated from protobuf field <code>optional uint32 direction_indication = 31 [json_name = "direction_indication"];</code>
     * @param int $var
     * @return $this
     */
    public function setDirectionIndication($var)
    {
        GPBUtil::checkUint32($var);
        $this->direction_indication = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 tachograph_performance = 32 [json_name = "tachograph_performance"];</code>
     * @return int
     */
    public function getTachographPerformance()
    {
        return isset($this->tachograph_performance) ? $this->tachograph_performance : 0;
    }

    public function hasTachographPerformance()
    {
        return isset($this->tachograph_performance);
    }

    public function clearTachographPerformance()
    {
        unset($this->tachograph_performance);
    }

    /**
     * Generated from protobuf field <code>optional uint32 tachograph_performance = 32 [json_name = "tachograph_performance"];</code>
     * @param int $var
     * @return $this
     */
    public function setTachographPerformance($var)
    {
        GPBUtil::checkUint32($var);
        $this->tachograph_performance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 handling_info = 33 [json_name = "handling_info"];</code>
     * @return int
     */
    public function getHandlingInfo()
    {
        return isset($this->handling_info) ? $this->handling_info : 0;
    }

    public function hasHandlingInfo()
    {
        return isset($this->handling_info);
    }

    public function clearHandlingInfo()
    {
        unset($this->handling_info);
    }

    /**
     * Generated from protobuf field <code>optional uint32 handling_info = 33 [json_name = "handling_info"];</code>
     * @param int $var
     * @return $this
     */
    public function setHandlingInfo($var)
    {
        GPBUtil::checkUint32($var);
        $this->handling_info = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 system_event = 34 [json_name = "system_event"];</code>
     * @return int
     */
    public function getSystemEvent()
    {
        return isset($this->system_event) ? $this->system_event : 0;
    }

    public function hasSystemEvent()
    {
        return isset($this->system_event);
    }

    public function clearSystemEvent()
    {
        unset($this->system_event);
    }

    /**
     * Generated from protobuf field <code>optional uint32 system_event = 34 [json_name = "system_event"];</code>
     * @param int $var
     * @return $this
     */
    public function setSystemEvent($var)
    {
        GPBUtil::checkUint32($var);
        $this->system_event = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional sint32 engine_coolant_temperature = 35 [json_name = "engine_coolant_temperature"];</code>
     * @return int
     */
    public function getEngineCoolantTemperature()
    {
        return isset($this->engine_coolant_temperature) ? $this->engine_coolant_temperature : 0;
    }

    public function hasEngineCoolantTemperature()
    {
        return isset($this->engine_coolant_temperature);
    }

    public function clearEngineCoolantTemperature()
    {
        unset($this->engine_coolant_temperature);
    }

    /**
     * Generated from protobuf field <code>optional sint32 engine_coolant_temperature = 35 [json_name = "engine_coolant_temperature"];</code>
     * @param int $var
     * @return $this
     */
    public function setEngineCoolantTemperature($var)
    {
        GPBUtil::checkInt32($var);
        $this->engine_coolant_temperature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional sint32 ambient_air_temperature = 36 [json_name = "ambient_air_temperature"];</code>
     * @return int
     */
    public function getAmbientAirTemperature()
    {
        return isset($this->ambient_air_temperature) ? $this->ambient_air_temperature : 0;
    }

    public function hasAmbientAirTemperature()
    {
        return isset($this->ambient_air_temperature);
    }

    public function clearAmbientAirTemperature()
    {
        unset($this->ambient_air_temperature);
    }

    /**
     * Generated from protobuf field <code>optional sint32 ambient_air_temperature = 36 [json_name = "ambient_air_temperature"];</code>
     * @param int $var
     * @return $this
     */
    public function setAmbientAirTemperature($var)
    {
        GPBUtil::checkInt32($var);
        $this->ambient_air_temperature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 fuel_rate = 37 [json_name = "fuel_rate"];</code>
     * @return int
     */
    public function getFuelRate()
    {
        return isset($this->fuel_rate) ? $this->fuel_rate : 0;
    }

    public function hasFuelRate()
    {
        return isset($this->fuel_rate);
    }

    public function clearFuelRate()
    {
        unset($this->fuel_rate);
    }

    /**
     * Generated from protobuf field <code>optional uint32 fuel_rate = 37 [json_name = "fuel_rate"];</code>
     * @param int $var
     * @return $this
     */
    public function setFuelRate($var)
    {
        GPBUtil::checkUint32($var);
        $this->fuel_rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 instantaneous_fuel_economy = 38 [json_name = "instantaneous_fuel_economy"];</code>
     * @return int
     */
    public function getInstantaneousFuelEconomy()
    {
        return isset($this->instantaneous_fuel_economy) ? $this->instantaneous_fuel_economy : 0;
    }

    public function hasInstantaneousFuelEconomy()
    {
        return isset($this->instantaneous_fuel_economy);
    }

    public function clearInstantaneousFuelEconomy()
    {
        unset($this->instantaneous_fuel_economy);
    }

    /**
     * Generated from protobuf field <code>optional uint32 instantaneous_fuel_economy = 38 [json_name = "instantaneous_fuel_economy"];</code>
     * @param int $var
     * @return $this
     */
    public function setInstantaneousFuelEconomy($var)
    {
        GPBUtil::checkUint32($var);
        $this->instantaneous_fuel_economy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 pto_drive_engagement = 39 [json_name = "pto_drive_engagement"];</code>
     * @return int
     */
    public function getPtoDriveEngagement()
    {
        return isset($this->pto_drive_engagement) ? $this->pto_drive_engagement : 0;
    }

    public function hasPtoDriveEngagement()
    {
        return isset($this->pto_drive_engagement);
    }

    public function clearPtoDriveEngagement()
    {
        unset($this->pto_drive_engagement);
    }

    /**
     * Generated from protobuf field <code>optional uint32 pto_drive_engagement = 39 [json_name = "pto_drive_engagement"];</code>
     * @param int $var
     * @return $this
     */
    public function setPtoDriveEngagement($var)
    {
        GPBUtil::checkUint32($var);
        $this->pto_drive_engagement = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 high_resolution_engine_total_fuel_used = 40 [json_name = "high_resolution_engine_total_fuel_used"];</code>
     * @return int
     */
    public function getHighResolutionEngineTotalFuelUsed()
    {
        return isset($this->high_resolution_engine_total_fuel_used) ? $this->high_resolution_engine_total_fuel_used : 0;
    }

    public function hasHighResolutionEngineTotalFuelUsed()
    {
        return isset($this->high_resolution_engine_total_fuel_used);
    }

    public function clearHighResolutionEngineTotalFuelUsed()
    {
        unset($this->high_resolution_engine_total_fuel_used);
    }

    /**
     * Generated from protobuf field <code>optional uint32 high_resolution_engine_total_fuel_used = 40 [json_name = "high_resolution_engine_total_fuel_used"];</code>
     * @param int $var
     * @return $this
     */
    public function setHighResolutionEngineTotalFuelUsed($var)
    {
        GPBUtil::checkUint32($var);
        $this->high_resolution_engine_total_fuel_used = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 gross_combination_vehicle_weight = 41 [json_name = "gross_combination_vehicle_weight"];</code>
     * @return int
     */
    public function getGrossCombinationVehicleWeight()
    {
        return isset($this->gross_combination_vehicle_weight) ? $this->gross_combination_vehicle_weight : 0;
    }

    public function hasGrossCombinationVehicleWeight()
    {
        return isset($this->gross_combination_vehicle_weight);
    }

    public function clearGrossCombinationVehicleWeight()
    {
        unset($this->gross_combination_vehicle_weight);
    }

    /**
     * Generated from protobuf field <code>optional uint32 gross_combination_vehicle_weight = 41 [json_name = "gross_combination_vehicle_weight"];</code>
     * @param int $var
     * @return $this
     */
    public function setGrossCombinationVehicleWeight($var)
    {
        GPBUtil::checkUint32($var);
        $this->gross_combination_vehicle_weight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 ad_blue_status = 42 [json_name = "ad_blue_status"];</code>
     * @return int
     */
    public function getAdBlueStatus()
    {
        return isset($this->ad_blue_status) ? $this->ad_blue_status : 0;
    }

    public function hasAdBlueStatus()
    {
        return isset($this->ad_blue_status);
    }

    public function clearAdBlueStatus()
    {
        unset($this->ad_blue_status);
    }

    /**
     * Generated from protobuf field <code>optional uint32 ad_blue_status = 42 [json_name = "ad_blue_status"];</code>
     * @param int $var
     * @return $this
     */
    public function setAdBlueStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->ad_blue_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 brake_pedal_position = 43 [json_name = "brake_pedal_position"];</code>
     * @return int
     */
    public function getBrakePedalPosition()
    {
        return isset($this->brake_pedal_position) ? $this->brake_pedal_position : 0;
    }

    public function hasBrakePedalPosition()
    {
        return isset($this->brake_pedal_position);
    }

    public function clearBrakePedalPosition()
    {
        unset($this->brake_pedal_position);
    }

    /**
     * Generated from protobuf field <code>optional uint32 brake_pedal_position = 43 [json_name = "brake_pedal_position"];</code>
     * @param int $var
     * @return $this
     */
    public function setBrakePedalPosition($var)
    {
        GPBUtil::checkUint32($var);
        $this->brake_pedal_position = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 fuel_level2 = 44 [json_name = "fuel_level_2"];</code>
     * @return int
     */
    public function getFuelLevel2()
    {
        return isset($this->fuel_level2) ? $this->fuel_level2 : 0;
    }

    public function hasFuelLevel2()
    {
        return isset($this->fuel_level2);
    }

    public function clearFuelLevel2()
    {
        unset($this->fuel_level2);
    }

    /**
     * Generated from protobuf field <code>optional uint32 fuel_level2 = 44 [json_name = "fuel_level_2"];</code>
     * @param int $var
     * @return $this
     */
    public function setFuelLevel2($var)
    {
        GPBUtil::checkUint32($var);
        $this->fuel_level2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 mil_indicator = 45 [json_name = "mil_indicator"];</code>
     * @return int
     */
    public function getMilIndicator()
    {
        return isset($this->mil_indicator) ? $this->mil_indicator : 0;
    }

    public function hasMilIndicator()
    {
        return isset($this->mil_indicator);
    }

    public function clearMilIndicator()
    {
        unset($this->mil_indicator);
    }

    /**
     * Generated from protobuf field <code>optional uint32 mil_indicator = 45 [json_name = "mil_indicator"];</code>
     * @param int $var
     * @return $this
     */
    public function setMilIndicator($var)
    {
        GPBUtil::checkUint32($var);
        $this->mil_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes tell_tale0 = 46 [json_name = "tell_tale_0"];</code>
     * @return string
     */
    public function getTellTale0()
    {
        return isset($this->tell_tale0) ? $this->tell_tale0 : '';
    }

    public function hasTellTale0()
    {
        return isset($this->tell_tale0);
    }

    public function clearTellTale0()
    {
        unset($this->tell_tale0);
    }

    /**
     * Generated from protobuf field <code>optional bytes tell_tale0 = 46 [json_name = "tell_tale_0"];</code>
     * @param string $var
     * @return $this
     */
    public function setTellTale0($var)
    {
        GPBUtil::checkString($var, False);
        $this->tell_tale0 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes tell_tale1 = 47 [json_name = "tell_tale_1"];</code>
     * @return string
     */
    public function getTellTale1()
    {
        return isset($this->tell_tale1) ? $this->tell_tale1 : '';
    }

    public function hasTellTale1()
    {
        return isset($this->tell_tale1);
    }

    public function clearTellTale1()
    {
        unset($this->tell_tale1);
    }

    /**
     * Generated from protobuf field <code>optional bytes tell_tale1 = 47 [json_name = "tell_tale_1"];</code>
     * @param string $var
     * @return $this
     */
    public function setTellTale1($var)
    {
        GPBUtil::checkString($var, False);
        $this->tell_tale1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes tell_tale2 = 48 [json_name = "tell_tale_2"];</code>
     * @return string
     */
    public function getTellTale2()
    {
        return isset($this->tell_tale2) ? $this->tell_tale2 : '';
    }

    public function hasTellTale2()
    {
        return isset($this->tell_tale2);
    }

    public function clearTellTale2()
    {
        unset($this->tell_tale2);
    }

    /**
     * Generated from protobuf field <code>optional bytes tell_tale2 = 48 [json_name = "tell_tale_2"];</code>
     * @param string $var
     * @return $this
     */
    public function setTellTale2($var)
    {
        GPBUtil::checkString($var, False);
        $this->tell_tale2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes tell_tale3 = 49 [json_name = "tell_tale_3"];</code>
     * @return string
     */
    public function getTellTale3()
    {
        return isset($this->tell_tale3) ? $this->tell_tale3 : '';
    }

    public function hasTellTale3()
    {
        return isset($this->tell_tale3);
    }

    public function clearTellTale3()
    {
        unset($this->tell_tale3);
    }

    /**
     * Generated from protobuf field <code>optional bytes tell_tale3 = 49 [json_name = "tell_tale_3"];</code>
     * @param string $var
     * @return $this
     */
    public function setTellTale3($var)
    {
        GPBUtil::checkString($var, False);
        $this->tell_tale3 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes tell_tale4 = 50 [json_name = "tell_tale_4"];</code>
     * @return string
     */
    public function getTellTale4()
    {
        return isset($this->tell_tale4) ? $this->tell_tale4 : '';
    }

    public function hasTellTale4()
    {
        return isset($this->tell_tale4);
    }

    public function clearTellTale4()
    {
        unset($this->tell_tale4);
    }

    /**
     * Generated from protobuf field <code>optional bytes tell_tale4 = 50 [json_name = "tell_tale_4"];</code>
     * @param string $var
     * @return $this
     */
    public function setTellTale4($var)
    {
        GPBUtil::checkString($var, False);
        $this->tell_tale4 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 ad_blue_level = 51 [json_name = "ad_blue_level"];</code>
     * @return int
     */
    public function getAdBlueLevel()
    {
        return isset($this->ad_blue_level) ? $this->ad_blue_level : 0;
    }

    public function hasAdBlueLevel()
    {
        return isset($this->ad_blue_level);
    }

    public function clearAdBlueLevel()
    {
        unset($this->ad_blue_level);
    }

    /**
     * Generated from protobuf field <code>optional uint32 ad_blue_level = 51 [json_name = "ad_blue_level"];</code>
     * @param int $var
     * @return $this
     */
    public function setAdBlueLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->ad_blue_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 dtc_dm1 = 52 [json_name = "dtc_dm_1"];</code>
     * @return int
     */
    public function getDtcDm1()
    {
        return isset($this->dtc_dm1) ? $this->dtc_dm1 : 0;
    }

    public function hasDtcDm1()
    {
        return isset($this->dtc_dm1);
    }

    public function clearDtcDm1()
    {
        unset($this->dtc_dm1);
    }

    /**
     * Generated from protobuf field <code>optional uint32 dtc_dm1 = 52 [json_name = "dtc_dm_1"];</code>
     * @param int $var
     * @return $this
     */
    public function setDtcDm1($var)
    {
        GPBUtil::checkUint32($var);
        $this->dtc_dm1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 dtc_time_dm1 = 53 [json_name = "dtc_time_dm_1"];</code>
     * @return int
     */
    public function getDtcTimeDm1()
    {
        return isset($this->dtc_time_dm1) ? $this->dtc_time_dm1 : 0;
    }

    public function hasDtcTimeDm1()
    {
        return isset($this->dtc_time_dm1);
    }

    public function clearDtcTimeDm1()
    {
        unset($this->dtc_time_dm1);
    }

    /**
     * Generated from protobuf field <code>optional uint32 dtc_time_dm1 = 53 [json_name = "dtc_time_dm_1"];</code>
     * @param int $var
     * @return $this
     */
    public function setDtcTimeDm1($var)
    {
        GPBUtil::checkUint32($var);
        $this->dtc_time_dm1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 dtc_dm2 = 54 [json_name = "dtc_dm_2"];</code>
     * @return int
     */
    public function getDtcDm2()
    {
        return isset($this->dtc_dm2) ? $this->dtc_dm2 : 0;
    }

    public function hasDtcDm2()
    {
        return isset($this->dtc_dm2);
    }

    public function clearDtcDm2()
    {
        unset($this->dtc_dm2);
    }

    /**
     * Generated from protobuf field <code>optional uint32 dtc_dm2 = 54 [json_name = "dtc_dm_2"];</code>
     * @param int $var
     * @return $this
     */
    public function setDtcDm2($var)
    {
        GPBUtil::checkUint32($var);
        $this->dtc_dm2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 dtc_time_dm2 = 55 [json_name = "dtc_time_dm_2"];</code>
     * @return int
     */
    public function getDtcTimeDm2()
    {
        return isset($this->dtc_time_dm2) ? $this->dtc_time_dm2 : 0;
    }

    public function hasDtcTimeDm2()
    {
        return isset($this->dtc_time_dm2);
    }

    public function clearDtcTimeDm2()
    {
        unset($this->dtc_time_dm2);
    }

    /**
     * Generated from protobuf field <code>optional uint32 dtc_time_dm2 = 55 [json_name = "dtc_time_dm_2"];</code>
     * @param int $var
     * @return $this
     */
    public function setDtcTimeDm2($var)
    {
        GPBUtil::checkUint32($var);
        $this->dtc_time_dm2 = $var;

        return $this;
    }

}

