<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packets/dataModel.proto

namespace Fatehan\Packet\DataModel;

if (false) {
    /**
     * This class is deprecated. Use Fatehan\Packet\DataModel\IoElement\Ble instead.
     * @deprecated
     */
    class IoElement_Ble {}
}
class_exists(IoElement\Ble::class);
@trigger_error('Fatehan\Packet\DataModel\IoElement_Ble is deprecated and will be removed in the next major release. Use Fatehan\Packet\DataModel\IoElement\Ble instead', E_USER_DEPRECATED);

