<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: packets/dataModel.proto

namespace Fatehan\Packet\DataModel;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.packets.ObdElements</code>
 */
class ObdElements extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string vin = 241 [json_name = "vin"];</code>
     */
    protected $vin = null;
    /**
     * Generated from protobuf field <code>optional int32 short_fuel_trim = 242 [json_name = "short_fuel_trim"];</code>
     */
    protected $short_fuel_trim = null;
    /**
     * Generated from protobuf field <code>optional uint32 fuel_pressure = 243 [json_name = "fuel_pressure"];</code>
     */
    protected $fuel_pressure = null;
    /**
     * Generated from protobuf field <code>optional uint32 intake_map = 244 [json_name = "intake_map"];</code>
     */
    protected $intake_map = null;
    /**
     * Generated from protobuf field <code>optional uint32 vehicle_speed = 245 [json_name = "vehicle_speed"];</code>
     */
    protected $vehicle_speed = null;
    /**
     * Generated from protobuf field <code>optional int32 timing_advance = 246 [json_name = "timing_advance"];</code>
     */
    protected $timing_advance = null;
    /**
     * Generated from protobuf field <code>optional int32 intake_air_temperature = 247 [json_name = "intake_air_temperature"];</code>
     */
    protected $intake_air_temperature = null;
    /**
     * Generated from protobuf field <code>optional uint32 maf = 248 [json_name = "maf"];</code>
     */
    protected $maf = null;
    /**
     * Generated from protobuf field <code>optional uint32 throttle_position = 249 [json_name = "throttle_position"];</code>
     */
    protected $throttle_position = null;
    /**
     * Generated from protobuf field <code>optional uint32 runtime_since_engine_start = 250 [json_name = "runtime_since_engine_start"];</code>
     */
    protected $runtime_since_engine_start = null;
    /**
     * Generated from protobuf field <code>optional uint32 distance_traveled_mil_on = 251 [json_name = "distance_traveled_mil_on"];</code>
     */
    protected $distance_traveled_mil_on = null;
    /**
     * Generated from protobuf field <code>optional uint32 relative_fuel_rail_pressure = 252 [json_name = "relative_fuel_rail_pressure"];</code>
     */
    protected $relative_fuel_rail_pressure = null;
    /**
     * Generated from protobuf field <code>optional uint32 direct_fuel_rail_pressure = 253 [json_name = "direct_fuel_rail_pressure"];</code>
     */
    protected $direct_fuel_rail_pressure = null;
    /**
     * Generated from protobuf field <code>optional uint32 commanded_egr = 254 [json_name = "commanded_egr"];</code>
     */
    protected $commanded_egr = null;
    /**
     * Generated from protobuf field <code>optional int32 egr_error = 255 [json_name = "egr_error"];</code>
     */
    protected $egr_error = null;
    /**
     * Generated from protobuf field <code>optional uint32 distance_since_codes_clear = 256 [json_name = "distance_since_codes_clear"];</code>
     */
    protected $distance_since_codes_clear = null;
    /**
     * Generated from protobuf field <code>optional uint32 barometric_pressure = 257 [json_name = "barometric_pressure"];</code>
     */
    protected $barometric_pressure = null;
    /**
     * Generated from protobuf field <code>optional uint32 control_module_voltage = 258 [json_name = "control_module_voltage"];</code>
     */
    protected $control_module_voltage = null;
    /**
     * Generated from protobuf field <code>optional uint32 absolute_load_value = 259 [json_name = "absolute_load_value"];</code>
     */
    protected $absolute_load_value = null;
    /**
     * Generated from protobuf field <code>optional uint32 fuel_type = 260 [json_name = "fuel_type"];</code>
     */
    protected $fuel_type = null;
    /**
     * Generated from protobuf field <code>optional int32 ambient_air_temperature = 261 [json_name = "ambient_air_temperature"];</code>
     */
    protected $ambient_air_temperature = null;
    /**
     * Generated from protobuf field <code>optional uint32 time_run_with_mil_on = 262 [json_name = "time_run_with_mil_on"];</code>
     */
    protected $time_run_with_mil_on = null;
    /**
     * Generated from protobuf field <code>optional uint32 time_since_codes_cleared = 263 [json_name = "time_since_codes_cleared"];</code>
     */
    protected $time_since_codes_cleared = null;
    /**
     * Generated from protobuf field <code>optional uint32 absolute_fuel_rail_pressure = 264 [json_name = "absolute_fuel_rail_pressure"];</code>
     */
    protected $absolute_fuel_rail_pressure = null;
    /**
     * Generated from protobuf field <code>optional uint32 hybrid_battery_pack_life = 265 [json_name = "hybrid_battery_pack_life"];</code>
     */
    protected $hybrid_battery_pack_life = null;
    /**
     * Generated from protobuf field <code>optional uint32 engine_oil_temperature = 266 [json_name = "engine_oil_temperature"];</code>
     */
    protected $engine_oil_temperature = null;
    /**
     * Generated from protobuf field <code>optional int32 fuel_injection_timing = 267 [json_name = "fuel_injection_timing"];</code>
     */
    protected $fuel_injection_timing = null;
    /**
     * Generated from protobuf field <code>optional uint32 throttle_position_group = 268 [json_name = "throttle_position_group"];</code>
     */
    protected $throttle_position_group = null;
    /**
     * Generated from protobuf field <code>optional uint32 commanded_equivalence_r = 269 [json_name = "commanded_equivalence_r"];</code>
     */
    protected $commanded_equivalence_r = null;
    /**
     * Generated from protobuf field <code>optional uint32 intake_map_2_bytes = 270 [json_name = "intake_map_2_bytes"];</code>
     */
    protected $intake_map_2_bytes = null;
    /**
     * Generated from protobuf field <code>optional uint32 hybrid_system_voltage = 271 [json_name = "hybrid_system_voltage"];</code>
     */
    protected $hybrid_system_voltage = null;
    /**
     * Generated from protobuf field <code>optional int32 hybrid_system_current = 272 [json_name = "hybrid_system_current"];</code>
     */
    protected $hybrid_system_current = null;
    /**
     * Generated from protobuf field <code>optional string fault_codes = 273 [json_name = "fault_codes"];</code>
     */
    protected $fault_codes = null;
    /**
     * Generated from protobuf field <code>optional bool ecu_break_switch = 25 [json_name = "ecu_break_switch"];</code>
     */
    protected $ecu_break_switch = null;
    /**
     * Generated from protobuf field <code>optional int32 coolant_temperature = 26 [json_name = "coolant_temperature"];</code>
     */
    protected $coolant_temperature = null;
    /**
     * Generated from protobuf field <code>optional uint32 number_of_dtc = 27 [json_name = "number_of_dtc"];</code>
     */
    protected $number_of_dtc = null;
    /**
     * Generated from protobuf field <code>optional uint32 engine_load = 28 [json_name = "engine_load"];</code>
     */
    protected $engine_load = null;
    /**
     * Generated from protobuf field <code>optional uint32 engine_rpm = 29 [json_name = "engine_rpm"];</code>
     */
    protected $engine_rpm = null;
    /**
     * Generated from protobuf field <code>optional uint32 fuel_level = 30 [json_name = "fuel_level"];</code>
     */
    protected $fuel_level = null;
    /**
     * Generated from protobuf field <code>optional uint32 fuel_rate = 31 [json_name = "fuel_rate"];</code>
     */
    protected $fuel_rate = null;
    /**
     * Generated from protobuf field <code>optional uint32 tire_pressure = 32 [json_name = "tire_pressure"];</code>
     */
    protected $tire_pressure = null;
    /**
     * Generated from protobuf field <code>optional uint32 analog = 34 [json_name = "analog"];</code>
     */
    protected $analog = null;
    /**
     * Generated from protobuf field <code>optional uint32 oil = 35 [json_name = "oil"];</code>
     */
    protected $oil = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $vin
     *     @type int $short_fuel_trim
     *     @type int $fuel_pressure
     *     @type int $intake_map
     *     @type int $vehicle_speed
     *     @type int $timing_advance
     *     @type int $intake_air_temperature
     *     @type int $maf
     *     @type int $throttle_position
     *     @type int $runtime_since_engine_start
     *     @type int $distance_traveled_mil_on
     *     @type int $relative_fuel_rail_pressure
     *     @type int $direct_fuel_rail_pressure
     *     @type int $commanded_egr
     *     @type int $egr_error
     *     @type int $distance_since_codes_clear
     *     @type int $barometric_pressure
     *     @type int $control_module_voltage
     *     @type int $absolute_load_value
     *     @type int $fuel_type
     *     @type int $ambient_air_temperature
     *     @type int $time_run_with_mil_on
     *     @type int $time_since_codes_cleared
     *     @type int $absolute_fuel_rail_pressure
     *     @type int $hybrid_battery_pack_life
     *     @type int $engine_oil_temperature
     *     @type int $fuel_injection_timing
     *     @type int $throttle_position_group
     *     @type int $commanded_equivalence_r
     *     @type int $intake_map_2_bytes
     *     @type int $hybrid_system_voltage
     *     @type int $hybrid_system_current
     *     @type string $fault_codes
     *     @type bool $ecu_break_switch
     *     @type int $coolant_temperature
     *     @type int $number_of_dtc
     *     @type int $engine_load
     *     @type int $engine_rpm
     *     @type int $fuel_level
     *     @type int $fuel_rate
     *     @type int $tire_pressure
     *     @type int $analog
     *     @type int $oil
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Packet\DataModel\MetaData\DataModel::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string vin = 241 [json_name = "vin"];</code>
     * @return string
     */
    public function getVin()
    {
        return isset($this->vin) ? $this->vin : '';
    }

    public function hasVin()
    {
        return isset($this->vin);
    }

    public function clearVin()
    {
        unset($this->vin);
    }

    /**
     * Generated from protobuf field <code>optional string vin = 241 [json_name = "vin"];</code>
     * @param string $var
     * @return $this
     */
    public function setVin($var)
    {
        GPBUtil::checkString($var, True);
        $this->vin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 short_fuel_trim = 242 [json_name = "short_fuel_trim"];</code>
     * @return int
     */
    public function getShortFuelTrim()
    {
        return isset($this->short_fuel_trim) ? $this->short_fuel_trim : 0;
    }

    public function hasShortFuelTrim()
    {
        return isset($this->short_fuel_trim);
    }

    public function clearShortFuelTrim()
    {
        unset($this->short_fuel_trim);
    }

    /**
     * Generated from protobuf field <code>optional int32 short_fuel_trim = 242 [json_name = "short_fuel_trim"];</code>
     * @param int $var
     * @return $this
     */
    public function setShortFuelTrim($var)
    {
        GPBUtil::checkInt32($var);
        $this->short_fuel_trim = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 fuel_pressure = 243 [json_name = "fuel_pressure"];</code>
     * @return int
     */
    public function getFuelPressure()
    {
        return isset($this->fuel_pressure) ? $this->fuel_pressure : 0;
    }

    public function hasFuelPressure()
    {
        return isset($this->fuel_pressure);
    }

    public function clearFuelPressure()
    {
        unset($this->fuel_pressure);
    }

    /**
     * Generated from protobuf field <code>optional uint32 fuel_pressure = 243 [json_name = "fuel_pressure"];</code>
     * @param int $var
     * @return $this
     */
    public function setFuelPressure($var)
    {
        GPBUtil::checkUint32($var);
        $this->fuel_pressure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 intake_map = 244 [json_name = "intake_map"];</code>
     * @return int
     */
    public function getIntakeMap()
    {
        return isset($this->intake_map) ? $this->intake_map : 0;
    }

    public function hasIntakeMap()
    {
        return isset($this->intake_map);
    }

    public function clearIntakeMap()
    {
        unset($this->intake_map);
    }

    /**
     * Generated from protobuf field <code>optional uint32 intake_map = 244 [json_name = "intake_map"];</code>
     * @param int $var
     * @return $this
     */
    public function setIntakeMap($var)
    {
        GPBUtil::checkUint32($var);
        $this->intake_map = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 vehicle_speed = 245 [json_name = "vehicle_speed"];</code>
     * @return int
     */
    public function getVehicleSpeed()
    {
        return isset($this->vehicle_speed) ? $this->vehicle_speed : 0;
    }

    public function hasVehicleSpeed()
    {
        return isset($this->vehicle_speed);
    }

    public function clearVehicleSpeed()
    {
        unset($this->vehicle_speed);
    }

    /**
     * Generated from protobuf field <code>optional uint32 vehicle_speed = 245 [json_name = "vehicle_speed"];</code>
     * @param int $var
     * @return $this
     */
    public function setVehicleSpeed($var)
    {
        GPBUtil::checkUint32($var);
        $this->vehicle_speed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 timing_advance = 246 [json_name = "timing_advance"];</code>
     * @return int
     */
    public function getTimingAdvance()
    {
        return isset($this->timing_advance) ? $this->timing_advance : 0;
    }

    public function hasTimingAdvance()
    {
        return isset($this->timing_advance);
    }

    public function clearTimingAdvance()
    {
        unset($this->timing_advance);
    }

    /**
     * Generated from protobuf field <code>optional int32 timing_advance = 246 [json_name = "timing_advance"];</code>
     * @param int $var
     * @return $this
     */
    public function setTimingAdvance($var)
    {
        GPBUtil::checkInt32($var);
        $this->timing_advance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 intake_air_temperature = 247 [json_name = "intake_air_temperature"];</code>
     * @return int
     */
    public function getIntakeAirTemperature()
    {
        return isset($this->intake_air_temperature) ? $this->intake_air_temperature : 0;
    }

    public function hasIntakeAirTemperature()
    {
        return isset($this->intake_air_temperature);
    }

    public function clearIntakeAirTemperature()
    {
        unset($this->intake_air_temperature);
    }

    /**
     * Generated from protobuf field <code>optional int32 intake_air_temperature = 247 [json_name = "intake_air_temperature"];</code>
     * @param int $var
     * @return $this
     */
    public function setIntakeAirTemperature($var)
    {
        GPBUtil::checkInt32($var);
        $this->intake_air_temperature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 maf = 248 [json_name = "maf"];</code>
     * @return int
     */
    public function getMaf()
    {
        return isset($this->maf) ? $this->maf : 0;
    }

    public function hasMaf()
    {
        return isset($this->maf);
    }

    public function clearMaf()
    {
        unset($this->maf);
    }

    /**
     * Generated from protobuf field <code>optional uint32 maf = 248 [json_name = "maf"];</code>
     * @param int $var
     * @return $this
     */
    public function setMaf($var)
    {
        GPBUtil::checkUint32($var);
        $this->maf = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 throttle_position = 249 [json_name = "throttle_position"];</code>
     * @return int
     */
    public function getThrottlePosition()
    {
        return isset($this->throttle_position) ? $this->throttle_position : 0;
    }

    public function hasThrottlePosition()
    {
        return isset($this->throttle_position);
    }

    public function clearThrottlePosition()
    {
        unset($this->throttle_position);
    }

    /**
     * Generated from protobuf field <code>optional uint32 throttle_position = 249 [json_name = "throttle_position"];</code>
     * @param int $var
     * @return $this
     */
    public function setThrottlePosition($var)
    {
        GPBUtil::checkUint32($var);
        $this->throttle_position = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 runtime_since_engine_start = 250 [json_name = "runtime_since_engine_start"];</code>
     * @return int
     */
    public function getRuntimeSinceEngineStart()
    {
        return isset($this->runtime_since_engine_start) ? $this->runtime_since_engine_start : 0;
    }

    public function hasRuntimeSinceEngineStart()
    {
        return isset($this->runtime_since_engine_start);
    }

    public function clearRuntimeSinceEngineStart()
    {
        unset($this->runtime_since_engine_start);
    }

    /**
     * Generated from protobuf field <code>optional uint32 runtime_since_engine_start = 250 [json_name = "runtime_since_engine_start"];</code>
     * @param int $var
     * @return $this
     */
    public function setRuntimeSinceEngineStart($var)
    {
        GPBUtil::checkUint32($var);
        $this->runtime_since_engine_start = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 distance_traveled_mil_on = 251 [json_name = "distance_traveled_mil_on"];</code>
     * @return int
     */
    public function getDistanceTraveledMilOn()
    {
        return isset($this->distance_traveled_mil_on) ? $this->distance_traveled_mil_on : 0;
    }

    public function hasDistanceTraveledMilOn()
    {
        return isset($this->distance_traveled_mil_on);
    }

    public function clearDistanceTraveledMilOn()
    {
        unset($this->distance_traveled_mil_on);
    }

    /**
     * Generated from protobuf field <code>optional uint32 distance_traveled_mil_on = 251 [json_name = "distance_traveled_mil_on"];</code>
     * @param int $var
     * @return $this
     */
    public function setDistanceTraveledMilOn($var)
    {
        GPBUtil::checkUint32($var);
        $this->distance_traveled_mil_on = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 relative_fuel_rail_pressure = 252 [json_name = "relative_fuel_rail_pressure"];</code>
     * @return int
     */
    public function getRelativeFuelRailPressure()
    {
        return isset($this->relative_fuel_rail_pressure) ? $this->relative_fuel_rail_pressure : 0;
    }

    public function hasRelativeFuelRailPressure()
    {
        return isset($this->relative_fuel_rail_pressure);
    }

    public function clearRelativeFuelRailPressure()
    {
        unset($this->relative_fuel_rail_pressure);
    }

    /**
     * Generated from protobuf field <code>optional uint32 relative_fuel_rail_pressure = 252 [json_name = "relative_fuel_rail_pressure"];</code>
     * @param int $var
     * @return $this
     */
    public function setRelativeFuelRailPressure($var)
    {
        GPBUtil::checkUint32($var);
        $this->relative_fuel_rail_pressure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 direct_fuel_rail_pressure = 253 [json_name = "direct_fuel_rail_pressure"];</code>
     * @return int
     */
    public function getDirectFuelRailPressure()
    {
        return isset($this->direct_fuel_rail_pressure) ? $this->direct_fuel_rail_pressure : 0;
    }

    public function hasDirectFuelRailPressure()
    {
        return isset($this->direct_fuel_rail_pressure);
    }

    public function clearDirectFuelRailPressure()
    {
        unset($this->direct_fuel_rail_pressure);
    }

    /**
     * Generated from protobuf field <code>optional uint32 direct_fuel_rail_pressure = 253 [json_name = "direct_fuel_rail_pressure"];</code>
     * @param int $var
     * @return $this
     */
    public function setDirectFuelRailPressure($var)
    {
        GPBUtil::checkUint32($var);
        $this->direct_fuel_rail_pressure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 commanded_egr = 254 [json_name = "commanded_egr"];</code>
     * @return int
     */
    public function getCommandedEgr()
    {
        return isset($this->commanded_egr) ? $this->commanded_egr : 0;
    }

    public function hasCommandedEgr()
    {
        return isset($this->commanded_egr);
    }

    public function clearCommandedEgr()
    {
        unset($this->commanded_egr);
    }

    /**
     * Generated from protobuf field <code>optional uint32 commanded_egr = 254 [json_name = "commanded_egr"];</code>
     * @param int $var
     * @return $this
     */
    public function setCommandedEgr($var)
    {
        GPBUtil::checkUint32($var);
        $this->commanded_egr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 egr_error = 255 [json_name = "egr_error"];</code>
     * @return int
     */
    public function getEgrError()
    {
        return isset($this->egr_error) ? $this->egr_error : 0;
    }

    public function hasEgrError()
    {
        return isset($this->egr_error);
    }

    public function clearEgrError()
    {
        unset($this->egr_error);
    }

    /**
     * Generated from protobuf field <code>optional int32 egr_error = 255 [json_name = "egr_error"];</code>
     * @param int $var
     * @return $this
     */
    public function setEgrError($var)
    {
        GPBUtil::checkInt32($var);
        $this->egr_error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 distance_since_codes_clear = 256 [json_name = "distance_since_codes_clear"];</code>
     * @return int
     */
    public function getDistanceSinceCodesClear()
    {
        return isset($this->distance_since_codes_clear) ? $this->distance_since_codes_clear : 0;
    }

    public function hasDistanceSinceCodesClear()
    {
        return isset($this->distance_since_codes_clear);
    }

    public function clearDistanceSinceCodesClear()
    {
        unset($this->distance_since_codes_clear);
    }

    /**
     * Generated from protobuf field <code>optional uint32 distance_since_codes_clear = 256 [json_name = "distance_since_codes_clear"];</code>
     * @param int $var
     * @return $this
     */
    public function setDistanceSinceCodesClear($var)
    {
        GPBUtil::checkUint32($var);
        $this->distance_since_codes_clear = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 barometric_pressure = 257 [json_name = "barometric_pressure"];</code>
     * @return int
     */
    public function getBarometricPressure()
    {
        return isset($this->barometric_pressure) ? $this->barometric_pressure : 0;
    }

    public function hasBarometricPressure()
    {
        return isset($this->barometric_pressure);
    }

    public function clearBarometricPressure()
    {
        unset($this->barometric_pressure);
    }

    /**
     * Generated from protobuf field <code>optional uint32 barometric_pressure = 257 [json_name = "barometric_pressure"];</code>
     * @param int $var
     * @return $this
     */
    public function setBarometricPressure($var)
    {
        GPBUtil::checkUint32($var);
        $this->barometric_pressure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 control_module_voltage = 258 [json_name = "control_module_voltage"];</code>
     * @return int
     */
    public function getControlModuleVoltage()
    {
        return isset($this->control_module_voltage) ? $this->control_module_voltage : 0;
    }

    public function hasControlModuleVoltage()
    {
        return isset($this->control_module_voltage);
    }

    public function clearControlModuleVoltage()
    {
        unset($this->control_module_voltage);
    }

    /**
     * Generated from protobuf field <code>optional uint32 control_module_voltage = 258 [json_name = "control_module_voltage"];</code>
     * @param int $var
     * @return $this
     */
    public function setControlModuleVoltage($var)
    {
        GPBUtil::checkUint32($var);
        $this->control_module_voltage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 absolute_load_value = 259 [json_name = "absolute_load_value"];</code>
     * @return int
     */
    public function getAbsoluteLoadValue()
    {
        return isset($this->absolute_load_value) ? $this->absolute_load_value : 0;
    }

    public function hasAbsoluteLoadValue()
    {
        return isset($this->absolute_load_value);
    }

    public function clearAbsoluteLoadValue()
    {
        unset($this->absolute_load_value);
    }

    /**
     * Generated from protobuf field <code>optional uint32 absolute_load_value = 259 [json_name = "absolute_load_value"];</code>
     * @param int $var
     * @return $this
     */
    public function setAbsoluteLoadValue($var)
    {
        GPBUtil::checkUint32($var);
        $this->absolute_load_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 fuel_type = 260 [json_name = "fuel_type"];</code>
     * @return int
     */
    public function getFuelType()
    {
        return isset($this->fuel_type) ? $this->fuel_type : 0;
    }

    public function hasFuelType()
    {
        return isset($this->fuel_type);
    }

    public function clearFuelType()
    {
        unset($this->fuel_type);
    }

    /**
     * Generated from protobuf field <code>optional uint32 fuel_type = 260 [json_name = "fuel_type"];</code>
     * @param int $var
     * @return $this
     */
    public function setFuelType($var)
    {
        GPBUtil::checkUint32($var);
        $this->fuel_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 ambient_air_temperature = 261 [json_name = "ambient_air_temperature"];</code>
     * @return int
     */
    public function getAmbientAirTemperature()
    {
        return isset($this->ambient_air_temperature) ? $this->ambient_air_temperature : 0;
    }

    public function hasAmbientAirTemperature()
    {
        return isset($this->ambient_air_temperature);
    }

    public function clearAmbientAirTemperature()
    {
        unset($this->ambient_air_temperature);
    }

    /**
     * Generated from protobuf field <code>optional int32 ambient_air_temperature = 261 [json_name = "ambient_air_temperature"];</code>
     * @param int $var
     * @return $this
     */
    public function setAmbientAirTemperature($var)
    {
        GPBUtil::checkInt32($var);
        $this->ambient_air_temperature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 time_run_with_mil_on = 262 [json_name = "time_run_with_mil_on"];</code>
     * @return int
     */
    public function getTimeRunWithMilOn()
    {
        return isset($this->time_run_with_mil_on) ? $this->time_run_with_mil_on : 0;
    }

    public function hasTimeRunWithMilOn()
    {
        return isset($this->time_run_with_mil_on);
    }

    public function clearTimeRunWithMilOn()
    {
        unset($this->time_run_with_mil_on);
    }

    /**
     * Generated from protobuf field <code>optional uint32 time_run_with_mil_on = 262 [json_name = "time_run_with_mil_on"];</code>
     * @param int $var
     * @return $this
     */
    public function setTimeRunWithMilOn($var)
    {
        GPBUtil::checkUint32($var);
        $this->time_run_with_mil_on = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 time_since_codes_cleared = 263 [json_name = "time_since_codes_cleared"];</code>
     * @return int
     */
    public function getTimeSinceCodesCleared()
    {
        return isset($this->time_since_codes_cleared) ? $this->time_since_codes_cleared : 0;
    }

    public function hasTimeSinceCodesCleared()
    {
        return isset($this->time_since_codes_cleared);
    }

    public function clearTimeSinceCodesCleared()
    {
        unset($this->time_since_codes_cleared);
    }

    /**
     * Generated from protobuf field <code>optional uint32 time_since_codes_cleared = 263 [json_name = "time_since_codes_cleared"];</code>
     * @param int $var
     * @return $this
     */
    public function setTimeSinceCodesCleared($var)
    {
        GPBUtil::checkUint32($var);
        $this->time_since_codes_cleared = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 absolute_fuel_rail_pressure = 264 [json_name = "absolute_fuel_rail_pressure"];</code>
     * @return int
     */
    public function getAbsoluteFuelRailPressure()
    {
        return isset($this->absolute_fuel_rail_pressure) ? $this->absolute_fuel_rail_pressure : 0;
    }

    public function hasAbsoluteFuelRailPressure()
    {
        return isset($this->absolute_fuel_rail_pressure);
    }

    public function clearAbsoluteFuelRailPressure()
    {
        unset($this->absolute_fuel_rail_pressure);
    }

    /**
     * Generated from protobuf field <code>optional uint32 absolute_fuel_rail_pressure = 264 [json_name = "absolute_fuel_rail_pressure"];</code>
     * @param int $var
     * @return $this
     */
    public function setAbsoluteFuelRailPressure($var)
    {
        GPBUtil::checkUint32($var);
        $this->absolute_fuel_rail_pressure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 hybrid_battery_pack_life = 265 [json_name = "hybrid_battery_pack_life"];</code>
     * @return int
     */
    public function getHybridBatteryPackLife()
    {
        return isset($this->hybrid_battery_pack_life) ? $this->hybrid_battery_pack_life : 0;
    }

    public function hasHybridBatteryPackLife()
    {
        return isset($this->hybrid_battery_pack_life);
    }

    public function clearHybridBatteryPackLife()
    {
        unset($this->hybrid_battery_pack_life);
    }

    /**
     * Generated from protobuf field <code>optional uint32 hybrid_battery_pack_life = 265 [json_name = "hybrid_battery_pack_life"];</code>
     * @param int $var
     * @return $this
     */
    public function setHybridBatteryPackLife($var)
    {
        GPBUtil::checkUint32($var);
        $this->hybrid_battery_pack_life = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 engine_oil_temperature = 266 [json_name = "engine_oil_temperature"];</code>
     * @return int
     */
    public function getEngineOilTemperature()
    {
        return isset($this->engine_oil_temperature) ? $this->engine_oil_temperature : 0;
    }

    public function hasEngineOilTemperature()
    {
        return isset($this->engine_oil_temperature);
    }

    public function clearEngineOilTemperature()
    {
        unset($this->engine_oil_temperature);
    }

    /**
     * Generated from protobuf field <code>optional uint32 engine_oil_temperature = 266 [json_name = "engine_oil_temperature"];</code>
     * @param int $var
     * @return $this
     */
    public function setEngineOilTemperature($var)
    {
        GPBUtil::checkUint32($var);
        $this->engine_oil_temperature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 fuel_injection_timing = 267 [json_name = "fuel_injection_timing"];</code>
     * @return int
     */
    public function getFuelInjectionTiming()
    {
        return isset($this->fuel_injection_timing) ? $this->fuel_injection_timing : 0;
    }

    public function hasFuelInjectionTiming()
    {
        return isset($this->fuel_injection_timing);
    }

    public function clearFuelInjectionTiming()
    {
        unset($this->fuel_injection_timing);
    }

    /**
     * Generated from protobuf field <code>optional int32 fuel_injection_timing = 267 [json_name = "fuel_injection_timing"];</code>
     * @param int $var
     * @return $this
     */
    public function setFuelInjectionTiming($var)
    {
        GPBUtil::checkInt32($var);
        $this->fuel_injection_timing = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 throttle_position_group = 268 [json_name = "throttle_position_group"];</code>
     * @return int
     */
    public function getThrottlePositionGroup()
    {
        return isset($this->throttle_position_group) ? $this->throttle_position_group : 0;
    }

    public function hasThrottlePositionGroup()
    {
        return isset($this->throttle_position_group);
    }

    public function clearThrottlePositionGroup()
    {
        unset($this->throttle_position_group);
    }

    /**
     * Generated from protobuf field <code>optional uint32 throttle_position_group = 268 [json_name = "throttle_position_group"];</code>
     * @param int $var
     * @return $this
     */
    public function setThrottlePositionGroup($var)
    {
        GPBUtil::checkUint32($var);
        $this->throttle_position_group = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 commanded_equivalence_r = 269 [json_name = "commanded_equivalence_r"];</code>
     * @return int
     */
    public function getCommandedEquivalenceR()
    {
        return isset($this->commanded_equivalence_r) ? $this->commanded_equivalence_r : 0;
    }

    public function hasCommandedEquivalenceR()
    {
        return isset($this->commanded_equivalence_r);
    }

    public function clearCommandedEquivalenceR()
    {
        unset($this->commanded_equivalence_r);
    }

    /**
     * Generated from protobuf field <code>optional uint32 commanded_equivalence_r = 269 [json_name = "commanded_equivalence_r"];</code>
     * @param int $var
     * @return $this
     */
    public function setCommandedEquivalenceR($var)
    {
        GPBUtil::checkUint32($var);
        $this->commanded_equivalence_r = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 intake_map_2_bytes = 270 [json_name = "intake_map_2_bytes"];</code>
     * @return int
     */
    public function getIntakeMap2Bytes()
    {
        return isset($this->intake_map_2_bytes) ? $this->intake_map_2_bytes : 0;
    }

    public function hasIntakeMap2Bytes()
    {
        return isset($this->intake_map_2_bytes);
    }

    public function clearIntakeMap2Bytes()
    {
        unset($this->intake_map_2_bytes);
    }

    /**
     * Generated from protobuf field <code>optional uint32 intake_map_2_bytes = 270 [json_name = "intake_map_2_bytes"];</code>
     * @param int $var
     * @return $this
     */
    public function setIntakeMap2Bytes($var)
    {
        GPBUtil::checkUint32($var);
        $this->intake_map_2_bytes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 hybrid_system_voltage = 271 [json_name = "hybrid_system_voltage"];</code>
     * @return int
     */
    public function getHybridSystemVoltage()
    {
        return isset($this->hybrid_system_voltage) ? $this->hybrid_system_voltage : 0;
    }

    public function hasHybridSystemVoltage()
    {
        return isset($this->hybrid_system_voltage);
    }

    public function clearHybridSystemVoltage()
    {
        unset($this->hybrid_system_voltage);
    }

    /**
     * Generated from protobuf field <code>optional uint32 hybrid_system_voltage = 271 [json_name = "hybrid_system_voltage"];</code>
     * @param int $var
     * @return $this
     */
    public function setHybridSystemVoltage($var)
    {
        GPBUtil::checkUint32($var);
        $this->hybrid_system_voltage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 hybrid_system_current = 272 [json_name = "hybrid_system_current"];</code>
     * @return int
     */
    public function getHybridSystemCurrent()
    {
        return isset($this->hybrid_system_current) ? $this->hybrid_system_current : 0;
    }

    public function hasHybridSystemCurrent()
    {
        return isset($this->hybrid_system_current);
    }

    public function clearHybridSystemCurrent()
    {
        unset($this->hybrid_system_current);
    }

    /**
     * Generated from protobuf field <code>optional int32 hybrid_system_current = 272 [json_name = "hybrid_system_current"];</code>
     * @param int $var
     * @return $this
     */
    public function setHybridSystemCurrent($var)
    {
        GPBUtil::checkInt32($var);
        $this->hybrid_system_current = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string fault_codes = 273 [json_name = "fault_codes"];</code>
     * @return string
     */
    public function getFaultCodes()
    {
        return isset($this->fault_codes) ? $this->fault_codes : '';
    }

    public function hasFaultCodes()
    {
        return isset($this->fault_codes);
    }

    public function clearFaultCodes()
    {
        unset($this->fault_codes);
    }

    /**
     * Generated from protobuf field <code>optional string fault_codes = 273 [json_name = "fault_codes"];</code>
     * @param string $var
     * @return $this
     */
    public function setFaultCodes($var)
    {
        GPBUtil::checkString($var, True);
        $this->fault_codes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool ecu_break_switch = 25 [json_name = "ecu_break_switch"];</code>
     * @return bool
     */
    public function getEcuBreakSwitch()
    {
        return isset($this->ecu_break_switch) ? $this->ecu_break_switch : false;
    }

    public function hasEcuBreakSwitch()
    {
        return isset($this->ecu_break_switch);
    }

    public function clearEcuBreakSwitch()
    {
        unset($this->ecu_break_switch);
    }

    /**
     * Generated from protobuf field <code>optional bool ecu_break_switch = 25 [json_name = "ecu_break_switch"];</code>
     * @param bool $var
     * @return $this
     */
    public function setEcuBreakSwitch($var)
    {
        GPBUtil::checkBool($var);
        $this->ecu_break_switch = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 coolant_temperature = 26 [json_name = "coolant_temperature"];</code>
     * @return int
     */
    public function getCoolantTemperature()
    {
        return isset($this->coolant_temperature) ? $this->coolant_temperature : 0;
    }

    public function hasCoolantTemperature()
    {
        return isset($this->coolant_temperature);
    }

    public function clearCoolantTemperature()
    {
        unset($this->coolant_temperature);
    }

    /**
     * Generated from protobuf field <code>optional int32 coolant_temperature = 26 [json_name = "coolant_temperature"];</code>
     * @param int $var
     * @return $this
     */
    public function setCoolantTemperature($var)
    {
        GPBUtil::checkInt32($var);
        $this->coolant_temperature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 number_of_dtc = 27 [json_name = "number_of_dtc"];</code>
     * @return int
     */
    public function getNumberOfDtc()
    {
        return isset($this->number_of_dtc) ? $this->number_of_dtc : 0;
    }

    public function hasNumberOfDtc()
    {
        return isset($this->number_of_dtc);
    }

    public function clearNumberOfDtc()
    {
        unset($this->number_of_dtc);
    }

    /**
     * Generated from protobuf field <code>optional uint32 number_of_dtc = 27 [json_name = "number_of_dtc"];</code>
     * @param int $var
     * @return $this
     */
    public function setNumberOfDtc($var)
    {
        GPBUtil::checkUint32($var);
        $this->number_of_dtc = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 engine_load = 28 [json_name = "engine_load"];</code>
     * @return int
     */
    public function getEngineLoad()
    {
        return isset($this->engine_load) ? $this->engine_load : 0;
    }

    public function hasEngineLoad()
    {
        return isset($this->engine_load);
    }

    public function clearEngineLoad()
    {
        unset($this->engine_load);
    }

    /**
     * Generated from protobuf field <code>optional uint32 engine_load = 28 [json_name = "engine_load"];</code>
     * @param int $var
     * @return $this
     */
    public function setEngineLoad($var)
    {
        GPBUtil::checkUint32($var);
        $this->engine_load = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 engine_rpm = 29 [json_name = "engine_rpm"];</code>
     * @return int
     */
    public function getEngineRpm()
    {
        return isset($this->engine_rpm) ? $this->engine_rpm : 0;
    }

    public function hasEngineRpm()
    {
        return isset($this->engine_rpm);
    }

    public function clearEngineRpm()
    {
        unset($this->engine_rpm);
    }

    /**
     * Generated from protobuf field <code>optional uint32 engine_rpm = 29 [json_name = "engine_rpm"];</code>
     * @param int $var
     * @return $this
     */
    public function setEngineRpm($var)
    {
        GPBUtil::checkUint32($var);
        $this->engine_rpm = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 fuel_level = 30 [json_name = "fuel_level"];</code>
     * @return int
     */
    public function getFuelLevel()
    {
        return isset($this->fuel_level) ? $this->fuel_level : 0;
    }

    public function hasFuelLevel()
    {
        return isset($this->fuel_level);
    }

    public function clearFuelLevel()
    {
        unset($this->fuel_level);
    }

    /**
     * Generated from protobuf field <code>optional uint32 fuel_level = 30 [json_name = "fuel_level"];</code>
     * @param int $var
     * @return $this
     */
    public function setFuelLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->fuel_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 fuel_rate = 31 [json_name = "fuel_rate"];</code>
     * @return int
     */
    public function getFuelRate()
    {
        return isset($this->fuel_rate) ? $this->fuel_rate : 0;
    }

    public function hasFuelRate()
    {
        return isset($this->fuel_rate);
    }

    public function clearFuelRate()
    {
        unset($this->fuel_rate);
    }

    /**
     * Generated from protobuf field <code>optional uint32 fuel_rate = 31 [json_name = "fuel_rate"];</code>
     * @param int $var
     * @return $this
     */
    public function setFuelRate($var)
    {
        GPBUtil::checkUint32($var);
        $this->fuel_rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 tire_pressure = 32 [json_name = "tire_pressure"];</code>
     * @return int
     */
    public function getTirePressure()
    {
        return isset($this->tire_pressure) ? $this->tire_pressure : 0;
    }

    public function hasTirePressure()
    {
        return isset($this->tire_pressure);
    }

    public function clearTirePressure()
    {
        unset($this->tire_pressure);
    }

    /**
     * Generated from protobuf field <code>optional uint32 tire_pressure = 32 [json_name = "tire_pressure"];</code>
     * @param int $var
     * @return $this
     */
    public function setTirePressure($var)
    {
        GPBUtil::checkUint32($var);
        $this->tire_pressure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 analog = 34 [json_name = "analog"];</code>
     * @return int
     */
    public function getAnalog()
    {
        return isset($this->analog) ? $this->analog : 0;
    }

    public function hasAnalog()
    {
        return isset($this->analog);
    }

    public function clearAnalog()
    {
        unset($this->analog);
    }

    /**
     * Generated from protobuf field <code>optional uint32 analog = 34 [json_name = "analog"];</code>
     * @param int $var
     * @return $this
     */
    public function setAnalog($var)
    {
        GPBUtil::checkUint32($var);
        $this->analog = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 oil = 35 [json_name = "oil"];</code>
     * @return int
     */
    public function getOil()
    {
        return isset($this->oil) ? $this->oil : 0;
    }

    public function hasOil()
    {
        return isset($this->oil);
    }

    public function clearOil()
    {
        unset($this->oil);
    }

    /**
     * Generated from protobuf field <code>optional uint32 oil = 35 [json_name = "oil"];</code>
     * @param int $var
     * @return $this
     */
    public function setOil($var)
    {
        GPBUtil::checkUint32($var);
        $this->oil = $var;

        return $this;
    }

}

