<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: packets/dataModel.proto

namespace Fatehan\Packet\DataModel;

use UnexpectedValueException;

/**
 * Protobuf type <code>com.fatehan.packets.Protocol</code>
 */
class Protocol
{
    /**
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>COBAN = 1;</code>
     */
    const COBAN = 1;
    /**
     * Generated from protobuf enum <code>COBAN_WR = 2;</code>
     */
    const COBAN_WR = 2;
    /**
     * Generated from protobuf enum <code>ACCURATE = 3;</code>
     */
    const ACCURATE = 3;
    /**
     * Generated from protobuf enum <code>A9 = 4;</code>
     */
    const A9 = 4;
    /**
     * Generated from protobuf enum <code>CONCOX = 5;</code>
     */
    const CONCOX = 5;
    /**
     * Generated from protobuf enum <code>DOLPHIN = 6;</code>
     */
    const DOLPHIN = 6;
    /**
     * Generated from protobuf enum <code>GT07 = 7;</code>
     */
    const GT07 = 7;
    /**
     * Generated from protobuf enum <code>JTT808 = 8;</code>
     */
    const JTT808 = 8;
    /**
     * Generated from protobuf enum <code>R16 = 9;</code>
     */
    const R16 = 9;
    /**
     * Generated from protobuf enum <code>R31 = 10;</code>
     */
    const R31 = 10;
    /**
     * Generated from protobuf enum <code>R56 = 11;</code>
     */
    const R56 = 11;
    /**
     * Generated from protobuf enum <code>S11 = 12;</code>
     */
    const S11 = 12;
    /**
     * Generated from protobuf enum <code>S15 = 13;</code>
     */
    const S15 = 13;
    /**
     * Generated from protobuf enum <code>SAYEH = 14;</code>
     */
    const SAYEH = 14;
    /**
     * Generated from protobuf enum <code>SINOTRACK = 15;</code>
     */
    const SINOTRACK = 15;
    /**
     * Generated from protobuf enum <code>TELTONIKA = 16;</code>
     */
    const TELTONIKA = 16;
    /**
     * Generated from protobuf enum <code>TOPIN = 17;</code>
     */
    const TOPIN = 17;
    /**
     * Generated from protobuf enum <code>WEFINDER = 18;</code>
     */
    const WEFINDER = 18;
    /**
     * Generated from protobuf enum <code>RUBTELLA = 19;</code>
     */
    const RUBTELLA = 19;
    /**
     * Generated from protobuf enum <code>LANDER = 20;</code>
     */
    const LANDER = 20;
    /**
     * Generated from protobuf enum <code>RAMMA = 21;</code>
     */
    const RAMMA = 21;
    /**
     * Generated from protobuf enum <code>SINERE = 22;</code>
     */
    const SINERE = 22;
    /**
     * Generated from protobuf enum <code>GALLO_SKY = 23;</code>
     */
    const GALLO_SKY = 23;
    /**
     * Generated from protobuf enum <code>GITINAMA = 24;</code>
     */
    const GITINAMA = 24;
    /**
     * Generated from protobuf enum <code>BCE = 25;</code>
     */
    const BCE = 25;
    /**
     * Generated from protobuf enum <code>TOP_FLY_TECH = 26;</code>
     */
    const TOP_FLY_TECH = 26;
    /**
     * Generated from protobuf enum <code>QUICK = 27;</code>
     */
    const QUICK = 27;
    /**
     * Generated from protobuf enum <code>RADSHID = 28;</code>
     */
    const RADSHID = 28;
    /**
     * Generated from protobuf enum <code>MEITRACK = 29;</code>
     */
    const MEITRACK = 29;
    /**
     * Generated from protobuf enum <code>GT30X = 30;</code>
     */
    const GT30X = 30;
    /**
     * Generated from protobuf enum <code>WP = 31;</code>
     */
    const WP = 31;
    /**
     * Generated from protobuf enum <code>SR03 = 32;</code>
     */
    const SR03 = 32;
    /**
     * Generated from protobuf enum <code>TELTONIKA650 = 33;</code>
     */
    const TELTONIKA650 = 33;
    /**
     * Generated from protobuf enum <code>SR04B = 34;</code>
     */
    const SR04B = 34;
    /**
     * Generated from protobuf enum <code>NAV_TELECOM = 35;</code>
     */
    const NAV_TELECOM = 35;
    /**
     * Generated from protobuf enum <code>VTRACK2 = 36;</code>
     */
    const VTRACK2 = 36;
    /**
     * Generated from protobuf enum <code>ET06L = 37;</code>
     */
    const ET06L = 37;
    /**
     * Generated from protobuf enum <code>ATN = 38;</code>
     */
    const ATN = 38;
    /**
     * Generated from protobuf enum <code>ARIO_AVL = 39;</code>
     */
    const ARIO_AVL = 39;
    /**
     * Generated from protobuf enum <code>HAMIGPS = 40;</code>
     */
    const HAMIGPS = 40;
    /**
     * Generated from protobuf enum <code>RUPTELLA = 41;</code>
     */
    const RUPTELLA = 41;
    /**
     * Generated from protobuf enum <code>ZINGJONG = 42;</code>
     */
    const ZINGJONG = 42;
    /**
     * Generated from protobuf enum <code>RADSHID_OLD = 43;</code>
     */
    const RADSHID_OLD = 43;
    /**
     * Generated from protobuf enum <code>COBAN_2025 = 44;</code>
     */
    const COBAN_2025 = 44;
    /**
     * Generated from protobuf enum <code>S200 = 45;</code>
     */
    const S200 = 45;
    /**
     * Generated from protobuf enum <code>S250 = 46;</code>
     */
    const S250 = 46;
    /**
     * Generated from protobuf enum <code>SR17 = 47;</code>
     */
    const SR17 = 47;
    /**
     * Generated from protobuf enum <code>ARIO_4G_AVL = 48;</code>
     */
    const ARIO_4G_AVL = 48;
    /**
     * Generated from protobuf enum <code>JT701 = 49;</code>
     */
    const JT701 = 49;
    /**
     * Generated from protobuf enum <code>ET804 = 50;</code>
     */
    const ET804 = 50;
    /**
     * Generated from protobuf enum <code>GF900 = 51;</code>
     */
    const GF900 = 51;
    /**
     * Generated from protobuf enum <code>XEXUN = 52;</code>
     */
    const XEXUN = 52;

    private static $valueToName = [
        self::UNKNOWN => 'UNKNOWN',
        self::COBAN => 'COBAN',
        self::COBAN_WR => 'COBAN_WR',
        self::ACCURATE => 'ACCURATE',
        self::A9 => 'A9',
        self::CONCOX => 'CONCOX',
        self::DOLPHIN => 'DOLPHIN',
        self::GT07 => 'GT07',
        self::JTT808 => 'JTT808',
        self::R16 => 'R16',
        self::R31 => 'R31',
        self::R56 => 'R56',
        self::S11 => 'S11',
        self::S15 => 'S15',
        self::SAYEH => 'SAYEH',
        self::SINOTRACK => 'SINOTRACK',
        self::TELTONIKA => 'TELTONIKA',
        self::TOPIN => 'TOPIN',
        self::WEFINDER => 'WEFINDER',
        self::RUBTELLA => 'RUBTELLA',
        self::LANDER => 'LANDER',
        self::RAMMA => 'RAMMA',
        self::SINERE => 'SINERE',
        self::GALLO_SKY => 'GALLO_SKY',
        self::GITINAMA => 'GITINAMA',
        self::BCE => 'BCE',
        self::TOP_FLY_TECH => 'TOP_FLY_TECH',
        self::QUICK => 'QUICK',
        self::RADSHID => 'RADSHID',
        self::MEITRACK => 'MEITRACK',
        self::GT30X => 'GT30X',
        self::WP => 'WP',
        self::SR03 => 'SR03',
        self::TELTONIKA650 => 'TELTONIKA650',
        self::SR04B => 'SR04B',
        self::NAV_TELECOM => 'NAV_TELECOM',
        self::VTRACK2 => 'VTRACK2',
        self::ET06L => 'ET06L',
        self::ATN => 'ATN',
        self::ARIO_AVL => 'ARIO_AVL',
        self::HAMIGPS => 'HAMIGPS',
        self::RUPTELLA => 'RUPTELLA',
        self::ZINGJONG => 'ZINGJONG',
        self::RADSHID_OLD => 'RADSHID_OLD',
        self::COBAN_2025 => 'COBAN_2025',
        self::S200 => 'S200',
        self::S250 => 'S250',
        self::SR17 => 'SR17',
        self::ARIO_4G_AVL => 'ARIO_4G_AVL',
        self::JT701 => 'JT701',
        self::ET804 => 'ET804',
        self::GF900 => 'GF900',
        self::XEXUN => 'XEXUN',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

