<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: identities/authentication.proto

namespace Fatehan\Identity\Authentication;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * auth state model
 *
 * Generated from protobuf message <code>com.fatehan.identities.AuthState</code>
 */
class AuthState extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.com.fatehan.identities.AuthenticationStrategy strategy = 1 [json_name = "strategy"];</code>
     */
    protected $strategy = null;
    /**
     * Generated from protobuf field <code>.com.fatehan.identities.AuthenticationMethod authentication = 2 [json_name = "authentication"];</code>
     */
    protected $authentication = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp authenticated = 3 [json_name = "authenticated"];</code>
     */
    protected $authenticated = null;
    /**
     * Generated from protobuf field <code>.com.fatehan.identities.AuthenticationMethod verification = 4 [json_name = "verification"];</code>
     */
    protected $verification = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp verified = 5 [json_name = "verified"];</code>
     */
    protected $verified = null;
    /**
     * Generated from protobuf field <code>string csrf_token = 6 [json_name = "csrf"];</code>
     */
    protected $csrf_token = '';
    /**
     * Generated from protobuf field <code>.com.fatehan.identities.Identity identity = 7 [json_name = "identity"];</code>
     */
    protected $identity = null;
    /**
     * Generated from protobuf field <code>.com.fatehan.identities.Identity google = 8 [json_name = "google"];</code>
     */
    protected $google = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Fatehan\Identity\Authentication\AuthenticationStrategy $strategy
     *     @type int $authentication
     *     @type \Google\Protobuf\Timestamp $authenticated
     *     @type int $verification
     *     @type \Google\Protobuf\Timestamp $verified
     *     @type string $csrf_token
     *     @type \Fatehan\Identity\Authentication\Identity $identity
     *     @type \Fatehan\Identity\Authentication\Identity $google
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Identity\Authentication\MetaData\Authentication::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.identities.AuthenticationStrategy strategy = 1 [json_name = "strategy"];</code>
     * @return \Fatehan\Identity\Authentication\AuthenticationStrategy|null
     */
    public function getStrategy()
    {
        return $this->strategy;
    }

    public function hasStrategy()
    {
        return isset($this->strategy);
    }

    public function clearStrategy()
    {
        unset($this->strategy);
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.identities.AuthenticationStrategy strategy = 1 [json_name = "strategy"];</code>
     * @param \Fatehan\Identity\Authentication\AuthenticationStrategy $var
     * @return $this
     */
    public function setStrategy(\Fatehan\Identity\Authentication\AuthenticationStrategy|null $var)
    {
        $this->strategy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.identities.AuthenticationMethod authentication = 2 [json_name = "authentication"];</code>
     * @return int one of the values in {@see \Fatehan\Identity\Authentication\AuthenticationMethod}
     */
    public function getAuthentication()
    {
        return $this->authentication;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.identities.AuthenticationMethod authentication = 2 [json_name = "authentication"];</code>
     * @param int $var one of the values in {@see \Fatehan\Identity\Authentication\AuthenticationMethod}
     * @return $this
     */
    public function setAuthentication(int $var)
    {
        GPBUtil::checkEnum($var, \Fatehan\Identity\Authentication\AuthenticationMethod::class);
        $this->authentication = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp authenticated = 3 [json_name = "authenticated"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getAuthenticated()
    {
        return $this->authenticated;
    }

    public function hasAuthenticated()
    {
        return isset($this->authenticated);
    }

    public function clearAuthenticated()
    {
        unset($this->authenticated);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp authenticated = 3 [json_name = "authenticated"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setAuthenticated(\Google\Protobuf\Timestamp|null $var)
    {
        $this->authenticated = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.identities.AuthenticationMethod verification = 4 [json_name = "verification"];</code>
     * @return int one of the values in {@see \Fatehan\Identity\Authentication\AuthenticationMethod}
     */
    public function getVerification()
    {
        return $this->verification;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.identities.AuthenticationMethod verification = 4 [json_name = "verification"];</code>
     * @param int $var one of the values in {@see \Fatehan\Identity\Authentication\AuthenticationMethod}
     * @return $this
     */
    public function setVerification(int $var)
    {
        GPBUtil::checkEnum($var, \Fatehan\Identity\Authentication\AuthenticationMethod::class);
        $this->verification = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp verified = 5 [json_name = "verified"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getVerified()
    {
        return $this->verified;
    }

    public function hasVerified()
    {
        return isset($this->verified);
    }

    public function clearVerified()
    {
        unset($this->verified);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp verified = 5 [json_name = "verified"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setVerified(\Google\Protobuf\Timestamp|null $var)
    {
        $this->verified = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string csrf_token = 6 [json_name = "csrf"];</code>
     * @return string
     */
    public function getCsrfToken()
    {
        return $this->csrf_token;
    }

    /**
     * Generated from protobuf field <code>string csrf_token = 6 [json_name = "csrf"];</code>
     * @param string $var
     * @return $this
     */
    public function setCsrfToken(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->csrf_token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.identities.Identity identity = 7 [json_name = "identity"];</code>
     * @return \Fatehan\Identity\Authentication\Identity|null
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    public function hasIdentity()
    {
        return isset($this->identity);
    }

    public function clearIdentity()
    {
        unset($this->identity);
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.identities.Identity identity = 7 [json_name = "identity"];</code>
     * @param \Fatehan\Identity\Authentication\Identity $var
     * @return $this
     */
    public function setIdentity(\Fatehan\Identity\Authentication\Identity|null $var)
    {
        $this->identity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.identities.Identity google = 8 [json_name = "google"];</code>
     * @return \Fatehan\Identity\Authentication\Identity|null
     */
    public function getGoogle()
    {
        return $this->google;
    }

    public function hasGoogle()
    {
        return isset($this->google);
    }

    public function clearGoogle()
    {
        unset($this->google);
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.identities.Identity google = 8 [json_name = "google"];</code>
     * @param \Fatehan\Identity\Authentication\Identity $var
     * @return $this
     */
    public function setGoogle(\Fatehan\Identity\Authentication\Identity|null $var)
    {
        $this->google = $var;

        return $this;
    }

}

