<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: identities/authentication.proto

namespace Fatehan\Identity\Authentication;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * auth strategy config
 *
 * Generated from protobuf message <code>com.fatehan.identities.AuthenticationStrategy</code>
 */
class AuthenticationStrategy extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .com.fatehan.identities.AuthenticationMethod authentication = 1 [json_name = "authentication"];</code>
     */
    private $authentication;
    /**
     * Generated from protobuf field <code>.com.fatehan.identities.AuthenticationMethod verification = 2 [json_name = "verification"];</code>
     */
    protected $verification = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Duration verification_timeout = 3 [json_name = "verification_timeout"];</code>
     */
    protected $verification_timeout = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[] $authentication
     *     @type int $verification
     *     @type \Google\Protobuf\Duration $verification_timeout
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Identity\Authentication\MetaData\Authentication::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.identities.AuthenticationMethod authentication = 1 [json_name = "authentication"];</code>
     * @return RepeatedField<int>
     */
    public function getAuthentication()
    {
        return $this->authentication;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.identities.AuthenticationMethod authentication = 1 [json_name = "authentication"];</code>
     * @param int[] $var
     * @return $this
     */
    public function setAuthentication($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Fatehan\Identity\Authentication\AuthenticationMethod::class);
        $this->authentication = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.identities.AuthenticationMethod verification = 2 [json_name = "verification"];</code>
     * @return int
     */
    public function getVerification()
    {
        return $this->verification;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.identities.AuthenticationMethod verification = 2 [json_name = "verification"];</code>
     * @param int $var
     * @return $this
     */
    public function setVerification($var)
    {
        GPBUtil::checkEnum($var, \Fatehan\Identity\Authentication\AuthenticationMethod::class);
        $this->verification = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration verification_timeout = 3 [json_name = "verification_timeout"];</code>
     * @return \Google\Protobuf\Duration|null
     */
    public function getVerificationTimeout()
    {
        return $this->verification_timeout;
    }

    public function hasVerificationTimeout()
    {
        return isset($this->verification_timeout);
    }

    public function clearVerificationTimeout()
    {
        unset($this->verification_timeout);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Duration verification_timeout = 3 [json_name = "verification_timeout"];</code>
     * @param \Google\Protobuf\Duration $var
     * @return $this
     */
    public function setVerificationTimeout($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Duration::class);
        $this->verification_timeout = $var;

        return $this;
    }

}

