<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identities/authentication.proto

namespace Fatehan\Identity\Authentication;

if (false) {
    /**
     * This class is deprecated. Use Fatehan\Identity\Authentication\WebhookEvent\Logout instead.
     * @deprecated
     */
    class WebhookEvent_Logout {}
}
class_exists(WebhookEvent\Logout::class);
@trigger_error('Fatehan\Identity\Authentication\WebhookEvent_Logout is deprecated and will be removed in the next major release. Use Fatehan\Identity\Authentication\WebhookEvent\Logout instead', E_USER_DEPRECATED);

