<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: activities/camera.proto

namespace Fatehan\Activities\Camera\CameraEvent;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.activities.CameraEvent.ReceiveTimeout</code>
 */
class ReceiveTimeout extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string stream = 1 [json_name = "stream"];</code>
     */
    protected $stream = null;
    /**
     * Generated from protobuf field <code>optional sint32 protocol = 2 [json_name = "protocol"];</code>
     */
    protected $protocol = null;
    /**
     * Generated from protobuf field <code>optional string remote_addr = 3 [json_name = "remote_addr"];</code>
     */
    protected $remote_addr = null;
    /**
     * Generated from protobuf field <code>optional string sink = 4 [json_name = "sink"];</code>
     */
    protected $sink = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $stream
     *     @type int $protocol
     *     @type string $remote_addr
     *     @type string $sink
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Activities\Camera\MetaData\Camera::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string stream = 1 [json_name = "stream"];</code>
     * @return string
     */
    public function getStream()
    {
        return isset($this->stream) ? $this->stream : '';
    }

    public function hasStream()
    {
        return isset($this->stream);
    }

    public function clearStream()
    {
        unset($this->stream);
    }

    /**
     * Generated from protobuf field <code>optional string stream = 1 [json_name = "stream"];</code>
     * @param string $var
     * @return $this
     */
    public function setStream($var)
    {
        GPBUtil::checkString($var, True);
        $this->stream = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional sint32 protocol = 2 [json_name = "protocol"];</code>
     * @return int
     */
    public function getProtocol()
    {
        return isset($this->protocol) ? $this->protocol : 0;
    }

    public function hasProtocol()
    {
        return isset($this->protocol);
    }

    public function clearProtocol()
    {
        unset($this->protocol);
    }

    /**
     * Generated from protobuf field <code>optional sint32 protocol = 2 [json_name = "protocol"];</code>
     * @param int $var
     * @return $this
     */
    public function setProtocol($var)
    {
        GPBUtil::checkInt32($var);
        $this->protocol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string remote_addr = 3 [json_name = "remote_addr"];</code>
     * @return string
     */
    public function getRemoteAddr()
    {
        return isset($this->remote_addr) ? $this->remote_addr : '';
    }

    public function hasRemoteAddr()
    {
        return isset($this->remote_addr);
    }

    public function clearRemoteAddr()
    {
        unset($this->remote_addr);
    }

    /**
     * Generated from protobuf field <code>optional string remote_addr = 3 [json_name = "remote_addr"];</code>
     * @param string $var
     * @return $this
     */
    public function setRemoteAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->remote_addr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string sink = 4 [json_name = "sink"];</code>
     * @return string
     */
    public function getSink()
    {
        return isset($this->sink) ? $this->sink : '';
    }

    public function hasSink()
    {
        return isset($this->sink);
    }

    public function clearSink()
    {
        unset($this->sink);
    }

    /**
     * Generated from protobuf field <code>optional string sink = 4 [json_name = "sink"];</code>
     * @param string $var
     * @return $this
     */
    public function setSink($var)
    {
        GPBUtil::checkString($var, True);
        $this->sink = $var;

        return $this;
    }

}

