<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/api.proto

namespace Fatehan\Service;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.fatehan.services.AreaSummaryReviewRequest</code>
 */
class AreaSummaryReviewRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp started_at = 1 [json_name = "started_at"];</code>
     */
    protected $started_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp finished_at = 2 [json_name = "finished_at"];</code>
     */
    protected $finished_at = null;
    /**
     * Generated from protobuf field <code>.com.fatehan.services.AreaSummaryReviewRequest.ScopeEnum scope = 3 [json_name = "scope"];</code>
     */
    protected $scope = 0;
    /**
     * Generated from protobuf field <code>repeated uint64 area_ids = 6 [json_name = "area_ids"];</code>
     */
    private $area_ids;
    /**
     * Generated from protobuf field <code>repeated uint64 device_ids = 7 [json_name = "device_ids"];</code>
     */
    private $device_ids;
    /**
     * Generated from protobuf field <code>uint64 organization_id = 8;</code>
     */
    protected $organization_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $started_at
     *     @type \Google\Protobuf\Timestamp $finished_at
     *     @type int $scope
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $area_ids
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $device_ids
     *     @type int|string $organization_id
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Service\MetaData\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp started_at = 1 [json_name = "started_at"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getStartedAt()
    {
        return $this->started_at;
    }

    public function hasStartedAt()
    {
        return isset($this->started_at);
    }

    public function clearStartedAt()
    {
        unset($this->started_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp started_at = 1 [json_name = "started_at"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setStartedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->started_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp finished_at = 2 [json_name = "finished_at"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getFinishedAt()
    {
        return $this->finished_at;
    }

    public function hasFinishedAt()
    {
        return isset($this->finished_at);
    }

    public function clearFinishedAt()
    {
        unset($this->finished_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp finished_at = 2 [json_name = "finished_at"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setFinishedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->finished_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.services.AreaSummaryReviewRequest.ScopeEnum scope = 3 [json_name = "scope"];</code>
     * @return int
     */
    public function getScope()
    {
        return $this->scope;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.services.AreaSummaryReviewRequest.ScopeEnum scope = 3 [json_name = "scope"];</code>
     * @param int $var
     * @return $this
     */
    public function setScope($var)
    {
        GPBUtil::checkEnum($var, \Fatehan\Service\AreaSummaryReviewRequest\ScopeEnum::class);
        $this->scope = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 area_ids = 6 [json_name = "area_ids"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAreaIds()
    {
        return $this->area_ids;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 area_ids = 6 [json_name = "area_ids"];</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAreaIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->area_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 device_ids = 7 [json_name = "device_ids"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDeviceIds()
    {
        return $this->device_ids;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 device_ids = 7 [json_name = "device_ids"];</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDeviceIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->device_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 organization_id = 8;</code>
     * @return int|string
     */
    public function getOrganizationId()
    {
        return $this->organization_id;
    }

    /**
     * Generated from protobuf field <code>uint64 organization_id = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrganizationId($var)
    {
        GPBUtil::checkUint64($var);
        $this->organization_id = $var;

        return $this;
    }

}

