<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/api.proto

namespace Fatehan\Service;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.services.CommandActionListRequest</code>
 */
class CommandActionListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 tracker_id = 1;</code>
     */
    protected $tracker_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $tracker_id
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Service\MetaData\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 tracker_id = 1;</code>
     * @return int|string
     */
    public function getTrackerId()
    {
        return $this->tracker_id;
    }

    /**
     * Generated from protobuf field <code>uint64 tracker_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTrackerId($var)
    {
        GPBUtil::checkUint64($var);
        $this->tracker_id = $var;

        return $this;
    }

}

