<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/api.proto

namespace Fatehan\Service;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.services.CommandActionModel</code>
 */
class CommandActionModel extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 command_id = 1 [json_name = "command_id"];</code>
     */
    protected $command_id = 0;
    /**
     * Generated from protobuf field <code>uint64 tracker_id = 2 [json_name = "tracker_id"];</code>
     */
    protected $tracker_id = 0;
    /**
     * Generated from protobuf field <code>uint64 command_action_id = 3 [json_name = "command_action_id"];</code>
     */
    protected $command_action_id = 0;
    /**
     * Generated from protobuf field <code>string command_name = 4 [json_name = "command_name"];</code>
     */
    protected $command_name = '';
    /**
     * Generated from protobuf field <code>string action_name = 5 [json_name = "action_name"];</code>
     */
    protected $action_name = '';
    /**
     * Generated from protobuf field <code>string action_description = 6 [json_name = "action_description"];</code>
     */
    protected $action_description = '';
    /**
     * Generated from protobuf field <code>string action_picture = 7 [json_name = "action_picture"];</code>
     */
    protected $action_picture = '';
    /**
     * Generated from protobuf field <code>optional .com.fatehan.packets.CommandFormat sms = 8 [json_name = "sms"];</code>
     */
    protected $sms = null;
    /**
     * Generated from protobuf field <code>optional .com.fatehan.packets.CommandFormat gprs = 9 [json_name = "gprs"];</code>
     */
    protected $gprs = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $command_id
     *     @type int|string $tracker_id
     *     @type int|string $command_action_id
     *     @type string $command_name
     *     @type string $action_name
     *     @type string $action_description
     *     @type string $action_picture
     *     @type \Fatehan\Packet\Message\CommandFormat $sms
     *     @type \Fatehan\Packet\Message\CommandFormat $gprs
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Service\MetaData\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 command_id = 1 [json_name = "command_id"];</code>
     * @return int|string
     */
    public function getCommandId()
    {
        return $this->command_id;
    }

    /**
     * Generated from protobuf field <code>uint64 command_id = 1 [json_name = "command_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setCommandId($var)
    {
        GPBUtil::checkUint64($var);
        $this->command_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 tracker_id = 2 [json_name = "tracker_id"];</code>
     * @return int|string
     */
    public function getTrackerId()
    {
        return $this->tracker_id;
    }

    /**
     * Generated from protobuf field <code>uint64 tracker_id = 2 [json_name = "tracker_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setTrackerId($var)
    {
        GPBUtil::checkUint64($var);
        $this->tracker_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 command_action_id = 3 [json_name = "command_action_id"];</code>
     * @return int|string
     */
    public function getCommandActionId()
    {
        return $this->command_action_id;
    }

    /**
     * Generated from protobuf field <code>uint64 command_action_id = 3 [json_name = "command_action_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setCommandActionId($var)
    {
        GPBUtil::checkUint64($var);
        $this->command_action_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string command_name = 4 [json_name = "command_name"];</code>
     * @return string
     */
    public function getCommandName()
    {
        return $this->command_name;
    }

    /**
     * Generated from protobuf field <code>string command_name = 4 [json_name = "command_name"];</code>
     * @param string $var
     * @return $this
     */
    public function setCommandName($var)
    {
        GPBUtil::checkString($var, True);
        $this->command_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string action_name = 5 [json_name = "action_name"];</code>
     * @return string
     */
    public function getActionName()
    {
        return $this->action_name;
    }

    /**
     * Generated from protobuf field <code>string action_name = 5 [json_name = "action_name"];</code>
     * @param string $var
     * @return $this
     */
    public function setActionName($var)
    {
        GPBUtil::checkString($var, True);
        $this->action_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string action_description = 6 [json_name = "action_description"];</code>
     * @return string
     */
    public function getActionDescription()
    {
        return $this->action_description;
    }

    /**
     * Generated from protobuf field <code>string action_description = 6 [json_name = "action_description"];</code>
     * @param string $var
     * @return $this
     */
    public function setActionDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->action_description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string action_picture = 7 [json_name = "action_picture"];</code>
     * @return string
     */
    public function getActionPicture()
    {
        return $this->action_picture;
    }

    /**
     * Generated from protobuf field <code>string action_picture = 7 [json_name = "action_picture"];</code>
     * @param string $var
     * @return $this
     */
    public function setActionPicture($var)
    {
        GPBUtil::checkString($var, True);
        $this->action_picture = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .com.fatehan.packets.CommandFormat sms = 8 [json_name = "sms"];</code>
     * @return \Fatehan\Packet\Message\CommandFormat|null
     */
    public function getSms()
    {
        return $this->sms;
    }

    public function hasSms()
    {
        return isset($this->sms);
    }

    public function clearSms()
    {
        unset($this->sms);
    }

    /**
     * Generated from protobuf field <code>optional .com.fatehan.packets.CommandFormat sms = 8 [json_name = "sms"];</code>
     * @param \Fatehan\Packet\Message\CommandFormat $var
     * @return $this
     */
    public function setSms($var)
    {
        GPBUtil::checkMessage($var, \Fatehan\Packet\Message\CommandFormat::class);
        $this->sms = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .com.fatehan.packets.CommandFormat gprs = 9 [json_name = "gprs"];</code>
     * @return \Fatehan\Packet\Message\CommandFormat|null
     */
    public function getGprs()
    {
        return $this->gprs;
    }

    public function hasGprs()
    {
        return isset($this->gprs);
    }

    public function clearGprs()
    {
        unset($this->gprs);
    }

    /**
     * Generated from protobuf field <code>optional .com.fatehan.packets.CommandFormat gprs = 9 [json_name = "gprs"];</code>
     * @param \Fatehan\Packet\Message\CommandFormat $var
     * @return $this
     */
    public function setGprs($var)
    {
        GPBUtil::checkMessage($var, \Fatehan\Packet\Message\CommandFormat::class);
        $this->gprs = $var;

        return $this;
    }

}

