<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/api.proto

namespace Fatehan\Service;

if (false) {
    /**
     * This class is deprecated. Use Fatehan\Service\DashboardIndividualResponse\Environmental instead.
     * @deprecated
     */
    class DashboardIndividualResponse_Environmental {}
}
class_exists(DashboardIndividualResponse\Environmental::class);
@trigger_error('Fatehan\Service\DashboardIndividualResponse_Environmental is deprecated and will be removed in the next major release. Use Fatehan\Service\DashboardIndividualResponse\Environmental instead', E_USER_DEPRECATED);

