<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/api.proto

namespace Fatehan\Service;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.services.FilterScope</code>
 */
class FilterScope extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string filter_type = 1 [json_name = "filterType"];</code>
     */
    protected $filter_type = '';
    /**
     * text filter type only
     *
     * Generated from protobuf field <code>optional string operator = 2 [json_name = "operator"];</code>
     */
    protected $operator = null;
    /**
     * text filter type only
     *
     * Generated from protobuf field <code>repeated .com.fatehan.services.FilterConditions conditions = 3 [json_name = "conditions"];</code>
     */
    private $conditions;
    /**
     * text filter type only
     *
     * Generated from protobuf field <code>optional string filter = 7 [json_name = "filter"];</code>
     */
    protected $filter = null;
    /**
     * date filter type only
     *
     * Generated from protobuf field <code>optional string date_from = 4 [json_name = "dateFrom"];</code>
     */
    protected $date_from = null;
    /**
     * date filter type only
     *
     * Generated from protobuf field <code>optional string date_to = 5 [json_name = "dateTo"];</code>
     */
    protected $date_to = null;
    /**
     * date, text filters type
     *
     * Generated from protobuf field <code>optional string type = 6 [json_name = "type"];</code>
     */
    protected $type = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $filter_type
     *     @type string $operator
     *           text filter type only
     *     @type \Fatehan\Service\FilterConditions[] $conditions
     *           text filter type only
     *     @type string $filter
     *           text filter type only
     *     @type string $date_from
     *           date filter type only
     *     @type string $date_to
     *           date filter type only
     *     @type string $type
     *           date, text filters type
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Service\MetaData\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string filter_type = 1 [json_name = "filterType"];</code>
     * @return string
     */
    public function getFilterType()
    {
        return $this->filter_type;
    }

    /**
     * Generated from protobuf field <code>string filter_type = 1 [json_name = "filterType"];</code>
     * @param string $var
     * @return $this
     */
    public function setFilterType($var)
    {
        GPBUtil::checkString($var, True);
        $this->filter_type = $var;

        return $this;
    }

    /**
     * text filter type only
     *
     * Generated from protobuf field <code>optional string operator = 2 [json_name = "operator"];</code>
     * @return string
     */
    public function getOperator()
    {
        return isset($this->operator) ? $this->operator : '';
    }

    public function hasOperator()
    {
        return isset($this->operator);
    }

    public function clearOperator()
    {
        unset($this->operator);
    }

    /**
     * text filter type only
     *
     * Generated from protobuf field <code>optional string operator = 2 [json_name = "operator"];</code>
     * @param string $var
     * @return $this
     */
    public function setOperator($var)
    {
        GPBUtil::checkString($var, True);
        $this->operator = $var;

        return $this;
    }

    /**
     * text filter type only
     *
     * Generated from protobuf field <code>repeated .com.fatehan.services.FilterConditions conditions = 3 [json_name = "conditions"];</code>
     * @return RepeatedField<\Fatehan\Service\FilterConditions>
     */
    public function getConditions()
    {
        return $this->conditions;
    }

    /**
     * text filter type only
     *
     * Generated from protobuf field <code>repeated .com.fatehan.services.FilterConditions conditions = 3 [json_name = "conditions"];</code>
     * @param \Fatehan\Service\FilterConditions[] $var
     * @return $this
     */
    public function setConditions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fatehan\Service\FilterConditions::class);
        $this->conditions = $arr;

        return $this;
    }

    /**
     * text filter type only
     *
     * Generated from protobuf field <code>optional string filter = 7 [json_name = "filter"];</code>
     * @return string
     */
    public function getFilter()
    {
        return isset($this->filter) ? $this->filter : '';
    }

    public function hasFilter()
    {
        return isset($this->filter);
    }

    public function clearFilter()
    {
        unset($this->filter);
    }

    /**
     * text filter type only
     *
     * Generated from protobuf field <code>optional string filter = 7 [json_name = "filter"];</code>
     * @param string $var
     * @return $this
     */
    public function setFilter($var)
    {
        GPBUtil::checkString($var, True);
        $this->filter = $var;

        return $this;
    }

    /**
     * date filter type only
     *
     * Generated from protobuf field <code>optional string date_from = 4 [json_name = "dateFrom"];</code>
     * @return string
     */
    public function getDateFrom()
    {
        return isset($this->date_from) ? $this->date_from : '';
    }

    public function hasDateFrom()
    {
        return isset($this->date_from);
    }

    public function clearDateFrom()
    {
        unset($this->date_from);
    }

    /**
     * date filter type only
     *
     * Generated from protobuf field <code>optional string date_from = 4 [json_name = "dateFrom"];</code>
     * @param string $var
     * @return $this
     */
    public function setDateFrom($var)
    {
        GPBUtil::checkString($var, True);
        $this->date_from = $var;

        return $this;
    }

    /**
     * date filter type only
     *
     * Generated from protobuf field <code>optional string date_to = 5 [json_name = "dateTo"];</code>
     * @return string
     */
    public function getDateTo()
    {
        return isset($this->date_to) ? $this->date_to : '';
    }

    public function hasDateTo()
    {
        return isset($this->date_to);
    }

    public function clearDateTo()
    {
        unset($this->date_to);
    }

    /**
     * date filter type only
     *
     * Generated from protobuf field <code>optional string date_to = 5 [json_name = "dateTo"];</code>
     * @param string $var
     * @return $this
     */
    public function setDateTo($var)
    {
        GPBUtil::checkString($var, True);
        $this->date_to = $var;

        return $this;
    }

    /**
     * date, text filters type
     *
     * Generated from protobuf field <code>optional string type = 6 [json_name = "type"];</code>
     * @return string
     */
    public function getType()
    {
        return isset($this->type) ? $this->type : '';
    }

    public function hasType()
    {
        return isset($this->type);
    }

    public function clearType()
    {
        unset($this->type);
    }

    /**
     * date, text filters type
     *
     * Generated from protobuf field <code>optional string type = 6 [json_name = "type"];</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

}

