<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/api.proto

namespace Fatehan\Service;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.fatehan.services.IoResponse</code>
 */
class IoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 cost = 1 [json_name = "cost"];</code>
     */
    protected $cost = 0;
    /**
     * Generated from protobuf field <code>uint32 records = 2 [json_name = "records"];</code>
     */
    protected $records = 0;
    /**
     * Generated from protobuf field <code>repeated .com.fatehan.devices.SystemIo ios = 3 [json_name = "ios"];</code>
     */
    private $ios;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $cost
     *     @type int $records
     *     @type \Fatehan\Device\SystemIo[]|\Google\Protobuf\Internal\RepeatedField $ios
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Service\MetaData\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 cost = 1 [json_name = "cost"];</code>
     * @return int
     */
    public function getCost()
    {
        return $this->cost;
    }

    /**
     * Generated from protobuf field <code>uint32 cost = 1 [json_name = "cost"];</code>
     * @param int $var
     * @return $this
     */
    public function setCost($var)
    {
        GPBUtil::checkUint32($var);
        $this->cost = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 records = 2 [json_name = "records"];</code>
     * @return int
     */
    public function getRecords()
    {
        return $this->records;
    }

    /**
     * Generated from protobuf field <code>uint32 records = 2 [json_name = "records"];</code>
     * @param int $var
     * @return $this
     */
    public function setRecords($var)
    {
        GPBUtil::checkUint32($var);
        $this->records = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.devices.SystemIo ios = 3 [json_name = "ios"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIos()
    {
        return $this->ios;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.devices.SystemIo ios = 3 [json_name = "ios"];</code>
     * @param \Fatehan\Device\SystemIo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fatehan\Device\SystemIo::class);
        $this->ios = $arr;

        return $this;
    }

}

