<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/api.proto

namespace Fatehan\Service;

if (false) {
    /**
     * This class is deprecated. Use Fatehan\Service\MaintenanceIndexResponse\Statistics instead.
     * @deprecated
     */
    class MaintenanceIndexResponse_Statistics {}
}
class_exists(MaintenanceIndexResponse\Statistics::class);
@trigger_error('Fatehan\Service\MaintenanceIndexResponse_Statistics is deprecated and will be removed in the next major release. Use Fatehan\Service\MaintenanceIndexResponse\Statistics instead', E_USER_DEPRECATED);

