<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/api.proto

namespace Fatehan\Service;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.services.NotificationMediaResponse</code>
 */
class NotificationMediaResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .com.fatehan.models.Gallery galleries = 1;</code>
     */
    private $galleries;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Fatehan\Models\Gallery[] $galleries
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Service\MetaData\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.models.Gallery galleries = 1;</code>
     * @return RepeatedField<\Fatehan\Models\Gallery>
     */
    public function getGalleries()
    {
        return $this->galleries;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.models.Gallery galleries = 1;</code>
     * @param \Fatehan\Models\Gallery[] $var
     * @return $this
     */
    public function setGalleries(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fatehan\Models\Gallery::class);
        $this->galleries = $arr;

        return $this;
    }

}

