<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/api.proto

namespace Fatehan\Service;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.fatehan.services.NotificationMediaResponse</code>
 */
class NotificationMediaResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .com.fatehan.models.Gallery galleries = 1;</code>
     */
    private $galleries;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Fatehan\Models\Gallery>|\Google\Protobuf\Internal\RepeatedField $galleries
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Service\MetaData\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.models.Gallery galleries = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGalleries()
    {
        return $this->galleries;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.models.Gallery galleries = 1;</code>
     * @param array<\Fatehan\Models\Gallery>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGalleries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fatehan\Models\Gallery::class);
        $this->galleries = $arr;

        return $this;
    }

}

