<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/api.proto

namespace Fatehan\Service;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.fatehan.services.PrepareSendUserNotificationRequest</code>
 */
class PrepareSendUserNotificationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 organization_id = 1 [json_name = "organization_id"];</code>
     */
    protected $organization_id = 0;
    /**
     * Generated from protobuf field <code>bool send_to_children = 2 [json_name = "send_to_children"];</code>
     */
    protected $send_to_children = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $organization_id
     *     @type bool $send_to_children
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Service\MetaData\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 organization_id = 1 [json_name = "organization_id"];</code>
     * @return int|string
     */
    public function getOrganizationId()
    {
        return $this->organization_id;
    }

    /**
     * Generated from protobuf field <code>uint64 organization_id = 1 [json_name = "organization_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrganizationId($var)
    {
        GPBUtil::checkUint64($var);
        $this->organization_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool send_to_children = 2 [json_name = "send_to_children"];</code>
     * @return bool
     */
    public function getSendToChildren()
    {
        return $this->send_to_children;
    }

    /**
     * Generated from protobuf field <code>bool send_to_children = 2 [json_name = "send_to_children"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSendToChildren($var)
    {
        GPBUtil::checkBool($var);
        $this->send_to_children = $var;

        return $this;
    }

}

