<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/api.proto

namespace Fatehan\Service;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.fatehan.services.SendUserNotificationResponse</code>
 */
class SendUserNotificationResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool status = 1;</code>
     */
    protected $status = false;
    /**
     * Generated from protobuf field <code>repeated uint64 organization_ids = 2 [json_name = "organization_ids"];</code>
     */
    private $organization_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $status
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $organization_ids
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Service\MetaData\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool status = 1;</code>
     * @return bool
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>bool status = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 organization_ids = 2 [json_name = "organization_ids"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOrganizationIds()
    {
        return $this->organization_ids;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 organization_ids = 2 [json_name = "organization_ids"];</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOrganizationIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->organization_ids = $arr;

        return $this;
    }

}

