<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/api.proto

namespace Fatehan\Service;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.fatehan.services.SendUserNotificationRequest</code>
 */
class SendUserNotificationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated uint64 user_ids = 1 [json_name = "user_ids"];</code>
     */
    private $user_ids;
    /**
     * Generated from protobuf field <code>uint64 organization_id = 2 [json_name = "organization_id"];</code>
     */
    protected $organization_id = 0;
    /**
     * Generated from protobuf field <code>string title = 3 [json_name = "title"];</code>
     */
    protected $title = '';
    /**
     * Generated from protobuf field <code>string body = 4 [json_name = "body"];</code>
     */
    protected $body = '';
    /**
     * Generated from protobuf field <code>repeated .com.fatehan.notifies.Via via = 5 [json_name = "via"];</code>
     */
    private $via;
    /**
     * Generated from protobuf field <code>bool send_to_children = 6 [json_name = "send_to_children"];</code>
     */
    protected $send_to_children = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $user_ids
     *     @type int|string $organization_id
     *     @type string $title
     *     @type string $body
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $via
     *     @type bool $send_to_children
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Service\MetaData\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated uint64 user_ids = 1 [json_name = "user_ids"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserIds()
    {
        return $this->user_ids;
    }

    /**
     * Generated from protobuf field <code>repeated uint64 user_ids = 1 [json_name = "user_ids"];</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->user_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 organization_id = 2 [json_name = "organization_id"];</code>
     * @return int|string
     */
    public function getOrganizationId()
    {
        return $this->organization_id;
    }

    /**
     * Generated from protobuf field <code>uint64 organization_id = 2 [json_name = "organization_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrganizationId($var)
    {
        GPBUtil::checkUint64($var);
        $this->organization_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title = 3 [json_name = "title"];</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 3 [json_name = "title"];</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string body = 4 [json_name = "body"];</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>string body = 4 [json_name = "body"];</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, True);
        $this->body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.notifies.Via via = 5 [json_name = "via"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVia()
    {
        return $this->via;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.notifies.Via via = 5 [json_name = "via"];</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVia($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Fatehan\Notify\Via::class);
        $this->via = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool send_to_children = 6 [json_name = "send_to_children"];</code>
     * @return bool
     */
    public function getSendToChildren()
    {
        return $this->send_to_children;
    }

    /**
     * Generated from protobuf field <code>bool send_to_children = 6 [json_name = "send_to_children"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSendToChildren($var)
    {
        GPBUtil::checkBool($var);
        $this->send_to_children = $var;

        return $this;
    }

}

