<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/api.proto

namespace Fatehan\Service;

if (false) {
    /**
     * This class is deprecated. Use Fatehan\Service\Traffix\Event instead.
     * @deprecated
     */
    class Traffix_Event {}
}
class_exists(Traffix\Event::class);
@trigger_error('Fatehan\Service\Traffix_Event is deprecated and will be removed in the next major release. Use Fatehan\Service\Traffix\Event instead', E_USER_DEPRECATED);

