<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/api.proto

namespace Fatehan\Service;

if (false) {
    /**
     * This class is deprecated. Use Fatehan\Service\TripsSummaryRequest\GroupBy instead.
     * @deprecated
     */
    class TripsSummaryRequest_GroupBy {}
}
class_exists(TripsSummaryRequest\GroupBy::class);
@trigger_error('Fatehan\Service\TripsSummaryRequest_GroupBy is deprecated and will be removed in the next major release. Use Fatehan\Service\TripsSummaryRequest\GroupBy instead', E_USER_DEPRECATED);

