<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/api.proto

namespace Fatehan\Service;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.fatehan.services.TripReportResponse</code>
 */
class TripReportResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 cost = 1;</code>
     */
    protected $cost = 0;
    /**
     * Generated from protobuf field <code>uint32 threads = 2;</code>
     */
    protected $threads = 0;
    /**
     * Generated from protobuf field <code>uint32 records = 3;</code>
     */
    protected $records = 0;
    /**
     * Generated from protobuf field <code>repeated .com.fatehan.trips.Trip trips = 4;</code>
     */
    private $trips;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $cost
     *     @type int $threads
     *     @type int $records
     *     @type \Fatehan\Trip\Trip[]|\Google\Protobuf\Internal\RepeatedField $trips
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Service\MetaData\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 cost = 1;</code>
     * @return int
     */
    public function getCost()
    {
        return $this->cost;
    }

    /**
     * Generated from protobuf field <code>uint32 cost = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCost($var)
    {
        GPBUtil::checkUint32($var);
        $this->cost = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 threads = 2;</code>
     * @return int
     */
    public function getThreads()
    {
        return $this->threads;
    }

    /**
     * Generated from protobuf field <code>uint32 threads = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setThreads($var)
    {
        GPBUtil::checkUint32($var);
        $this->threads = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 records = 3;</code>
     * @return int
     */
    public function getRecords()
    {
        return $this->records;
    }

    /**
     * Generated from protobuf field <code>uint32 records = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRecords($var)
    {
        GPBUtil::checkUint32($var);
        $this->records = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.trips.Trip trips = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTrips()
    {
        return $this->trips;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.trips.Trip trips = 4;</code>
     * @param \Fatehan\Trip\Trip[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTrips($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fatehan\Trip\Trip::class);
        $this->trips = $arr;

        return $this;
    }

}

