<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services/api.proto

namespace Fatehan\Service;

if (false) {
    /**
     * This class is deprecated. Use Fatehan\Service\TripPerformance\Average instead.
     * @deprecated
     */
    class TripPerformance_Average {}
}
class_exists(TripPerformance\Average::class);
@trigger_error('Fatehan\Service\TripPerformance_Average is deprecated and will be removed in the next major release. Use Fatehan\Service\TripPerformance\Average instead', E_USER_DEPRECATED);

