<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reports/report.proto

namespace Fatehan\Report\TrafficResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.reports.TrafficResponse.Traffic</code>
 */
class Traffic extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.com.fatehan.reports.TrafficResponse.Traffic.EventType type = 1;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>optional string area = 2;</code>
     */
    protected $area = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_time = 3;</code>
     */
    protected $date_time = null;
    /**
     * Generated from protobuf field <code>uint64 area_id = 4;</code>
     */
    protected $area_id = 0;
    /**
     * Generated from protobuf field <code>uint64 device_id = 5;</code>
     */
    protected $device_id = 0;
    /**
     * Generated from protobuf field <code>optional uint32 mileage = 6;</code>
     */
    protected $mileage = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type string $area
     *     @type \Google\Protobuf\Timestamp $date_time
     *     @type int|string $area_id
     *     @type int|string $device_id
     *     @type int $mileage
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Report\MetaData\Report::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.reports.TrafficResponse.Traffic.EventType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.reports.TrafficResponse.Traffic.EventType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Fatehan\Report\TrafficResponse\Traffic\EventType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string area = 2;</code>
     * @return string
     */
    public function getArea()
    {
        return isset($this->area) ? $this->area : '';
    }

    public function hasArea()
    {
        return isset($this->area);
    }

    public function clearArea()
    {
        unset($this->area);
    }

    /**
     * Generated from protobuf field <code>optional string area = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setArea($var)
    {
        GPBUtil::checkString($var, True);
        $this->area = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_time = 3;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getDateTime()
    {
        return $this->date_time;
    }

    public function hasDateTime()
    {
        return isset($this->date_time);
    }

    public function clearDateTime()
    {
        unset($this->date_time);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_time = 3;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setDateTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->date_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 area_id = 4;</code>
     * @return int|string
     */
    public function getAreaId()
    {
        return $this->area_id;
    }

    /**
     * Generated from protobuf field <code>uint64 area_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAreaId($var)
    {
        GPBUtil::checkUint64($var);
        $this->area_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 device_id = 5;</code>
     * @return int|string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Generated from protobuf field <code>uint64 device_id = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkUint64($var);
        $this->device_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 mileage = 6;</code>
     * @return int
     */
    public function getMileage()
    {
        return isset($this->mileage) ? $this->mileage : 0;
    }

    public function hasMileage()
    {
        return isset($this->mileage);
    }

    public function clearMileage()
    {
        unset($this->mileage);
    }

    /**
     * Generated from protobuf field <code>optional uint32 mileage = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setMileage($var)
    {
        GPBUtil::checkUint32($var);
        $this->mileage = $var;

        return $this;
    }

}

