<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: activities/workshift.proto

namespace Fatehan\Activities\WorkShift;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.activities.WorkShiftTemplateIndexResponse</code>
 */
class WorkShiftTemplateIndexResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 current_page = 1;</code>
     */
    protected $current_page = 0;
    /**
     * Generated from protobuf field <code>uint32 last_page = 2;</code>
     */
    protected $last_page = 0;
    /**
     * Generated from protobuf field <code>uint32 per_page = 3;</code>
     */
    protected $per_page = 0;
    /**
     * Generated from protobuf field <code>repeated .com.fatehan.activities.WorkShiftTemplate data = 4;</code>
     */
    private $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $current_page
     *     @type int $last_page
     *     @type int $per_page
     *     @type \Fatehan\Activities\WorkShift\WorkShiftTemplate[] $data
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Activities\WorkShift\MetaData\Workshift::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 current_page = 1;</code>
     * @return int
     */
    public function getCurrentPage()
    {
        return $this->current_page;
    }

    /**
     * Generated from protobuf field <code>uint32 current_page = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrentPage(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->current_page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 last_page = 2;</code>
     * @return int
     */
    public function getLastPage()
    {
        return $this->last_page;
    }

    /**
     * Generated from protobuf field <code>uint32 last_page = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLastPage(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->last_page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 per_page = 3;</code>
     * @return int
     */
    public function getPerPage()
    {
        return $this->per_page;
    }

    /**
     * Generated from protobuf field <code>uint32 per_page = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPerPage(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->per_page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.activities.WorkShiftTemplate data = 4;</code>
     * @return RepeatedField<\Fatehan\Activities\WorkShift\WorkShiftTemplate>
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.activities.WorkShiftTemplate data = 4;</code>
     * @param \Fatehan\Activities\WorkShift\WorkShiftTemplate[] $var
     * @return $this
     */
    public function setData(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fatehan\Activities\WorkShift\WorkShiftTemplate::class);
        $this->data = $arr;

        return $this;
    }

}

