<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: packets/dataModel.proto

namespace Fatehan\Packet\DataModel\DeviceStatus;

use UnexpectedValueException;

/**
 * Protobuf type <code>com.fatehan.packets.DeviceStatus.Stat</code>
 */
class Stat
{
    /**
     * Generated from protobuf enum <code>STAT_UNSPECIFIED = 0;</code>
     */
    const STAT_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>IDLING = 1;</code>
     */
    const IDLING = 1;
    /**
     * Generated from protobuf enum <code>MOVING = 2;</code>
     */
    const MOVING = 2;
    /**
     * Generated from protobuf enum <code>TOWING = 3;</code>
     */
    const TOWING = 3;
    /**
     * Generated from protobuf enum <code>PARKING = 4;</code>
     */
    const PARKING = 4;

    private static $valueToName = [
        self::STAT_UNSPECIFIED => 'STAT_UNSPECIFIED',
        self::IDLING => 'IDLING',
        self::MOVING => 'MOVING',
        self::TOWING => 'TOWING',
        self::PARKING => 'PARKING',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

