<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: financial/financial.proto

namespace Fatehan\Financial;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.financial.Currency</code>
 */
class Currency extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1 [json_name = "id"];</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>optional string code = 3 [json_name = "code"];</code>
     */
    protected $code = null;
    /**
     * Generated from protobuf field <code>optional string left_sign = 4 [json_name = "left_sign"];</code>
     */
    protected $left_sign = null;
    /**
     * Generated from protobuf field <code>optional string right_sign = 5 [json_name = "right_sign"];</code>
     */
    protected $right_sign = null;
    /**
     * Generated from protobuf field <code>sint32 default = 6 [json_name = "default"];</code>
     */
    protected $default = 0;
    /**
     * Generated from protobuf field <code>sint32 ratio_to_default = 7 [json_name = "ratio_to_default"];</code>
     */
    protected $ratio_to_default = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 8 [json_name = "created_at"];</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 9 [json_name = "updated_at"];</code>
     */
    protected $updated_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $name
     *     @type string $code
     *     @type string $left_sign
     *     @type string $right_sign
     *     @type int $default
     *     @type int $ratio_to_default
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type \Google\Protobuf\Timestamp $updated_at
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Financial\MetaData\Financial::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1 [json_name = "id"];</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1 [json_name = "id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string code = 3 [json_name = "code"];</code>
     * @return string
     */
    public function getCode()
    {
        return isset($this->code) ? $this->code : '';
    }

    public function hasCode()
    {
        return isset($this->code);
    }

    public function clearCode()
    {
        unset($this->code);
    }

    /**
     * Generated from protobuf field <code>optional string code = 3 [json_name = "code"];</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string left_sign = 4 [json_name = "left_sign"];</code>
     * @return string
     */
    public function getLeftSign()
    {
        return isset($this->left_sign) ? $this->left_sign : '';
    }

    public function hasLeftSign()
    {
        return isset($this->left_sign);
    }

    public function clearLeftSign()
    {
        unset($this->left_sign);
    }

    /**
     * Generated from protobuf field <code>optional string left_sign = 4 [json_name = "left_sign"];</code>
     * @param string $var
     * @return $this
     */
    public function setLeftSign($var)
    {
        GPBUtil::checkString($var, True);
        $this->left_sign = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string right_sign = 5 [json_name = "right_sign"];</code>
     * @return string
     */
    public function getRightSign()
    {
        return isset($this->right_sign) ? $this->right_sign : '';
    }

    public function hasRightSign()
    {
        return isset($this->right_sign);
    }

    public function clearRightSign()
    {
        unset($this->right_sign);
    }

    /**
     * Generated from protobuf field <code>optional string right_sign = 5 [json_name = "right_sign"];</code>
     * @param string $var
     * @return $this
     */
    public function setRightSign($var)
    {
        GPBUtil::checkString($var, True);
        $this->right_sign = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint32 default = 6 [json_name = "default"];</code>
     * @return int
     */
    public function getDefault()
    {
        return $this->default;
    }

    /**
     * Generated from protobuf field <code>sint32 default = 6 [json_name = "default"];</code>
     * @param int $var
     * @return $this
     */
    public function setDefault($var)
    {
        GPBUtil::checkInt32($var);
        $this->default = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint32 ratio_to_default = 7 [json_name = "ratio_to_default"];</code>
     * @return int
     */
    public function getRatioToDefault()
    {
        return $this->ratio_to_default;
    }

    /**
     * Generated from protobuf field <code>sint32 ratio_to_default = 7 [json_name = "ratio_to_default"];</code>
     * @param int $var
     * @return $this
     */
    public function setRatioToDefault($var)
    {
        GPBUtil::checkInt32($var);
        $this->ratio_to_default = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 8 [json_name = "created_at"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 8 [json_name = "created_at"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 9 [json_name = "updated_at"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    public function hasUpdatedAt()
    {
        return isset($this->updated_at);
    }

    public function clearUpdatedAt()
    {
        unset($this->updated_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 9 [json_name = "updated_at"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_at = $var;

        return $this;
    }

}

