<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: financial/financial.proto

namespace Fatehan\Financial;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.financial.OrderPagination</code>
 */
class OrderPagination extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 current_page = 1 [json_name = "current_page"];</code>
     */
    protected $current_page = 0;
    /**
     * Generated from protobuf field <code>string first_page_url = 2 [json_name = "first_page_url"];</code>
     */
    protected $first_page_url = '';
    /**
     * Generated from protobuf field <code>string last_page_url = 3 [json_name = "last_page_url"];</code>
     */
    protected $last_page_url = '';
    /**
     * Generated from protobuf field <code>string next_page_url = 4 [json_name = "next_page_url"];</code>
     */
    protected $next_page_url = '';
    /**
     * Generated from protobuf field <code>string prev_page_url = 5 [json_name = "prev_page_url"];</code>
     */
    protected $prev_page_url = '';
    /**
     * Generated from protobuf field <code>string path = 6 [json_name = "path"];</code>
     */
    protected $path = '';
    /**
     * Generated from protobuf field <code>uint32 from = 7 [json_name = "from"];</code>
     */
    protected $from = 0;
    /**
     * Generated from protobuf field <code>uint32 last_page = 8 [json_name = "last_page"];</code>
     */
    protected $last_page = 0;
    /**
     * Generated from protobuf field <code>uint32 per_page = 9 [json_name = "per_page"];</code>
     */
    protected $per_page = 0;
    /**
     * Generated from protobuf field <code>uint32 to = 10 [json_name = "to"];</code>
     */
    protected $to = 0;
    /**
     * Generated from protobuf field <code>repeated .com.fatehan.financial.Order data = 11 [json_name = "data"];</code>
     */
    private $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $current_page
     *     @type string $first_page_url
     *     @type string $last_page_url
     *     @type string $next_page_url
     *     @type string $prev_page_url
     *     @type string $path
     *     @type int $from
     *     @type int $last_page
     *     @type int $per_page
     *     @type int $to
     *     @type \Fatehan\Financial\Order[] $data
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Financial\MetaData\Financial::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 current_page = 1 [json_name = "current_page"];</code>
     * @return int
     */
    public function getCurrentPage()
    {
        return $this->current_page;
    }

    /**
     * Generated from protobuf field <code>uint32 current_page = 1 [json_name = "current_page"];</code>
     * @param int $var
     * @return $this
     */
    public function setCurrentPage(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->current_page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string first_page_url = 2 [json_name = "first_page_url"];</code>
     * @return string
     */
    public function getFirstPageUrl()
    {
        return $this->first_page_url;
    }

    /**
     * Generated from protobuf field <code>string first_page_url = 2 [json_name = "first_page_url"];</code>
     * @param string $var
     * @return $this
     */
    public function setFirstPageUrl(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->first_page_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string last_page_url = 3 [json_name = "last_page_url"];</code>
     * @return string
     */
    public function getLastPageUrl()
    {
        return $this->last_page_url;
    }

    /**
     * Generated from protobuf field <code>string last_page_url = 3 [json_name = "last_page_url"];</code>
     * @param string $var
     * @return $this
     */
    public function setLastPageUrl(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->last_page_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string next_page_url = 4 [json_name = "next_page_url"];</code>
     * @return string
     */
    public function getNextPageUrl()
    {
        return $this->next_page_url;
    }

    /**
     * Generated from protobuf field <code>string next_page_url = 4 [json_name = "next_page_url"];</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageUrl(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->next_page_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string prev_page_url = 5 [json_name = "prev_page_url"];</code>
     * @return string
     */
    public function getPrevPageUrl()
    {
        return $this->prev_page_url;
    }

    /**
     * Generated from protobuf field <code>string prev_page_url = 5 [json_name = "prev_page_url"];</code>
     * @param string $var
     * @return $this
     */
    public function setPrevPageUrl(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->prev_page_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string path = 6 [json_name = "path"];</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 6 [json_name = "path"];</code>
     * @param string $var
     * @return $this
     */
    public function setPath(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 from = 7 [json_name = "from"];</code>
     * @return int
     */
    public function getFrom()
    {
        return $this->from;
    }

    /**
     * Generated from protobuf field <code>uint32 from = 7 [json_name = "from"];</code>
     * @param int $var
     * @return $this
     */
    public function setFrom(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->from = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 last_page = 8 [json_name = "last_page"];</code>
     * @return int
     */
    public function getLastPage()
    {
        return $this->last_page;
    }

    /**
     * Generated from protobuf field <code>uint32 last_page = 8 [json_name = "last_page"];</code>
     * @param int $var
     * @return $this
     */
    public function setLastPage(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->last_page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 per_page = 9 [json_name = "per_page"];</code>
     * @return int
     */
    public function getPerPage()
    {
        return $this->per_page;
    }

    /**
     * Generated from protobuf field <code>uint32 per_page = 9 [json_name = "per_page"];</code>
     * @param int $var
     * @return $this
     */
    public function setPerPage(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->per_page = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 to = 10 [json_name = "to"];</code>
     * @return int
     */
    public function getTo()
    {
        return $this->to;
    }

    /**
     * Generated from protobuf field <code>uint32 to = 10 [json_name = "to"];</code>
     * @param int $var
     * @return $this
     */
    public function setTo(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->to = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.financial.Order data = 11 [json_name = "data"];</code>
     * @return RepeatedField<\Fatehan\Financial\Order>
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.financial.Order data = 11 [json_name = "data"];</code>
     * @param \Fatehan\Financial\Order[] $var
     * @return $this
     */
    public function setData(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fatehan\Financial\Order::class);
        $this->data = $arr;

        return $this;
    }

}

