<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reports/report.proto

namespace Fatehan\Report\Traffix\Event;

use UnexpectedValueException;

/**
 * Protobuf type <code>com.fatehan.reports.Traffix.Event.Type</code>
 */
class Type
{
    /**
     * Generated from protobuf enum <code>NONE = 0;</code>
     */
    const NONE = 0;
    /**
     * Generated from protobuf enum <code>INSIDE = 1;</code>
     */
    const INSIDE = 1;
    /**
     * Generated from protobuf enum <code>OUTSIDE = 2;</code>
     */
    const OUTSIDE = 2;

    private static $valueToName = [
        self::NONE => 'NONE',
        self::INSIDE => 'INSIDE',
        self::OUTSIDE => 'OUTSIDE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

