<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identities/identities.proto

namespace Fatehan\Identity;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>com.fatehan.identities.AuthLog</code>
 */
class AuthLog extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string domain = 2;</code>
     */
    protected $domain = '';
    /**
     * Generated from protobuf field <code>uint64 identity_id = 3;</code>
     */
    protected $identity_id = 0;
    /**
     * Generated from protobuf field <code>uint64 organization_id = 4;</code>
     */
    protected $organization_id = 0;
    /**
     * Generated from protobuf field <code>string authentication_method = 5;</code>
     */
    protected $authentication_method = '';
    /**
     * Generated from protobuf field <code>string verification_method = 6;</code>
     */
    protected $verification_method = '';
    /**
     * Generated from protobuf field <code>string result = 7;</code>
     */
    protected $result = '';
    /**
     * Generated from protobuf field <code>string ip = 8;</code>
     */
    protected $ip = '';
    /**
     * Generated from protobuf field <code>string user_agent = 9;</code>
     */
    protected $user_agent = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 10;</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 11;</code>
     */
    protected $updated_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $domain
     *     @type int|string $identity_id
     *     @type int|string $organization_id
     *     @type string $authentication_method
     *     @type string $verification_method
     *     @type string $result
     *     @type string $ip
     *     @type string $user_agent
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type \Google\Protobuf\Timestamp $updated_at
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Identity\MetaData\Identities::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>bytes id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, False);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string domain = 2;</code>
     * @return string
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * Generated from protobuf field <code>string domain = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDomain($var)
    {
        GPBUtil::checkString($var, True);
        $this->domain = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 identity_id = 3;</code>
     * @return int|string
     */
    public function getIdentityId()
    {
        return $this->identity_id;
    }

    /**
     * Generated from protobuf field <code>uint64 identity_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIdentityId($var)
    {
        GPBUtil::checkUint64($var);
        $this->identity_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 organization_id = 4;</code>
     * @return int|string
     */
    public function getOrganizationId()
    {
        return $this->organization_id;
    }

    /**
     * Generated from protobuf field <code>uint64 organization_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOrganizationId($var)
    {
        GPBUtil::checkUint64($var);
        $this->organization_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string authentication_method = 5;</code>
     * @return string
     */
    public function getAuthenticationMethod()
    {
        return $this->authentication_method;
    }

    /**
     * Generated from protobuf field <code>string authentication_method = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthenticationMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->authentication_method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string verification_method = 6;</code>
     * @return string
     */
    public function getVerificationMethod()
    {
        return $this->verification_method;
    }

    /**
     * Generated from protobuf field <code>string verification_method = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setVerificationMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->verification_method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string result = 7;</code>
     * @return string
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>string result = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkString($var, True);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ip = 8;</code>
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * Generated from protobuf field <code>string ip = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string user_agent = 9;</code>
     * @return string
     */
    public function getUserAgent()
    {
        return $this->user_agent;
    }

    /**
     * Generated from protobuf field <code>string user_agent = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setUserAgent($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_agent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 10;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 10;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 11;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    public function hasUpdatedAt()
    {
        return isset($this->updated_at);
    }

    public function clearUpdatedAt()
    {
        unset($this->updated_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 11;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_at = $var;

        return $this;
    }

}

