<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identities/identities.proto

namespace Fatehan\Identity;

if (false) {
    /**
     * This class is deprecated. Use Fatehan\Identity\Receiver\Token instead.
     * @deprecated
     */
    class Receiver_Token {}
}
class_exists(Receiver\Token::class);
@trigger_error('Fatehan\Identity\Receiver_Token is deprecated and will be removed in the next major release. Use Fatehan\Identity\Receiver\Token instead', E_USER_DEPRECATED);

