<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: activities/workflow.proto

namespace Fatehan\Activities\Workflow;

use UnexpectedValueException;

/**
 * Protobuf type <code>com.fatehan.activities.AreaEvent</code>
 */
class AreaEvent
{
    /**
     * Generated from protobuf enum <code>NONE = 0;</code>
     */
    const NONE = 0;
    /**
     * Generated from protobuf enum <code>ENTER = 1;</code>
     */
    const ENTER = 1;
    /**
     * Generated from protobuf enum <code>EXIT = 2;</code>
     */
    const PBEXIT = 2;

    private static $valueToName = [
        self::NONE => 'NONE',
        self::ENTER => 'ENTER',
        self::PBEXIT => 'EXIT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            $pbconst =  __CLASS__. '::PB' . strtoupper($name);
            if (!defined($pbconst)) {
                throw new UnexpectedValueException(sprintf(
                        'Enum %s has no value defined for name %s', __CLASS__, $name));
            }
            return constant($pbconst);
        }
        return constant($const);
    }
}

