<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trips/trip.proto

namespace Fatehan\Trip;

use UnexpectedValueException;

/**
 * Protobuf type <code>com.fatehan.trips.CrashEnum</code>
 */
class CrashEnum
{
    /**
     * Generated from protobuf enum <code>CrashNone = 0;</code>
     */
    const CrashNone = 0;
    /**
     * Generated from protobuf enum <code>RealCrash = 1;</code>
     */
    const RealCrash = 1;
    /**
     * Generated from protobuf enum <code>LimitedCrashTrace = 2;</code>
     */
    const LimitedCrashTrace = 2;
    /**
     * Generated from protobuf enum <code>LimitedCrashTraceNotCalibrated = 3;</code>
     */
    const LimitedCrashTraceNotCalibrated = 3;
    /**
     * Generated from protobuf enum <code>FullCrashTraceNotCalibrated = 4;</code>
     */
    const FullCrashTraceNotCalibrated = 4;
    /**
     * Generated from protobuf enum <code>FullCrashTrace = 5;</code>
     */
    const FullCrashTrace = 5;
    /**
     * Generated from protobuf enum <code>RealCrashNotCalibrated = 6;</code>
     */
    const RealCrashNotCalibrated = 6;

    private static $valueToName = [
        self::CrashNone => 'CrashNone',
        self::RealCrash => 'RealCrash',
        self::LimitedCrashTrace => 'LimitedCrashTrace',
        self::LimitedCrashTraceNotCalibrated => 'LimitedCrashTraceNotCalibrated',
        self::FullCrashTraceNotCalibrated => 'FullCrashTraceNotCalibrated',
        self::FullCrashTrace => 'FullCrashTrace',
        self::RealCrashNotCalibrated => 'RealCrashNotCalibrated',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

