<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trips/trip.proto

namespace Fatehan\Trip;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.trips.FusionTrip</code>
 */
class FusionTrip extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1 [json_name = "id"];</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>uint64 device_id = 2 [json_name = "device_id"];</code>
     */
    protected $device_id = 0;
    /**
     * Generated from protobuf field <code>uint32 mileage = 3 [json_name = "mileage"];</code>
     */
    protected $mileage = 0;
    /**
     * Generated from protobuf field <code>uint32 idling = 4 [json_name = "idling"];</code>
     */
    protected $idling = 0;
    /**
     * Generated from protobuf field <code>uint32 parking = 5 [json_name = "parking"];</code>
     */
    protected $parking = 0;
    /**
     * Generated from protobuf field <code>uint32 moving = 6 [json_name = "moving"];</code>
     */
    protected $moving = 0;
    /**
     * Generated from protobuf field <code>uint32 towing = 7 [json_name = "towing"];</code>
     */
    protected $towing = 0;
    /**
     * Generated from protobuf field <code>uint32 speed_total = 8 [json_name = "speed_total"];</code>
     */
    protected $speed_total = 0;
    /**
     * Generated from protobuf field <code>uint32 speed_sum = 9 [json_name = "speed_sum"];</code>
     */
    protected $speed_sum = 0;
    /**
     * Generated from protobuf field <code>uint32 speed_max = 10 [json_name = "speed_max"];</code>
     */
    protected $speed_max = 0;
    /**
     * Generated from protobuf field <code>uint32 records = 11 [json_name = "records"];</code>
     */
    protected $records = 0;
    /**
     * Generated from protobuf field <code>uint32 harsh_acceleration = 12 [json_name = "harsh_acceleration"];</code>
     */
    protected $harsh_acceleration = 0;
    /**
     * Generated from protobuf field <code>uint32 harsh_break = 13 [json_name = "harsh_break"];</code>
     */
    protected $harsh_break = 0;
    /**
     * Generated from protobuf field <code>uint32 harsh_corner = 14 [json_name = "harsh_corner"];</code>
     */
    protected $harsh_corner = 0;
    /**
     * Generated from protobuf field <code>optional sint32 min_temp01 = 15 [json_name = "min_temp01"];</code>
     */
    protected $min_temp01 = null;
    /**
     * Generated from protobuf field <code>optional sint32 max_temp01 = 16 [json_name = "max_temp01"];</code>
     */
    protected $max_temp01 = null;
    /**
     * Generated from protobuf field <code>optional sint32 min_temp02 = 17 [json_name = "min_temp02"];</code>
     */
    protected $min_temp02 = null;
    /**
     * Generated from protobuf field <code>optional sint32 max_temp02 = 18 [json_name = "max_temp02"];</code>
     */
    protected $max_temp02 = null;
    /**
     * Generated from protobuf field <code>optional sint32 min_temp03 = 19 [json_name = "min_temp03"];</code>
     */
    protected $min_temp03 = null;
    /**
     * Generated from protobuf field <code>optional sint32 max_temp03 = 20 [json_name = "max_temp03"];</code>
     */
    protected $max_temp03 = null;
    /**
     * Generated from protobuf field <code>optional sint32 min_temp04 = 21 [json_name = "min_temp04"];</code>
     */
    protected $min_temp04 = null;
    /**
     * Generated from protobuf field <code>optional sint32 max_temp04 = 22 [json_name = "max_temp04"];</code>
     */
    protected $max_temp04 = null;
    /**
     * Generated from protobuf field <code>optional uint32 min_humidity = 23 [json_name = "min_humidity"];</code>
     */
    protected $min_humidity = null;
    /**
     * Generated from protobuf field <code>optional uint32 max_humidity = 24 [json_name = "max_humidity"];</code>
     */
    protected $max_humidity = null;
    /**
     * Generated from protobuf field <code>optional float start_lat = 25 [json_name = "start_lat"];</code>
     */
    protected $start_lat = null;
    /**
     * Generated from protobuf field <code>optional float start_lng = 26 [json_name = "start_lng"];</code>
     */
    protected $start_lng = null;
    /**
     * Generated from protobuf field <code>optional float finish_lat = 27 [json_name = "finish_lat"];</code>
     */
    protected $finish_lat = null;
    /**
     * Generated from protobuf field <code>optional float finish_lng = 28 [json_name = "finish_lng"];</code>
     */
    protected $finish_lng = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp started_at = 29 [json_name = "started_at"];</code>
     */
    protected $started_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp finished_at = 30 [json_name = "finished_at"];</code>
     */
    protected $finished_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 31 [json_name = "created_at"];</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 32 [json_name = "updated_at"];</code>
     */
    protected $updated_at = null;
    /**
     * Generated from protobuf field <code>string Logs = 33 [json_name = "logs"];</code>
     */
    protected $Logs = '';
    /**
     * Generated from protobuf field <code>optional uint32 Fug = 34 [json_name = "fug"];</code>
     */
    protected $Fug = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type int|string $device_id
     *     @type int $mileage
     *     @type int $idling
     *     @type int $parking
     *     @type int $moving
     *     @type int $towing
     *     @type int $speed_total
     *     @type int $speed_sum
     *     @type int $speed_max
     *     @type int $records
     *     @type int $harsh_acceleration
     *     @type int $harsh_break
     *     @type int $harsh_corner
     *     @type int $min_temp01
     *     @type int $max_temp01
     *     @type int $min_temp02
     *     @type int $max_temp02
     *     @type int $min_temp03
     *     @type int $max_temp03
     *     @type int $min_temp04
     *     @type int $max_temp04
     *     @type int $min_humidity
     *     @type int $max_humidity
     *     @type float $start_lat
     *     @type float $start_lng
     *     @type float $finish_lat
     *     @type float $finish_lng
     *     @type \Google\Protobuf\Timestamp $started_at
     *     @type \Google\Protobuf\Timestamp $finished_at
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type \Google\Protobuf\Timestamp $updated_at
     *     @type string $Logs
     *     @type int $Fug
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Trip\MetaData\Trip::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1 [json_name = "id"];</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1 [json_name = "id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 device_id = 2 [json_name = "device_id"];</code>
     * @return int|string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     * Generated from protobuf field <code>uint64 device_id = 2 [json_name = "device_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkUint64($var);
        $this->device_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 mileage = 3 [json_name = "mileage"];</code>
     * @return int
     */
    public function getMileage()
    {
        return $this->mileage;
    }

    /**
     * Generated from protobuf field <code>uint32 mileage = 3 [json_name = "mileage"];</code>
     * @param int $var
     * @return $this
     */
    public function setMileage($var)
    {
        GPBUtil::checkUint32($var);
        $this->mileage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 idling = 4 [json_name = "idling"];</code>
     * @return int
     */
    public function getIdling()
    {
        return $this->idling;
    }

    /**
     * Generated from protobuf field <code>uint32 idling = 4 [json_name = "idling"];</code>
     * @param int $var
     * @return $this
     */
    public function setIdling($var)
    {
        GPBUtil::checkUint32($var);
        $this->idling = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 parking = 5 [json_name = "parking"];</code>
     * @return int
     */
    public function getParking()
    {
        return $this->parking;
    }

    /**
     * Generated from protobuf field <code>uint32 parking = 5 [json_name = "parking"];</code>
     * @param int $var
     * @return $this
     */
    public function setParking($var)
    {
        GPBUtil::checkUint32($var);
        $this->parking = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 moving = 6 [json_name = "moving"];</code>
     * @return int
     */
    public function getMoving()
    {
        return $this->moving;
    }

    /**
     * Generated from protobuf field <code>uint32 moving = 6 [json_name = "moving"];</code>
     * @param int $var
     * @return $this
     */
    public function setMoving($var)
    {
        GPBUtil::checkUint32($var);
        $this->moving = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 towing = 7 [json_name = "towing"];</code>
     * @return int
     */
    public function getTowing()
    {
        return $this->towing;
    }

    /**
     * Generated from protobuf field <code>uint32 towing = 7 [json_name = "towing"];</code>
     * @param int $var
     * @return $this
     */
    public function setTowing($var)
    {
        GPBUtil::checkUint32($var);
        $this->towing = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 speed_total = 8 [json_name = "speed_total"];</code>
     * @return int
     */
    public function getSpeedTotal()
    {
        return $this->speed_total;
    }

    /**
     * Generated from protobuf field <code>uint32 speed_total = 8 [json_name = "speed_total"];</code>
     * @param int $var
     * @return $this
     */
    public function setSpeedTotal($var)
    {
        GPBUtil::checkUint32($var);
        $this->speed_total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 speed_sum = 9 [json_name = "speed_sum"];</code>
     * @return int
     */
    public function getSpeedSum()
    {
        return $this->speed_sum;
    }

    /**
     * Generated from protobuf field <code>uint32 speed_sum = 9 [json_name = "speed_sum"];</code>
     * @param int $var
     * @return $this
     */
    public function setSpeedSum($var)
    {
        GPBUtil::checkUint32($var);
        $this->speed_sum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 speed_max = 10 [json_name = "speed_max"];</code>
     * @return int
     */
    public function getSpeedMax()
    {
        return $this->speed_max;
    }

    /**
     * Generated from protobuf field <code>uint32 speed_max = 10 [json_name = "speed_max"];</code>
     * @param int $var
     * @return $this
     */
    public function setSpeedMax($var)
    {
        GPBUtil::checkUint32($var);
        $this->speed_max = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 records = 11 [json_name = "records"];</code>
     * @return int
     */
    public function getRecords()
    {
        return $this->records;
    }

    /**
     * Generated from protobuf field <code>uint32 records = 11 [json_name = "records"];</code>
     * @param int $var
     * @return $this
     */
    public function setRecords($var)
    {
        GPBUtil::checkUint32($var);
        $this->records = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 harsh_acceleration = 12 [json_name = "harsh_acceleration"];</code>
     * @return int
     */
    public function getHarshAcceleration()
    {
        return $this->harsh_acceleration;
    }

    /**
     * Generated from protobuf field <code>uint32 harsh_acceleration = 12 [json_name = "harsh_acceleration"];</code>
     * @param int $var
     * @return $this
     */
    public function setHarshAcceleration($var)
    {
        GPBUtil::checkUint32($var);
        $this->harsh_acceleration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 harsh_break = 13 [json_name = "harsh_break"];</code>
     * @return int
     */
    public function getHarshBreak()
    {
        return $this->harsh_break;
    }

    /**
     * Generated from protobuf field <code>uint32 harsh_break = 13 [json_name = "harsh_break"];</code>
     * @param int $var
     * @return $this
     */
    public function setHarshBreak($var)
    {
        GPBUtil::checkUint32($var);
        $this->harsh_break = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 harsh_corner = 14 [json_name = "harsh_corner"];</code>
     * @return int
     */
    public function getHarshCorner()
    {
        return $this->harsh_corner;
    }

    /**
     * Generated from protobuf field <code>uint32 harsh_corner = 14 [json_name = "harsh_corner"];</code>
     * @param int $var
     * @return $this
     */
    public function setHarshCorner($var)
    {
        GPBUtil::checkUint32($var);
        $this->harsh_corner = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional sint32 min_temp01 = 15 [json_name = "min_temp01"];</code>
     * @return int
     */
    public function getMinTemp01()
    {
        return isset($this->min_temp01) ? $this->min_temp01 : 0;
    }

    public function hasMinTemp01()
    {
        return isset($this->min_temp01);
    }

    public function clearMinTemp01()
    {
        unset($this->min_temp01);
    }

    /**
     * Generated from protobuf field <code>optional sint32 min_temp01 = 15 [json_name = "min_temp01"];</code>
     * @param int $var
     * @return $this
     */
    public function setMinTemp01($var)
    {
        GPBUtil::checkInt32($var);
        $this->min_temp01 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional sint32 max_temp01 = 16 [json_name = "max_temp01"];</code>
     * @return int
     */
    public function getMaxTemp01()
    {
        return isset($this->max_temp01) ? $this->max_temp01 : 0;
    }

    public function hasMaxTemp01()
    {
        return isset($this->max_temp01);
    }

    public function clearMaxTemp01()
    {
        unset($this->max_temp01);
    }

    /**
     * Generated from protobuf field <code>optional sint32 max_temp01 = 16 [json_name = "max_temp01"];</code>
     * @param int $var
     * @return $this
     */
    public function setMaxTemp01($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_temp01 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional sint32 min_temp02 = 17 [json_name = "min_temp02"];</code>
     * @return int
     */
    public function getMinTemp02()
    {
        return isset($this->min_temp02) ? $this->min_temp02 : 0;
    }

    public function hasMinTemp02()
    {
        return isset($this->min_temp02);
    }

    public function clearMinTemp02()
    {
        unset($this->min_temp02);
    }

    /**
     * Generated from protobuf field <code>optional sint32 min_temp02 = 17 [json_name = "min_temp02"];</code>
     * @param int $var
     * @return $this
     */
    public function setMinTemp02($var)
    {
        GPBUtil::checkInt32($var);
        $this->min_temp02 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional sint32 max_temp02 = 18 [json_name = "max_temp02"];</code>
     * @return int
     */
    public function getMaxTemp02()
    {
        return isset($this->max_temp02) ? $this->max_temp02 : 0;
    }

    public function hasMaxTemp02()
    {
        return isset($this->max_temp02);
    }

    public function clearMaxTemp02()
    {
        unset($this->max_temp02);
    }

    /**
     * Generated from protobuf field <code>optional sint32 max_temp02 = 18 [json_name = "max_temp02"];</code>
     * @param int $var
     * @return $this
     */
    public function setMaxTemp02($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_temp02 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional sint32 min_temp03 = 19 [json_name = "min_temp03"];</code>
     * @return int
     */
    public function getMinTemp03()
    {
        return isset($this->min_temp03) ? $this->min_temp03 : 0;
    }

    public function hasMinTemp03()
    {
        return isset($this->min_temp03);
    }

    public function clearMinTemp03()
    {
        unset($this->min_temp03);
    }

    /**
     * Generated from protobuf field <code>optional sint32 min_temp03 = 19 [json_name = "min_temp03"];</code>
     * @param int $var
     * @return $this
     */
    public function setMinTemp03($var)
    {
        GPBUtil::checkInt32($var);
        $this->min_temp03 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional sint32 max_temp03 = 20 [json_name = "max_temp03"];</code>
     * @return int
     */
    public function getMaxTemp03()
    {
        return isset($this->max_temp03) ? $this->max_temp03 : 0;
    }

    public function hasMaxTemp03()
    {
        return isset($this->max_temp03);
    }

    public function clearMaxTemp03()
    {
        unset($this->max_temp03);
    }

    /**
     * Generated from protobuf field <code>optional sint32 max_temp03 = 20 [json_name = "max_temp03"];</code>
     * @param int $var
     * @return $this
     */
    public function setMaxTemp03($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_temp03 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional sint32 min_temp04 = 21 [json_name = "min_temp04"];</code>
     * @return int
     */
    public function getMinTemp04()
    {
        return isset($this->min_temp04) ? $this->min_temp04 : 0;
    }

    public function hasMinTemp04()
    {
        return isset($this->min_temp04);
    }

    public function clearMinTemp04()
    {
        unset($this->min_temp04);
    }

    /**
     * Generated from protobuf field <code>optional sint32 min_temp04 = 21 [json_name = "min_temp04"];</code>
     * @param int $var
     * @return $this
     */
    public function setMinTemp04($var)
    {
        GPBUtil::checkInt32($var);
        $this->min_temp04 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional sint32 max_temp04 = 22 [json_name = "max_temp04"];</code>
     * @return int
     */
    public function getMaxTemp04()
    {
        return isset($this->max_temp04) ? $this->max_temp04 : 0;
    }

    public function hasMaxTemp04()
    {
        return isset($this->max_temp04);
    }

    public function clearMaxTemp04()
    {
        unset($this->max_temp04);
    }

    /**
     * Generated from protobuf field <code>optional sint32 max_temp04 = 22 [json_name = "max_temp04"];</code>
     * @param int $var
     * @return $this
     */
    public function setMaxTemp04($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_temp04 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 min_humidity = 23 [json_name = "min_humidity"];</code>
     * @return int
     */
    public function getMinHumidity()
    {
        return isset($this->min_humidity) ? $this->min_humidity : 0;
    }

    public function hasMinHumidity()
    {
        return isset($this->min_humidity);
    }

    public function clearMinHumidity()
    {
        unset($this->min_humidity);
    }

    /**
     * Generated from protobuf field <code>optional uint32 min_humidity = 23 [json_name = "min_humidity"];</code>
     * @param int $var
     * @return $this
     */
    public function setMinHumidity($var)
    {
        GPBUtil::checkUint32($var);
        $this->min_humidity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 max_humidity = 24 [json_name = "max_humidity"];</code>
     * @return int
     */
    public function getMaxHumidity()
    {
        return isset($this->max_humidity) ? $this->max_humidity : 0;
    }

    public function hasMaxHumidity()
    {
        return isset($this->max_humidity);
    }

    public function clearMaxHumidity()
    {
        unset($this->max_humidity);
    }

    /**
     * Generated from protobuf field <code>optional uint32 max_humidity = 24 [json_name = "max_humidity"];</code>
     * @param int $var
     * @return $this
     */
    public function setMaxHumidity($var)
    {
        GPBUtil::checkUint32($var);
        $this->max_humidity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional float start_lat = 25 [json_name = "start_lat"];</code>
     * @return float
     */
    public function getStartLat()
    {
        return isset($this->start_lat) ? $this->start_lat : 0.0;
    }

    public function hasStartLat()
    {
        return isset($this->start_lat);
    }

    public function clearStartLat()
    {
        unset($this->start_lat);
    }

    /**
     * Generated from protobuf field <code>optional float start_lat = 25 [json_name = "start_lat"];</code>
     * @param float $var
     * @return $this
     */
    public function setStartLat($var)
    {
        GPBUtil::checkFloat($var);
        $this->start_lat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional float start_lng = 26 [json_name = "start_lng"];</code>
     * @return float
     */
    public function getStartLng()
    {
        return isset($this->start_lng) ? $this->start_lng : 0.0;
    }

    public function hasStartLng()
    {
        return isset($this->start_lng);
    }

    public function clearStartLng()
    {
        unset($this->start_lng);
    }

    /**
     * Generated from protobuf field <code>optional float start_lng = 26 [json_name = "start_lng"];</code>
     * @param float $var
     * @return $this
     */
    public function setStartLng($var)
    {
        GPBUtil::checkFloat($var);
        $this->start_lng = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional float finish_lat = 27 [json_name = "finish_lat"];</code>
     * @return float
     */
    public function getFinishLat()
    {
        return isset($this->finish_lat) ? $this->finish_lat : 0.0;
    }

    public function hasFinishLat()
    {
        return isset($this->finish_lat);
    }

    public function clearFinishLat()
    {
        unset($this->finish_lat);
    }

    /**
     * Generated from protobuf field <code>optional float finish_lat = 27 [json_name = "finish_lat"];</code>
     * @param float $var
     * @return $this
     */
    public function setFinishLat($var)
    {
        GPBUtil::checkFloat($var);
        $this->finish_lat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional float finish_lng = 28 [json_name = "finish_lng"];</code>
     * @return float
     */
    public function getFinishLng()
    {
        return isset($this->finish_lng) ? $this->finish_lng : 0.0;
    }

    public function hasFinishLng()
    {
        return isset($this->finish_lng);
    }

    public function clearFinishLng()
    {
        unset($this->finish_lng);
    }

    /**
     * Generated from protobuf field <code>optional float finish_lng = 28 [json_name = "finish_lng"];</code>
     * @param float $var
     * @return $this
     */
    public function setFinishLng($var)
    {
        GPBUtil::checkFloat($var);
        $this->finish_lng = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp started_at = 29 [json_name = "started_at"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getStartedAt()
    {
        return $this->started_at;
    }

    public function hasStartedAt()
    {
        return isset($this->started_at);
    }

    public function clearStartedAt()
    {
        unset($this->started_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp started_at = 29 [json_name = "started_at"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setStartedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->started_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp finished_at = 30 [json_name = "finished_at"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getFinishedAt()
    {
        return $this->finished_at;
    }

    public function hasFinishedAt()
    {
        return isset($this->finished_at);
    }

    public function clearFinishedAt()
    {
        unset($this->finished_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp finished_at = 30 [json_name = "finished_at"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setFinishedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->finished_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 31 [json_name = "created_at"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    public function hasCreatedAt()
    {
        return isset($this->created_at);
    }

    public function clearCreatedAt()
    {
        unset($this->created_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 31 [json_name = "created_at"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 32 [json_name = "updated_at"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    public function hasUpdatedAt()
    {
        return isset($this->updated_at);
    }

    public function clearUpdatedAt()
    {
        unset($this->updated_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 32 [json_name = "updated_at"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Logs = 33 [json_name = "logs"];</code>
     * @return string
     */
    public function getLogs()
    {
        return $this->Logs;
    }

    /**
     * Generated from protobuf field <code>string Logs = 33 [json_name = "logs"];</code>
     * @param string $var
     * @return $this
     */
    public function setLogs($var)
    {
        GPBUtil::checkString($var, True);
        $this->Logs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 Fug = 34 [json_name = "fug"];</code>
     * @return int
     */
    public function getFug()
    {
        return isset($this->Fug) ? $this->Fug : 0;
    }

    public function hasFug()
    {
        return isset($this->Fug);
    }

    public function clearFug()
    {
        unset($this->Fug);
    }

    /**
     * Generated from protobuf field <code>optional uint32 Fug = 34 [json_name = "fug"];</code>
     * @param int $var
     * @return $this
     */
    public function setFug($var)
    {
        GPBUtil::checkUint32($var);
        $this->Fug = $var;

        return $this;
    }

}

