<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/api.proto

namespace Fatehan\Service\MaintenanceIndexResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.services.MaintenanceIndexResponse.Statistics</code>
 */
class Statistics extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 completed = 1 [json_name = "completed"];</code>
     */
    protected $completed = 0;
    /**
     * Generated from protobuf field <code>uint32 not_completed = 2 [json_name = "not_completed"];</code>
     */
    protected $not_completed = 0;
    /**
     * Generated from protobuf field <code>uint32 total = 3 [json_name = "total"];</code>
     */
    protected $total = 0;
    /**
     * Generated from protobuf field <code>repeated .com.fatehan.services.MaintenanceIndexResponse.MostUsed most_used_services = 4 [json_name = "most_used_services"];</code>
     */
    private $most_used_services;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $completed
     *     @type int $not_completed
     *     @type int $total
     *     @type \Fatehan\Service\MaintenanceIndexResponse\MostUsed[] $most_used_services
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Service\MetaData\Api::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 completed = 1 [json_name = "completed"];</code>
     * @return int
     */
    public function getCompleted()
    {
        return $this->completed;
    }

    /**
     * Generated from protobuf field <code>uint32 completed = 1 [json_name = "completed"];</code>
     * @param int $var
     * @return $this
     */
    public function setCompleted($var)
    {
        GPBUtil::checkUint32($var);
        $this->completed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 not_completed = 2 [json_name = "not_completed"];</code>
     * @return int
     */
    public function getNotCompleted()
    {
        return $this->not_completed;
    }

    /**
     * Generated from protobuf field <code>uint32 not_completed = 2 [json_name = "not_completed"];</code>
     * @param int $var
     * @return $this
     */
    public function setNotCompleted($var)
    {
        GPBUtil::checkUint32($var);
        $this->not_completed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 total = 3 [json_name = "total"];</code>
     * @return int
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>uint32 total = 3 [json_name = "total"];</code>
     * @param int $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkUint32($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.services.MaintenanceIndexResponse.MostUsed most_used_services = 4 [json_name = "most_used_services"];</code>
     * @return RepeatedField<\Fatehan\Service\MaintenanceIndexResponse\MostUsed>
     */
    public function getMostUsedServices()
    {
        return $this->most_used_services;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.services.MaintenanceIndexResponse.MostUsed most_used_services = 4 [json_name = "most_used_services"];</code>
     * @param \Fatehan\Service\MaintenanceIndexResponse\MostUsed[] $var
     * @return $this
     */
    public function setMostUsedServices($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fatehan\Service\MaintenanceIndexResponse\MostUsed::class);
        $this->most_used_services = $arr;

        return $this;
    }

}

