<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services/repositories.proto

namespace Fatehan\Service\Repositories;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.services.DeviceRepo</code>
 */
class DeviceRepo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.com.fatehan.devices.Device device = 1 [json_name = "device"];</code>
     */
    protected $device = null;
    /**
     * Generated from protobuf field <code>optional .com.fatehan.devices.DeviceIcon icon = 2 [json_name = "icon"];</code>
     */
    protected $icon = null;
    /**
     * Generated from protobuf field <code>optional .com.fatehan.devices.Tracker tracker = 3 [json_name = "tracker"];</code>
     */
    protected $tracker = null;
    /**
     * Generated from protobuf field <code>optional .com.fatehan.services.CarRepo car_repo = 4 [json_name = "car_repo"];</code>
     */
    protected $car_repo = null;
    /**
     * Generated from protobuf field <code>optional .com.fatehan.packets.DeviceStatus device_status = 5 [json_name = "device_status"];</code>
     */
    protected $device_status = null;
    /**
     * Generated from protobuf field <code>repeated .com.fatehan.devices.SystemIo user_device_io = 6 [json_name = "user_device_io"];</code>
     */
    private $user_device_io;
    /**
     * Generated from protobuf field <code>optional .com.fatehan.services.UserRepo owner_repo = 7 [json_name = "owner_repo"];</code>
     */
    protected $owner_repo = null;
    /**
     * Generated from protobuf field <code>optional .com.fatehan.identities.Organization organization = 8 [json_name = "organization"];</code>
     */
    protected $organization = null;
    /**
     * Generated from protobuf field <code>bool subscribed = 9 [json_name = "subscribed"];</code>
     */
    protected $subscribed = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Fatehan\Device\Device $device
     *     @type \Fatehan\Device\DeviceIcon $icon
     *     @type \Fatehan\Device\Tracker $tracker
     *     @type \Fatehan\Service\Repositories\CarRepo $car_repo
     *     @type \Fatehan\Packet\DataModel\DeviceStatus $device_status
     *     @type \Fatehan\Device\SystemIo[] $user_device_io
     *     @type \Fatehan\Service\Repositories\UserRepo $owner_repo
     *     @type \Fatehan\Identity\Organization $organization
     *     @type bool $subscribed
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Service\Repositories\MetaData\Repositories::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.devices.Device device = 1 [json_name = "device"];</code>
     * @return \Fatehan\Device\Device|null
     */
    public function getDevice()
    {
        return $this->device;
    }

    public function hasDevice()
    {
        return isset($this->device);
    }

    public function clearDevice()
    {
        unset($this->device);
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.devices.Device device = 1 [json_name = "device"];</code>
     * @param \Fatehan\Device\Device $var
     * @return $this
     */
    public function setDevice($var)
    {
        GPBUtil::checkMessage($var, \Fatehan\Device\Device::class);
        $this->device = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .com.fatehan.devices.DeviceIcon icon = 2 [json_name = "icon"];</code>
     * @return \Fatehan\Device\DeviceIcon|null
     */
    public function getIcon()
    {
        return $this->icon;
    }

    public function hasIcon()
    {
        return isset($this->icon);
    }

    public function clearIcon()
    {
        unset($this->icon);
    }

    /**
     * Generated from protobuf field <code>optional .com.fatehan.devices.DeviceIcon icon = 2 [json_name = "icon"];</code>
     * @param \Fatehan\Device\DeviceIcon $var
     * @return $this
     */
    public function setIcon($var)
    {
        GPBUtil::checkMessage($var, \Fatehan\Device\DeviceIcon::class);
        $this->icon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .com.fatehan.devices.Tracker tracker = 3 [json_name = "tracker"];</code>
     * @return \Fatehan\Device\Tracker|null
     */
    public function getTracker()
    {
        return $this->tracker;
    }

    public function hasTracker()
    {
        return isset($this->tracker);
    }

    public function clearTracker()
    {
        unset($this->tracker);
    }

    /**
     * Generated from protobuf field <code>optional .com.fatehan.devices.Tracker tracker = 3 [json_name = "tracker"];</code>
     * @param \Fatehan\Device\Tracker $var
     * @return $this
     */
    public function setTracker($var)
    {
        GPBUtil::checkMessage($var, \Fatehan\Device\Tracker::class);
        $this->tracker = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .com.fatehan.services.CarRepo car_repo = 4 [json_name = "car_repo"];</code>
     * @return \Fatehan\Service\Repositories\CarRepo|null
     */
    public function getCarRepo()
    {
        return $this->car_repo;
    }

    public function hasCarRepo()
    {
        return isset($this->car_repo);
    }

    public function clearCarRepo()
    {
        unset($this->car_repo);
    }

    /**
     * Generated from protobuf field <code>optional .com.fatehan.services.CarRepo car_repo = 4 [json_name = "car_repo"];</code>
     * @param \Fatehan\Service\Repositories\CarRepo $var
     * @return $this
     */
    public function setCarRepo($var)
    {
        GPBUtil::checkMessage($var, \Fatehan\Service\Repositories\CarRepo::class);
        $this->car_repo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .com.fatehan.packets.DeviceStatus device_status = 5 [json_name = "device_status"];</code>
     * @return \Fatehan\Packet\DataModel\DeviceStatus|null
     */
    public function getDeviceStatus()
    {
        return $this->device_status;
    }

    public function hasDeviceStatus()
    {
        return isset($this->device_status);
    }

    public function clearDeviceStatus()
    {
        unset($this->device_status);
    }

    /**
     * Generated from protobuf field <code>optional .com.fatehan.packets.DeviceStatus device_status = 5 [json_name = "device_status"];</code>
     * @param \Fatehan\Packet\DataModel\DeviceStatus $var
     * @return $this
     */
    public function setDeviceStatus($var)
    {
        GPBUtil::checkMessage($var, \Fatehan\Packet\DataModel\DeviceStatus::class);
        $this->device_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.devices.SystemIo user_device_io = 6 [json_name = "user_device_io"];</code>
     * @return RepeatedField<\Fatehan\Device\SystemIo>
     */
    public function getUserDeviceIo()
    {
        return $this->user_device_io;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.devices.SystemIo user_device_io = 6 [json_name = "user_device_io"];</code>
     * @param \Fatehan\Device\SystemIo[] $var
     * @return $this
     */
    public function setUserDeviceIo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fatehan\Device\SystemIo::class);
        $this->user_device_io = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .com.fatehan.services.UserRepo owner_repo = 7 [json_name = "owner_repo"];</code>
     * @return \Fatehan\Service\Repositories\UserRepo|null
     */
    public function getOwnerRepo()
    {
        return $this->owner_repo;
    }

    public function hasOwnerRepo()
    {
        return isset($this->owner_repo);
    }

    public function clearOwnerRepo()
    {
        unset($this->owner_repo);
    }

    /**
     * Generated from protobuf field <code>optional .com.fatehan.services.UserRepo owner_repo = 7 [json_name = "owner_repo"];</code>
     * @param \Fatehan\Service\Repositories\UserRepo $var
     * @return $this
     */
    public function setOwnerRepo($var)
    {
        GPBUtil::checkMessage($var, \Fatehan\Service\Repositories\UserRepo::class);
        $this->owner_repo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .com.fatehan.identities.Organization organization = 8 [json_name = "organization"];</code>
     * @return \Fatehan\Identity\Organization|null
     */
    public function getOrganization()
    {
        return $this->organization;
    }

    public function hasOrganization()
    {
        return isset($this->organization);
    }

    public function clearOrganization()
    {
        unset($this->organization);
    }

    /**
     * Generated from protobuf field <code>optional .com.fatehan.identities.Organization organization = 8 [json_name = "organization"];</code>
     * @param \Fatehan\Identity\Organization $var
     * @return $this
     */
    public function setOrganization($var)
    {
        GPBUtil::checkMessage($var, \Fatehan\Identity\Organization::class);
        $this->organization = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool subscribed = 9 [json_name = "subscribed"];</code>
     * @return bool
     */
    public function getSubscribed()
    {
        return $this->subscribed;
    }

    /**
     * Generated from protobuf field <code>bool subscribed = 9 [json_name = "subscribed"];</code>
     * @param bool $var
     * @return $this
     */
    public function setSubscribed($var)
    {
        GPBUtil::checkBool($var);
        $this->subscribed = $var;

        return $this;
    }

}

