<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: packets/forge.proto

namespace Fatehan\Packet\Forge\JTTPlaybackUpdate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.packets.JTTPlaybackUpdate.Control</code>
 */
class Control extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>sint32 fast_forward = 1;</code>
     */
    protected $fast_forward = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp playback_position = 2;</code>
     */
    protected $playback_position = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $fast_forward
     *     @type \Google\Protobuf\Timestamp $playback_position
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Packet\Forge\MetaData\Forge::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>sint32 fast_forward = 1;</code>
     * @return int
     */
    public function getFastForward()
    {
        return $this->fast_forward;
    }

    /**
     * Generated from protobuf field <code>sint32 fast_forward = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFastForward($var)
    {
        GPBUtil::checkInt32($var);
        $this->fast_forward = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp playback_position = 2;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getPlaybackPosition()
    {
        return $this->playback_position;
    }

    public function hasPlaybackPosition()
    {
        return isset($this->playback_position);
    }

    public function clearPlaybackPosition()
    {
        unset($this->playback_position);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp playback_position = 2;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setPlaybackPosition($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->playback_position = $var;

        return $this;
    }

}

