<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: packets/dataModel.proto

namespace Fatehan\Packet\DataModel\CanAdaptersElements;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.packets.CanAdaptersElements.Isf</code>
 */
class Isf extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional bool check_engine_indicator = 1 [json_name = "check_engine_indicator"];</code>
     */
    protected $check_engine_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool abs_indicator = 2 [json_name = "abs_indicator"];</code>
     */
    protected $abs_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool esp_indicator = 3 [json_name = "esp_indicator"];</code>
     */
    protected $esp_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool esp_turned_off = 4 [json_name = "esp_turned_off"];</code>
     */
    protected $esp_turned_off = null;
    /**
     * Generated from protobuf field <code>optional bool stop_indicator = 5 [json_name = "stop_indicator"];</code>
     */
    protected $stop_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool oil_level_indicator = 6 [json_name = "oil_level_indicator"];</code>
     */
    protected $oil_level_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool coolant_liquid_level = 7 [json_name = "coolant_liquid_level"];</code>
     */
    protected $coolant_liquid_level = null;
    /**
     * Generated from protobuf field <code>optional bool battery_not_charging_indicator = 8 [json_name = "battery_not_charging_indicator"];</code>
     */
    protected $battery_not_charging_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool handbrake_system_indicator = 9 [json_name = "handbrake_system_indicator"];</code>
     */
    protected $handbrake_system_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool airbag_indicator = 10 [json_name = "airbag_indicator"];</code>
     */
    protected $airbag_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool eps_indicator = 11 [json_name = "eps_indicator"];</code>
     */
    protected $eps_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool warning_indicator = 12 [json_name = "warning_indicator"];</code>
     */
    protected $warning_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool lights_failure_indicator = 13 [json_name = "lights_failure_indicator"];</code>
     */
    protected $lights_failure_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool low_tire_pressure_indicator = 14 [json_name = "low_tire_pressure_indicator"];</code>
     */
    protected $low_tire_pressure_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool wear_of_brake_pads_indicator = 15 [json_name = "wear_of_brake_pads_indicator"];</code>
     */
    protected $wear_of_brake_pads_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool low_fuel_level_indicator = 16 [json_name = "low_fuel_level_indicator"];</code>
     */
    protected $low_fuel_level_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool maintenance_required_indicator = 17 [json_name = "maintenance_required_indicator"];</code>
     */
    protected $maintenance_required_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool glow_plug_indicator = 18 [json_name = "glow_plug_indicator"];</code>
     */
    protected $glow_plug_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool fap_indicator = 19 [json_name = "fap_indicator"];</code>
     */
    protected $fap_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool epc_electronic_power_control_indicator = 20 [json_name = "epc_electronic_power_control_indicator"];</code>
     */
    protected $epc_electronic_power_control_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool clogged_engine_oil_filter_indicator = 21 [json_name = "clogged_engine_oil_filter_indicator"];</code>
     */
    protected $clogged_engine_oil_filter_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool low_engine_oil_pressure_indicator = 22 [json_name = "low_engine_oil_pressure_indicator"];</code>
     */
    protected $low_engine_oil_pressure_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool too_high_engine_oil_temperature_indicator = 23 [json_name = "too_high_engine_oil_temperature_indicator"];</code>
     */
    protected $too_high_engine_oil_temperature_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool low_coolant_level_indicator = 24 [json_name = "low_coolant_level_indicator"];</code>
     */
    protected $low_coolant_level_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool clogged_hydraulic_system_oil_filter_indicator = 25 [json_name = "clogged_hydraulic_system_oil_filter_indicator"];</code>
     */
    protected $clogged_hydraulic_system_oil_filter_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool hydraulic_system_low_pressure_indicator = 26 [json_name = "hydraulic_system_low_pressure_indicator"];</code>
     */
    protected $hydraulic_system_low_pressure_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool hydraulic_oil_low_level_indicator = 27 [json_name = "hydraulic_oil_low_level_indicator"];</code>
     */
    protected $hydraulic_oil_low_level_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool hydraulic_system_high_temperature_indicator = 28 [json_name = "hydraulic_system_high_temperature_indicator"];</code>
     */
    protected $hydraulic_system_high_temperature_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool oil_overflow_in_hydraulic_chamber_indicator = 29 [json_name = "oil_overflow_in_hydraulic_chamber_indicator"];</code>
     */
    protected $oil_overflow_in_hydraulic_chamber_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool clogged_air_filter_indicator = 30 [json_name = "clogged_air_filter_indicator"];</code>
     */
    protected $clogged_air_filter_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool clogged_fuel_filter_indicator = 31 [json_name = "clogged_fuel_filter_indicator"];</code>
     */
    protected $clogged_fuel_filter_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool water_in_fuel_indicator = 32 [json_name = "water_in_fuel_indicator"];</code>
     */
    protected $water_in_fuel_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool clogged_brake_system_filter_indicator = 33 [json_name = "clogged_brake_system_filter_indicator"];</code>
     */
    protected $clogged_brake_system_filter_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool low_washer_fluid_level_indicator = 34 [json_name = "low_washer_fluid_level_indicator"];</code>
     */
    protected $low_washer_fluid_level_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool low_ad_blue_level_indicator = 35 [json_name = "low_ad_blue_level_indicator"];</code>
     */
    protected $low_ad_blue_level_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool low_trailer_tyre_pressure_indicator = 36 [json_name = "low_trailer_tyre_pressure_indicator"];</code>
     */
    protected $low_trailer_tyre_pressure_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool wear_of_trailer_brake_lining_indicator = 37 [json_name = "wear_of_trailer_brake_lining_indicator"];</code>
     */
    protected $wear_of_trailer_brake_lining_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool high_trailer_brake_temperature_indicator = 38 [json_name = "high_trailer_brake_temperature_indicator"];</code>
     */
    protected $high_trailer_brake_temperature_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool incorrect_trailer_pneumatic_supply_indicator = 39 [json_name = "incorrect_trailer_pneumatic_supply_indicator"];</code>
     */
    protected $incorrect_trailer_pneumatic_supply_indicator = null;
    /**
     * Generated from protobuf field <code>optional bool low_cng_level_indicator = 40 [json_name = "low_cng_level_indicator"];</code>
     */
    protected $low_cng_level_indicator = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $check_engine_indicator
     *     @type bool $abs_indicator
     *     @type bool $esp_indicator
     *     @type bool $esp_turned_off
     *     @type bool $stop_indicator
     *     @type bool $oil_level_indicator
     *     @type bool $coolant_liquid_level
     *     @type bool $battery_not_charging_indicator
     *     @type bool $handbrake_system_indicator
     *     @type bool $airbag_indicator
     *     @type bool $eps_indicator
     *     @type bool $warning_indicator
     *     @type bool $lights_failure_indicator
     *     @type bool $low_tire_pressure_indicator
     *     @type bool $wear_of_brake_pads_indicator
     *     @type bool $low_fuel_level_indicator
     *     @type bool $maintenance_required_indicator
     *     @type bool $glow_plug_indicator
     *     @type bool $fap_indicator
     *     @type bool $epc_electronic_power_control_indicator
     *     @type bool $clogged_engine_oil_filter_indicator
     *     @type bool $low_engine_oil_pressure_indicator
     *     @type bool $too_high_engine_oil_temperature_indicator
     *     @type bool $low_coolant_level_indicator
     *     @type bool $clogged_hydraulic_system_oil_filter_indicator
     *     @type bool $hydraulic_system_low_pressure_indicator
     *     @type bool $hydraulic_oil_low_level_indicator
     *     @type bool $hydraulic_system_high_temperature_indicator
     *     @type bool $oil_overflow_in_hydraulic_chamber_indicator
     *     @type bool $clogged_air_filter_indicator
     *     @type bool $clogged_fuel_filter_indicator
     *     @type bool $water_in_fuel_indicator
     *     @type bool $clogged_brake_system_filter_indicator
     *     @type bool $low_washer_fluid_level_indicator
     *     @type bool $low_ad_blue_level_indicator
     *     @type bool $low_trailer_tyre_pressure_indicator
     *     @type bool $wear_of_trailer_brake_lining_indicator
     *     @type bool $high_trailer_brake_temperature_indicator
     *     @type bool $incorrect_trailer_pneumatic_supply_indicator
     *     @type bool $low_cng_level_indicator
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Packet\DataModel\MetaData\DataModel::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional bool check_engine_indicator = 1 [json_name = "check_engine_indicator"];</code>
     * @return bool
     */
    public function getCheckEngineIndicator()
    {
        return isset($this->check_engine_indicator) ? $this->check_engine_indicator : false;
    }

    public function hasCheckEngineIndicator()
    {
        return isset($this->check_engine_indicator);
    }

    public function clearCheckEngineIndicator()
    {
        unset($this->check_engine_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool check_engine_indicator = 1 [json_name = "check_engine_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setCheckEngineIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->check_engine_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool abs_indicator = 2 [json_name = "abs_indicator"];</code>
     * @return bool
     */
    public function getAbsIndicator()
    {
        return isset($this->abs_indicator) ? $this->abs_indicator : false;
    }

    public function hasAbsIndicator()
    {
        return isset($this->abs_indicator);
    }

    public function clearAbsIndicator()
    {
        unset($this->abs_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool abs_indicator = 2 [json_name = "abs_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setAbsIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->abs_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool esp_indicator = 3 [json_name = "esp_indicator"];</code>
     * @return bool
     */
    public function getEspIndicator()
    {
        return isset($this->esp_indicator) ? $this->esp_indicator : false;
    }

    public function hasEspIndicator()
    {
        return isset($this->esp_indicator);
    }

    public function clearEspIndicator()
    {
        unset($this->esp_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool esp_indicator = 3 [json_name = "esp_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setEspIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->esp_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool esp_turned_off = 4 [json_name = "esp_turned_off"];</code>
     * @return bool
     */
    public function getEspTurnedOff()
    {
        return isset($this->esp_turned_off) ? $this->esp_turned_off : false;
    }

    public function hasEspTurnedOff()
    {
        return isset($this->esp_turned_off);
    }

    public function clearEspTurnedOff()
    {
        unset($this->esp_turned_off);
    }

    /**
     * Generated from protobuf field <code>optional bool esp_turned_off = 4 [json_name = "esp_turned_off"];</code>
     * @param bool $var
     * @return $this
     */
    public function setEspTurnedOff($var)
    {
        GPBUtil::checkBool($var);
        $this->esp_turned_off = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool stop_indicator = 5 [json_name = "stop_indicator"];</code>
     * @return bool
     */
    public function getStopIndicator()
    {
        return isset($this->stop_indicator) ? $this->stop_indicator : false;
    }

    public function hasStopIndicator()
    {
        return isset($this->stop_indicator);
    }

    public function clearStopIndicator()
    {
        unset($this->stop_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool stop_indicator = 5 [json_name = "stop_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setStopIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->stop_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool oil_level_indicator = 6 [json_name = "oil_level_indicator"];</code>
     * @return bool
     */
    public function getOilLevelIndicator()
    {
        return isset($this->oil_level_indicator) ? $this->oil_level_indicator : false;
    }

    public function hasOilLevelIndicator()
    {
        return isset($this->oil_level_indicator);
    }

    public function clearOilLevelIndicator()
    {
        unset($this->oil_level_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool oil_level_indicator = 6 [json_name = "oil_level_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setOilLevelIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->oil_level_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool coolant_liquid_level = 7 [json_name = "coolant_liquid_level"];</code>
     * @return bool
     */
    public function getCoolantLiquidLevel()
    {
        return isset($this->coolant_liquid_level) ? $this->coolant_liquid_level : false;
    }

    public function hasCoolantLiquidLevel()
    {
        return isset($this->coolant_liquid_level);
    }

    public function clearCoolantLiquidLevel()
    {
        unset($this->coolant_liquid_level);
    }

    /**
     * Generated from protobuf field <code>optional bool coolant_liquid_level = 7 [json_name = "coolant_liquid_level"];</code>
     * @param bool $var
     * @return $this
     */
    public function setCoolantLiquidLevel($var)
    {
        GPBUtil::checkBool($var);
        $this->coolant_liquid_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool battery_not_charging_indicator = 8 [json_name = "battery_not_charging_indicator"];</code>
     * @return bool
     */
    public function getBatteryNotChargingIndicator()
    {
        return isset($this->battery_not_charging_indicator) ? $this->battery_not_charging_indicator : false;
    }

    public function hasBatteryNotChargingIndicator()
    {
        return isset($this->battery_not_charging_indicator);
    }

    public function clearBatteryNotChargingIndicator()
    {
        unset($this->battery_not_charging_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool battery_not_charging_indicator = 8 [json_name = "battery_not_charging_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setBatteryNotChargingIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->battery_not_charging_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool handbrake_system_indicator = 9 [json_name = "handbrake_system_indicator"];</code>
     * @return bool
     */
    public function getHandbrakeSystemIndicator()
    {
        return isset($this->handbrake_system_indicator) ? $this->handbrake_system_indicator : false;
    }

    public function hasHandbrakeSystemIndicator()
    {
        return isset($this->handbrake_system_indicator);
    }

    public function clearHandbrakeSystemIndicator()
    {
        unset($this->handbrake_system_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool handbrake_system_indicator = 9 [json_name = "handbrake_system_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setHandbrakeSystemIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->handbrake_system_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool airbag_indicator = 10 [json_name = "airbag_indicator"];</code>
     * @return bool
     */
    public function getAirbagIndicator()
    {
        return isset($this->airbag_indicator) ? $this->airbag_indicator : false;
    }

    public function hasAirbagIndicator()
    {
        return isset($this->airbag_indicator);
    }

    public function clearAirbagIndicator()
    {
        unset($this->airbag_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool airbag_indicator = 10 [json_name = "airbag_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setAirbagIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->airbag_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool eps_indicator = 11 [json_name = "eps_indicator"];</code>
     * @return bool
     */
    public function getEpsIndicator()
    {
        return isset($this->eps_indicator) ? $this->eps_indicator : false;
    }

    public function hasEpsIndicator()
    {
        return isset($this->eps_indicator);
    }

    public function clearEpsIndicator()
    {
        unset($this->eps_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool eps_indicator = 11 [json_name = "eps_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setEpsIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->eps_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool warning_indicator = 12 [json_name = "warning_indicator"];</code>
     * @return bool
     */
    public function getWarningIndicator()
    {
        return isset($this->warning_indicator) ? $this->warning_indicator : false;
    }

    public function hasWarningIndicator()
    {
        return isset($this->warning_indicator);
    }

    public function clearWarningIndicator()
    {
        unset($this->warning_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool warning_indicator = 12 [json_name = "warning_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setWarningIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->warning_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool lights_failure_indicator = 13 [json_name = "lights_failure_indicator"];</code>
     * @return bool
     */
    public function getLightsFailureIndicator()
    {
        return isset($this->lights_failure_indicator) ? $this->lights_failure_indicator : false;
    }

    public function hasLightsFailureIndicator()
    {
        return isset($this->lights_failure_indicator);
    }

    public function clearLightsFailureIndicator()
    {
        unset($this->lights_failure_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool lights_failure_indicator = 13 [json_name = "lights_failure_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setLightsFailureIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->lights_failure_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool low_tire_pressure_indicator = 14 [json_name = "low_tire_pressure_indicator"];</code>
     * @return bool
     */
    public function getLowTirePressureIndicator()
    {
        return isset($this->low_tire_pressure_indicator) ? $this->low_tire_pressure_indicator : false;
    }

    public function hasLowTirePressureIndicator()
    {
        return isset($this->low_tire_pressure_indicator);
    }

    public function clearLowTirePressureIndicator()
    {
        unset($this->low_tire_pressure_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool low_tire_pressure_indicator = 14 [json_name = "low_tire_pressure_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setLowTirePressureIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->low_tire_pressure_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool wear_of_brake_pads_indicator = 15 [json_name = "wear_of_brake_pads_indicator"];</code>
     * @return bool
     */
    public function getWearOfBrakePadsIndicator()
    {
        return isset($this->wear_of_brake_pads_indicator) ? $this->wear_of_brake_pads_indicator : false;
    }

    public function hasWearOfBrakePadsIndicator()
    {
        return isset($this->wear_of_brake_pads_indicator);
    }

    public function clearWearOfBrakePadsIndicator()
    {
        unset($this->wear_of_brake_pads_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool wear_of_brake_pads_indicator = 15 [json_name = "wear_of_brake_pads_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setWearOfBrakePadsIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->wear_of_brake_pads_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool low_fuel_level_indicator = 16 [json_name = "low_fuel_level_indicator"];</code>
     * @return bool
     */
    public function getLowFuelLevelIndicator()
    {
        return isset($this->low_fuel_level_indicator) ? $this->low_fuel_level_indicator : false;
    }

    public function hasLowFuelLevelIndicator()
    {
        return isset($this->low_fuel_level_indicator);
    }

    public function clearLowFuelLevelIndicator()
    {
        unset($this->low_fuel_level_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool low_fuel_level_indicator = 16 [json_name = "low_fuel_level_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setLowFuelLevelIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->low_fuel_level_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool maintenance_required_indicator = 17 [json_name = "maintenance_required_indicator"];</code>
     * @return bool
     */
    public function getMaintenanceRequiredIndicator()
    {
        return isset($this->maintenance_required_indicator) ? $this->maintenance_required_indicator : false;
    }

    public function hasMaintenanceRequiredIndicator()
    {
        return isset($this->maintenance_required_indicator);
    }

    public function clearMaintenanceRequiredIndicator()
    {
        unset($this->maintenance_required_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool maintenance_required_indicator = 17 [json_name = "maintenance_required_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setMaintenanceRequiredIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->maintenance_required_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool glow_plug_indicator = 18 [json_name = "glow_plug_indicator"];</code>
     * @return bool
     */
    public function getGlowPlugIndicator()
    {
        return isset($this->glow_plug_indicator) ? $this->glow_plug_indicator : false;
    }

    public function hasGlowPlugIndicator()
    {
        return isset($this->glow_plug_indicator);
    }

    public function clearGlowPlugIndicator()
    {
        unset($this->glow_plug_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool glow_plug_indicator = 18 [json_name = "glow_plug_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setGlowPlugIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->glow_plug_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool fap_indicator = 19 [json_name = "fap_indicator"];</code>
     * @return bool
     */
    public function getFapIndicator()
    {
        return isset($this->fap_indicator) ? $this->fap_indicator : false;
    }

    public function hasFapIndicator()
    {
        return isset($this->fap_indicator);
    }

    public function clearFapIndicator()
    {
        unset($this->fap_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool fap_indicator = 19 [json_name = "fap_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setFapIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->fap_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool epc_electronic_power_control_indicator = 20 [json_name = "epc_electronic_power_control_indicator"];</code>
     * @return bool
     */
    public function getEpcElectronicPowerControlIndicator()
    {
        return isset($this->epc_electronic_power_control_indicator) ? $this->epc_electronic_power_control_indicator : false;
    }

    public function hasEpcElectronicPowerControlIndicator()
    {
        return isset($this->epc_electronic_power_control_indicator);
    }

    public function clearEpcElectronicPowerControlIndicator()
    {
        unset($this->epc_electronic_power_control_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool epc_electronic_power_control_indicator = 20 [json_name = "epc_electronic_power_control_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setEpcElectronicPowerControlIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->epc_electronic_power_control_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool clogged_engine_oil_filter_indicator = 21 [json_name = "clogged_engine_oil_filter_indicator"];</code>
     * @return bool
     */
    public function getCloggedEngineOilFilterIndicator()
    {
        return isset($this->clogged_engine_oil_filter_indicator) ? $this->clogged_engine_oil_filter_indicator : false;
    }

    public function hasCloggedEngineOilFilterIndicator()
    {
        return isset($this->clogged_engine_oil_filter_indicator);
    }

    public function clearCloggedEngineOilFilterIndicator()
    {
        unset($this->clogged_engine_oil_filter_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool clogged_engine_oil_filter_indicator = 21 [json_name = "clogged_engine_oil_filter_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setCloggedEngineOilFilterIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->clogged_engine_oil_filter_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool low_engine_oil_pressure_indicator = 22 [json_name = "low_engine_oil_pressure_indicator"];</code>
     * @return bool
     */
    public function getLowEngineOilPressureIndicator()
    {
        return isset($this->low_engine_oil_pressure_indicator) ? $this->low_engine_oil_pressure_indicator : false;
    }

    public function hasLowEngineOilPressureIndicator()
    {
        return isset($this->low_engine_oil_pressure_indicator);
    }

    public function clearLowEngineOilPressureIndicator()
    {
        unset($this->low_engine_oil_pressure_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool low_engine_oil_pressure_indicator = 22 [json_name = "low_engine_oil_pressure_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setLowEngineOilPressureIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->low_engine_oil_pressure_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool too_high_engine_oil_temperature_indicator = 23 [json_name = "too_high_engine_oil_temperature_indicator"];</code>
     * @return bool
     */
    public function getTooHighEngineOilTemperatureIndicator()
    {
        return isset($this->too_high_engine_oil_temperature_indicator) ? $this->too_high_engine_oil_temperature_indicator : false;
    }

    public function hasTooHighEngineOilTemperatureIndicator()
    {
        return isset($this->too_high_engine_oil_temperature_indicator);
    }

    public function clearTooHighEngineOilTemperatureIndicator()
    {
        unset($this->too_high_engine_oil_temperature_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool too_high_engine_oil_temperature_indicator = 23 [json_name = "too_high_engine_oil_temperature_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setTooHighEngineOilTemperatureIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->too_high_engine_oil_temperature_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool low_coolant_level_indicator = 24 [json_name = "low_coolant_level_indicator"];</code>
     * @return bool
     */
    public function getLowCoolantLevelIndicator()
    {
        return isset($this->low_coolant_level_indicator) ? $this->low_coolant_level_indicator : false;
    }

    public function hasLowCoolantLevelIndicator()
    {
        return isset($this->low_coolant_level_indicator);
    }

    public function clearLowCoolantLevelIndicator()
    {
        unset($this->low_coolant_level_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool low_coolant_level_indicator = 24 [json_name = "low_coolant_level_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setLowCoolantLevelIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->low_coolant_level_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool clogged_hydraulic_system_oil_filter_indicator = 25 [json_name = "clogged_hydraulic_system_oil_filter_indicator"];</code>
     * @return bool
     */
    public function getCloggedHydraulicSystemOilFilterIndicator()
    {
        return isset($this->clogged_hydraulic_system_oil_filter_indicator) ? $this->clogged_hydraulic_system_oil_filter_indicator : false;
    }

    public function hasCloggedHydraulicSystemOilFilterIndicator()
    {
        return isset($this->clogged_hydraulic_system_oil_filter_indicator);
    }

    public function clearCloggedHydraulicSystemOilFilterIndicator()
    {
        unset($this->clogged_hydraulic_system_oil_filter_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool clogged_hydraulic_system_oil_filter_indicator = 25 [json_name = "clogged_hydraulic_system_oil_filter_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setCloggedHydraulicSystemOilFilterIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->clogged_hydraulic_system_oil_filter_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool hydraulic_system_low_pressure_indicator = 26 [json_name = "hydraulic_system_low_pressure_indicator"];</code>
     * @return bool
     */
    public function getHydraulicSystemLowPressureIndicator()
    {
        return isset($this->hydraulic_system_low_pressure_indicator) ? $this->hydraulic_system_low_pressure_indicator : false;
    }

    public function hasHydraulicSystemLowPressureIndicator()
    {
        return isset($this->hydraulic_system_low_pressure_indicator);
    }

    public function clearHydraulicSystemLowPressureIndicator()
    {
        unset($this->hydraulic_system_low_pressure_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool hydraulic_system_low_pressure_indicator = 26 [json_name = "hydraulic_system_low_pressure_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setHydraulicSystemLowPressureIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->hydraulic_system_low_pressure_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool hydraulic_oil_low_level_indicator = 27 [json_name = "hydraulic_oil_low_level_indicator"];</code>
     * @return bool
     */
    public function getHydraulicOilLowLevelIndicator()
    {
        return isset($this->hydraulic_oil_low_level_indicator) ? $this->hydraulic_oil_low_level_indicator : false;
    }

    public function hasHydraulicOilLowLevelIndicator()
    {
        return isset($this->hydraulic_oil_low_level_indicator);
    }

    public function clearHydraulicOilLowLevelIndicator()
    {
        unset($this->hydraulic_oil_low_level_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool hydraulic_oil_low_level_indicator = 27 [json_name = "hydraulic_oil_low_level_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setHydraulicOilLowLevelIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->hydraulic_oil_low_level_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool hydraulic_system_high_temperature_indicator = 28 [json_name = "hydraulic_system_high_temperature_indicator"];</code>
     * @return bool
     */
    public function getHydraulicSystemHighTemperatureIndicator()
    {
        return isset($this->hydraulic_system_high_temperature_indicator) ? $this->hydraulic_system_high_temperature_indicator : false;
    }

    public function hasHydraulicSystemHighTemperatureIndicator()
    {
        return isset($this->hydraulic_system_high_temperature_indicator);
    }

    public function clearHydraulicSystemHighTemperatureIndicator()
    {
        unset($this->hydraulic_system_high_temperature_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool hydraulic_system_high_temperature_indicator = 28 [json_name = "hydraulic_system_high_temperature_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setHydraulicSystemHighTemperatureIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->hydraulic_system_high_temperature_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool oil_overflow_in_hydraulic_chamber_indicator = 29 [json_name = "oil_overflow_in_hydraulic_chamber_indicator"];</code>
     * @return bool
     */
    public function getOilOverflowInHydraulicChamberIndicator()
    {
        return isset($this->oil_overflow_in_hydraulic_chamber_indicator) ? $this->oil_overflow_in_hydraulic_chamber_indicator : false;
    }

    public function hasOilOverflowInHydraulicChamberIndicator()
    {
        return isset($this->oil_overflow_in_hydraulic_chamber_indicator);
    }

    public function clearOilOverflowInHydraulicChamberIndicator()
    {
        unset($this->oil_overflow_in_hydraulic_chamber_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool oil_overflow_in_hydraulic_chamber_indicator = 29 [json_name = "oil_overflow_in_hydraulic_chamber_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setOilOverflowInHydraulicChamberIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->oil_overflow_in_hydraulic_chamber_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool clogged_air_filter_indicator = 30 [json_name = "clogged_air_filter_indicator"];</code>
     * @return bool
     */
    public function getCloggedAirFilterIndicator()
    {
        return isset($this->clogged_air_filter_indicator) ? $this->clogged_air_filter_indicator : false;
    }

    public function hasCloggedAirFilterIndicator()
    {
        return isset($this->clogged_air_filter_indicator);
    }

    public function clearCloggedAirFilterIndicator()
    {
        unset($this->clogged_air_filter_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool clogged_air_filter_indicator = 30 [json_name = "clogged_air_filter_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setCloggedAirFilterIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->clogged_air_filter_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool clogged_fuel_filter_indicator = 31 [json_name = "clogged_fuel_filter_indicator"];</code>
     * @return bool
     */
    public function getCloggedFuelFilterIndicator()
    {
        return isset($this->clogged_fuel_filter_indicator) ? $this->clogged_fuel_filter_indicator : false;
    }

    public function hasCloggedFuelFilterIndicator()
    {
        return isset($this->clogged_fuel_filter_indicator);
    }

    public function clearCloggedFuelFilterIndicator()
    {
        unset($this->clogged_fuel_filter_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool clogged_fuel_filter_indicator = 31 [json_name = "clogged_fuel_filter_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setCloggedFuelFilterIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->clogged_fuel_filter_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool water_in_fuel_indicator = 32 [json_name = "water_in_fuel_indicator"];</code>
     * @return bool
     */
    public function getWaterInFuelIndicator()
    {
        return isset($this->water_in_fuel_indicator) ? $this->water_in_fuel_indicator : false;
    }

    public function hasWaterInFuelIndicator()
    {
        return isset($this->water_in_fuel_indicator);
    }

    public function clearWaterInFuelIndicator()
    {
        unset($this->water_in_fuel_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool water_in_fuel_indicator = 32 [json_name = "water_in_fuel_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setWaterInFuelIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->water_in_fuel_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool clogged_brake_system_filter_indicator = 33 [json_name = "clogged_brake_system_filter_indicator"];</code>
     * @return bool
     */
    public function getCloggedBrakeSystemFilterIndicator()
    {
        return isset($this->clogged_brake_system_filter_indicator) ? $this->clogged_brake_system_filter_indicator : false;
    }

    public function hasCloggedBrakeSystemFilterIndicator()
    {
        return isset($this->clogged_brake_system_filter_indicator);
    }

    public function clearCloggedBrakeSystemFilterIndicator()
    {
        unset($this->clogged_brake_system_filter_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool clogged_brake_system_filter_indicator = 33 [json_name = "clogged_brake_system_filter_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setCloggedBrakeSystemFilterIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->clogged_brake_system_filter_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool low_washer_fluid_level_indicator = 34 [json_name = "low_washer_fluid_level_indicator"];</code>
     * @return bool
     */
    public function getLowWasherFluidLevelIndicator()
    {
        return isset($this->low_washer_fluid_level_indicator) ? $this->low_washer_fluid_level_indicator : false;
    }

    public function hasLowWasherFluidLevelIndicator()
    {
        return isset($this->low_washer_fluid_level_indicator);
    }

    public function clearLowWasherFluidLevelIndicator()
    {
        unset($this->low_washer_fluid_level_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool low_washer_fluid_level_indicator = 34 [json_name = "low_washer_fluid_level_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setLowWasherFluidLevelIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->low_washer_fluid_level_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool low_ad_blue_level_indicator = 35 [json_name = "low_ad_blue_level_indicator"];</code>
     * @return bool
     */
    public function getLowAdBlueLevelIndicator()
    {
        return isset($this->low_ad_blue_level_indicator) ? $this->low_ad_blue_level_indicator : false;
    }

    public function hasLowAdBlueLevelIndicator()
    {
        return isset($this->low_ad_blue_level_indicator);
    }

    public function clearLowAdBlueLevelIndicator()
    {
        unset($this->low_ad_blue_level_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool low_ad_blue_level_indicator = 35 [json_name = "low_ad_blue_level_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setLowAdBlueLevelIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->low_ad_blue_level_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool low_trailer_tyre_pressure_indicator = 36 [json_name = "low_trailer_tyre_pressure_indicator"];</code>
     * @return bool
     */
    public function getLowTrailerTyrePressureIndicator()
    {
        return isset($this->low_trailer_tyre_pressure_indicator) ? $this->low_trailer_tyre_pressure_indicator : false;
    }

    public function hasLowTrailerTyrePressureIndicator()
    {
        return isset($this->low_trailer_tyre_pressure_indicator);
    }

    public function clearLowTrailerTyrePressureIndicator()
    {
        unset($this->low_trailer_tyre_pressure_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool low_trailer_tyre_pressure_indicator = 36 [json_name = "low_trailer_tyre_pressure_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setLowTrailerTyrePressureIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->low_trailer_tyre_pressure_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool wear_of_trailer_brake_lining_indicator = 37 [json_name = "wear_of_trailer_brake_lining_indicator"];</code>
     * @return bool
     */
    public function getWearOfTrailerBrakeLiningIndicator()
    {
        return isset($this->wear_of_trailer_brake_lining_indicator) ? $this->wear_of_trailer_brake_lining_indicator : false;
    }

    public function hasWearOfTrailerBrakeLiningIndicator()
    {
        return isset($this->wear_of_trailer_brake_lining_indicator);
    }

    public function clearWearOfTrailerBrakeLiningIndicator()
    {
        unset($this->wear_of_trailer_brake_lining_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool wear_of_trailer_brake_lining_indicator = 37 [json_name = "wear_of_trailer_brake_lining_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setWearOfTrailerBrakeLiningIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->wear_of_trailer_brake_lining_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool high_trailer_brake_temperature_indicator = 38 [json_name = "high_trailer_brake_temperature_indicator"];</code>
     * @return bool
     */
    public function getHighTrailerBrakeTemperatureIndicator()
    {
        return isset($this->high_trailer_brake_temperature_indicator) ? $this->high_trailer_brake_temperature_indicator : false;
    }

    public function hasHighTrailerBrakeTemperatureIndicator()
    {
        return isset($this->high_trailer_brake_temperature_indicator);
    }

    public function clearHighTrailerBrakeTemperatureIndicator()
    {
        unset($this->high_trailer_brake_temperature_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool high_trailer_brake_temperature_indicator = 38 [json_name = "high_trailer_brake_temperature_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setHighTrailerBrakeTemperatureIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->high_trailer_brake_temperature_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool incorrect_trailer_pneumatic_supply_indicator = 39 [json_name = "incorrect_trailer_pneumatic_supply_indicator"];</code>
     * @return bool
     */
    public function getIncorrectTrailerPneumaticSupplyIndicator()
    {
        return isset($this->incorrect_trailer_pneumatic_supply_indicator) ? $this->incorrect_trailer_pneumatic_supply_indicator : false;
    }

    public function hasIncorrectTrailerPneumaticSupplyIndicator()
    {
        return isset($this->incorrect_trailer_pneumatic_supply_indicator);
    }

    public function clearIncorrectTrailerPneumaticSupplyIndicator()
    {
        unset($this->incorrect_trailer_pneumatic_supply_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool incorrect_trailer_pneumatic_supply_indicator = 39 [json_name = "incorrect_trailer_pneumatic_supply_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setIncorrectTrailerPneumaticSupplyIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->incorrect_trailer_pneumatic_supply_indicator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool low_cng_level_indicator = 40 [json_name = "low_cng_level_indicator"];</code>
     * @return bool
     */
    public function getLowCngLevelIndicator()
    {
        return isset($this->low_cng_level_indicator) ? $this->low_cng_level_indicator : false;
    }

    public function hasLowCngLevelIndicator()
    {
        return isset($this->low_cng_level_indicator);
    }

    public function clearLowCngLevelIndicator()
    {
        unset($this->low_cng_level_indicator);
    }

    /**
     * Generated from protobuf field <code>optional bool low_cng_level_indicator = 40 [json_name = "low_cng_level_indicator"];</code>
     * @param bool $var
     * @return $this
     */
    public function setLowCngLevelIndicator($var)
    {
        GPBUtil::checkBool($var);
        $this->low_cng_level_indicator = $var;

        return $this;
    }

}

