<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reports/report.proto

namespace Fatehan\Report\TripsSummaryRequest;

use UnexpectedValueException;

/**
 * Protobuf type <code>com.fatehan.reports.TripsSummaryRequest.GroupBy</code>
 */
class GroupBy
{
    /**
     * Generated from protobuf enum <code>ALL = 0;</code>
     */
    const ALL = 0;
    /**
     * Generated from protobuf enum <code>DAY = 1;</code>
     */
    const DAY = 1;
    /**
     * Generated from protobuf enum <code>MONTH = 2;</code>
     */
    const MONTH = 2;

    private static $valueToName = [
        self::ALL => 'ALL',
        self::DAY => 'DAY',
        self::MONTH => 'MONTH',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

