<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: areas/area.proto

namespace Fatehan\Area\WorkCycle;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.areas.WorkCycle.Event</code>
 */
class Event extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1 [json_name = "device_id"];</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>optional string name = 2 [json_name = "name"];</code>
     */
    protected $name = null;
    /**
     * Generated from protobuf field <code>.com.fatehan.areas.Point entered_point = 3 [json_name = "entered_point"];</code>
     */
    protected $entered_point = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp entered_at = 4 [json_name = "entered_at"];</code>
     */
    protected $entered_at = null;
    /**
     * Generated from protobuf field <code>.com.fatehan.areas.Point exited_point = 5 [json_name = "exited_point"];</code>
     */
    protected $exited_point = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp exited_at = 6 [json_name = "exited_at"];</code>
     */
    protected $exited_at = null;
    /**
     * Generated from protobuf field <code>uint32 mileage = 7 [json_name = "mileage"];</code>
     */
    protected $mileage = 0;
    /**
     * Generated from protobuf field <code>uint32 duration = 8 [json_name = "duration"];</code>
     */
    protected $duration = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type string $name
     *     @type \Fatehan\Area\Point $entered_point
     *     @type \Google\Protobuf\Timestamp $entered_at
     *     @type \Fatehan\Area\Point $exited_point
     *     @type \Google\Protobuf\Timestamp $exited_at
     *     @type int $mileage
     *     @type int $duration
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Area\MetaData\Area::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1 [json_name = "device_id"];</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1 [json_name = "device_id"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string name = 2 [json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return isset($this->name) ? $this->name : '';
    }

    public function hasName()
    {
        return isset($this->name);
    }

    public function clearName()
    {
        unset($this->name);
    }

    /**
     * Generated from protobuf field <code>optional string name = 2 [json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.areas.Point entered_point = 3 [json_name = "entered_point"];</code>
     * @return \Fatehan\Area\Point|null
     */
    public function getEnteredPoint()
    {
        return $this->entered_point;
    }

    public function hasEnteredPoint()
    {
        return isset($this->entered_point);
    }

    public function clearEnteredPoint()
    {
        unset($this->entered_point);
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.areas.Point entered_point = 3 [json_name = "entered_point"];</code>
     * @param \Fatehan\Area\Point $var
     * @return $this
     */
    public function setEnteredPoint($var)
    {
        GPBUtil::checkMessage($var, \Fatehan\Area\Point::class);
        $this->entered_point = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp entered_at = 4 [json_name = "entered_at"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getEnteredAt()
    {
        return $this->entered_at;
    }

    public function hasEnteredAt()
    {
        return isset($this->entered_at);
    }

    public function clearEnteredAt()
    {
        unset($this->entered_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp entered_at = 4 [json_name = "entered_at"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setEnteredAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->entered_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.areas.Point exited_point = 5 [json_name = "exited_point"];</code>
     * @return \Fatehan\Area\Point|null
     */
    public function getExitedPoint()
    {
        return $this->exited_point;
    }

    public function hasExitedPoint()
    {
        return isset($this->exited_point);
    }

    public function clearExitedPoint()
    {
        unset($this->exited_point);
    }

    /**
     * Generated from protobuf field <code>.com.fatehan.areas.Point exited_point = 5 [json_name = "exited_point"];</code>
     * @param \Fatehan\Area\Point $var
     * @return $this
     */
    public function setExitedPoint($var)
    {
        GPBUtil::checkMessage($var, \Fatehan\Area\Point::class);
        $this->exited_point = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp exited_at = 6 [json_name = "exited_at"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getExitedAt()
    {
        return $this->exited_at;
    }

    public function hasExitedAt()
    {
        return isset($this->exited_at);
    }

    public function clearExitedAt()
    {
        unset($this->exited_at);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp exited_at = 6 [json_name = "exited_at"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setExitedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->exited_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 mileage = 7 [json_name = "mileage"];</code>
     * @return int
     */
    public function getMileage()
    {
        return $this->mileage;
    }

    /**
     * Generated from protobuf field <code>uint32 mileage = 7 [json_name = "mileage"];</code>
     * @param int $var
     * @return $this
     */
    public function setMileage($var)
    {
        GPBUtil::checkUint32($var);
        $this->mileage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 duration = 8 [json_name = "duration"];</code>
     * @return int
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * Generated from protobuf field <code>uint32 duration = 8 [json_name = "duration"];</code>
     * @param int $var
     * @return $this
     */
    public function setDuration($var)
    {
        GPBUtil::checkUint32($var);
        $this->duration = $var;

        return $this;
    }

}

