<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reports/report.proto

namespace Fatehan\Report;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.reports.ChartResponse</code>
 */
class ChartResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 cost = 1 [json_name = "cost"];</code>
     */
    protected $cost = 0;
    /**
     * Generated from protobuf field <code>uint32 records = 2 [json_name = "records"];</code>
     */
    protected $records = 0;
    /**
     * Generated from protobuf field <code>map<uint64, .com.fatehan.reports.ChartResponse.Chart> chart = 3 [json_name = "chart"];</code>
     */
    private $chart;
    /**
     * Generated from protobuf field <code>uint32 section = 4 [json_name = "section"];</code>
     */
    protected $section = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $cost
     *     @type int $records
     *     @type array|\Google\Protobuf\Internal\MapField $chart
     *     @type int $section
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Report\MetaData\Report::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 cost = 1 [json_name = "cost"];</code>
     * @return int
     */
    public function getCost()
    {
        return $this->cost;
    }

    /**
     * Generated from protobuf field <code>uint32 cost = 1 [json_name = "cost"];</code>
     * @param int $var
     * @return $this
     */
    public function setCost($var)
    {
        GPBUtil::checkUint32($var);
        $this->cost = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 records = 2 [json_name = "records"];</code>
     * @return int
     */
    public function getRecords()
    {
        return $this->records;
    }

    /**
     * Generated from protobuf field <code>uint32 records = 2 [json_name = "records"];</code>
     * @param int $var
     * @return $this
     */
    public function setRecords($var)
    {
        GPBUtil::checkUint32($var);
        $this->records = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<uint64, .com.fatehan.reports.ChartResponse.Chart> chart = 3 [json_name = "chart"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getChart()
    {
        return $this->chart;
    }

    /**
     * Generated from protobuf field <code>map<uint64, .com.fatehan.reports.ChartResponse.Chart> chart = 3 [json_name = "chart"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setChart($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::UINT64, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fatehan\Report\ChartResponse\Chart::class);
        $this->chart = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 section = 4 [json_name = "section"];</code>
     * @return int
     */
    public function getSection()
    {
        return $this->section;
    }

    /**
     * Generated from protobuf field <code>uint32 section = 4 [json_name = "section"];</code>
     * @param int $var
     * @return $this
     */
    public function setSection($var)
    {
        GPBUtil::checkUint32($var);
        $this->section = $var;

        return $this;
    }

}

