<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reports/report.proto

namespace Fatehan\Report;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>com.fatehan.reports.DriverBehaviorReportResponse</code>
 */
class DriverBehaviorReportResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 cost = 1 [json_name = "cost"];</code>
     */
    protected $cost = 0;
    /**
     * Generated from protobuf field <code>uint32 records = 2 [json_name = "records"];</code>
     */
    protected $records = 0;
    /**
     * Generated from protobuf field <code>repeated .com.fatehan.trips.TripPoint points = 3 [json_name = "points"];</code>
     */
    private $points;
    /**
     * Generated from protobuf field <code>repeated .com.fatehan.reports.DriverBehaviorReportResponse.Chunk chunks = 4 [json_name = "chunks"];</code>
     */
    private $chunks;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $cost
     *     @type int $records
     *     @type \Fatehan\Trip\TripPoint[] $points
     *     @type \Fatehan\Report\DriverBehaviorReportResponse\Chunk[] $chunks
     * }
     */
    public function __construct($data = NULL) {
        \Fatehan\Report\MetaData\Report::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 cost = 1 [json_name = "cost"];</code>
     * @return int
     */
    public function getCost()
    {
        return $this->cost;
    }

    /**
     * Generated from protobuf field <code>uint32 cost = 1 [json_name = "cost"];</code>
     * @param int $var
     * @return $this
     */
    public function setCost($var)
    {
        GPBUtil::checkUint32($var);
        $this->cost = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 records = 2 [json_name = "records"];</code>
     * @return int
     */
    public function getRecords()
    {
        return $this->records;
    }

    /**
     * Generated from protobuf field <code>uint32 records = 2 [json_name = "records"];</code>
     * @param int $var
     * @return $this
     */
    public function setRecords($var)
    {
        GPBUtil::checkUint32($var);
        $this->records = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.trips.TripPoint points = 3 [json_name = "points"];</code>
     * @return RepeatedField<\Fatehan\Trip\TripPoint>
     */
    public function getPoints()
    {
        return $this->points;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.trips.TripPoint points = 3 [json_name = "points"];</code>
     * @param \Fatehan\Trip\TripPoint[] $var
     * @return $this
     */
    public function setPoints($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fatehan\Trip\TripPoint::class);
        $this->points = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.reports.DriverBehaviorReportResponse.Chunk chunks = 4 [json_name = "chunks"];</code>
     * @return RepeatedField<\Fatehan\Report\DriverBehaviorReportResponse\Chunk>
     */
    public function getChunks()
    {
        return $this->chunks;
    }

    /**
     * Generated from protobuf field <code>repeated .com.fatehan.reports.DriverBehaviorReportResponse.Chunk chunks = 4 [json_name = "chunks"];</code>
     * @param \Fatehan\Report\DriverBehaviorReportResponse\Chunk[] $var
     * @return $this
     */
    public function setChunks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Fatehan\Report\DriverBehaviorReportResponse\Chunk::class);
        $this->chunks = $arr;

        return $this;
    }

}

